/*
 * Copyright 2011 Google Inc.
 *
 * Swiffy runtime version 3.2
 *
 * In addition to the Google Terms of Service (http://www.google.com/accounts/TOS),
 * Google grants you and the Google Swiffy end users a personal, worldwide,
 * royalty-free, non-assignable and non-exclusive license to use the Google Swiffy
 * runtime to host it for Google Swiffy end users and to use it in connection with
 * the Google Swiffy service.
 */
var f=void 0,h=null,aa=window,j=Object,ba=Function,k=document,l=Math,ca=Array,da=Error,ea=parseInt,fa=decodeURIComponent;function ga(a,b){return a.data=b}function ha(a,b){return a.currentTarget=b}function ia(a,b){return a.keyCode=b}function ja(a,b){return a.type=b}function ka(a,b){return a.toString=b}function la(a,b){return a.length=b}function ma(a,b){return a.target=b}function na(a,b){return a.call=b}function oa(a,b){return a.returnValue=b}function pa(a,b){return a.apply=b}
var m="appendChild",n="push",qa="ymin",ra="font",sa="indent",ta="getParent",ua="shift",va="ymax",wa="POSITIVE_INFINITY",xa="width",ya="bitmap",Aa="expand",Ba="slice",o="replace",Ca="matrix",Da="setCapture",p="data",Ea="load",Fa="floor",Ga="getNamedItem",Ha="preventDefault",Ia="setAttributeNS",r="indexOf",s="color",Ja="capture",Ka="ratio",La="setTransform",Ma="knockout",Na="getName",Oa="charCode",Qa="getObject",Ra="createElement",t="defineProperty",u="keyCode",Sa="sqrt",x="setAttribute",Ta="play",
Ua="handleEvent",Va="path",y="depth",z="type",Wa="childNodes",Xa="bind",Ya="name",Za="releaseCapture",$a="fill",ab="stop",A="toString",bb="gradient",B="length",cb="propertyIsEnumerable",C="prototype",db="result",eb="inner",fb="actions",D="createElementNS",gb="ctrlKey",F="split",hb="stopPropagation",ib="glyphs",jb="hasOwnProperty",G="style",kb="body",lb="removeChild",mb="target",nb="lastChild",H="call",ob="frameSize",pb="init",qb="returnValue",rb="charCodeAt",sb="colortransform",tb="xmin",ub="trackAsMenu",
I="apply",vb="filters",wb="xmax",xb="navigator",yb="parentNode",zb="update",K="height",Ab="splice",Bb="join",Cb="unshift",Db="isCaptured",Eb="transform",Fb="nodeValue",Gb="quality",Hb="toLowerCase",L,M=this,Ib=function(){},Jb=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof ca)return"array";else if(a instanceof j)return b;var c=j[C][A][H](a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a[B]=="number"&&typeof a[Ab]!="undefined"&&typeof a[cb]!="undefined"&&!a[cb]("splice"))return"array";
if(c=="[object Function]"||typeof a[H]!="undefined"&&typeof a[cb]!="undefined"&&!a[cb]("call"))return"function"}else return"null";else if(b=="function"&&typeof a[H]=="undefined")return"object";return b},N=function(a){return a!==f},Kb=function(a){return Jb(a)=="array"},Lb=function(a){var b=Jb(a);return b=="array"||b=="object"&&typeof a[B]=="number"},Mb=function(a){return typeof a=="string"},Nb=function(a){return Jb(a)=="function"},Ob=function(a){a=Jb(a);return a=="object"||a=="array"||a=="function"},
Rb=function(a){return a[Pb]||(a[Pb]=++Qb)},Pb="closure_uid_"+l[Fa](l.random()*2147483648)[A](36),Qb=0,Sb=function(a,b,c){return a[H][I](a[Xa],arguments)},Tb=function(a,b,c){if(!a)throw da();if(arguments[B]>2){var d=ca[C][Ba][H](arguments,2);return function(){var c=ca[C][Ba][H](arguments);ca[C][Cb][I](c,d);return a[I](b,c)}}else return function(){return a[I](b,arguments)}},Ub=function(a,b,c){Ub=ba[C][Xa]&&ba[C][Xa][A]()[r]("native code")!=-1?Sb:Tb;return Ub[I](h,arguments)},O=function(a,b){var c=ca[C][Ba][H](arguments,
1);return function(){var b=ca[C][Ba][H](arguments);b[Cb][I](b,c);return a[I](this,b)}},P=function(a,b){function c(){}c.prototype=b[C];a.K=b[C];a.prototype=new c};ba[C].bind=ba[C][Xa]||function(a,b){if(arguments[B]>1){var c=ca[C][Ba][H](arguments,1);c[Cb](this,a);return Ub[I](h,c)}else return Ub(this,a)};var Vb=function(a){this.stack=da().stack||"";if(a)this.message=String(a)};P(Vb,da);Vb[C].name="CustomError";var Wb=function(a,b){for(var c=1;c<arguments[B];c++)var d=String(arguments[c])[o](/\$/g,"$$$$"),a=a[o](/\%s/,d);return a},Xb=/^[a-zA-Z0-9\-_.!~*'()]*$/,Yb=function(a){a=String(a);return!Xb.test(a)?encodeURIComponent(a):a},$b=function(a,b){for(var c=0,d=String(a)[o](/^[\s\xa0]+|[\s\xa0]+$/g,"")[F]("."),e=String(b)[o](/^[\s\xa0]+|[\s\xa0]+$/g,"")[F]("."),g=l.max(d[B],e[B]),i=0;c==0&&i<g;i++){var q=d[i]||"",w=e[i]||"",v=RegExp("(\\d*)(\\D*)","g"),Pa=RegExp("(\\d*)(\\D*)","g");do{var J=v.exec(q)||["",
"",""],E=Pa.exec(w)||["","",""];if(J[0][B]==0&&E[0][B]==0)break;c=Zb(J[1][B]==0?0:ea(J[1],10),E[1][B]==0?0:ea(E[1],10))||Zb(J[2][B]==0,E[2][B]==0)||Zb(J[2],E[2])}while(c==0)}return c},Zb=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var ac=function(a,b){b[Cb](a);Vb[H](this,Wb[I](h,b));b[ua]();this.Cg=a};P(ac,Vb);ac[C].name="AssertionError";var Q=function(a,b,c){if(!a){var d=ca[C][Ba][H](arguments,2),e="Assertion failed";if(b){e+=": "+b;var g=d}throw new ac(""+e,g||[]);}return a};var bc=ca[C],cc=bc[r]?function(a,b,c){Q(a[B]!=h);return bc[r][H](a,b,c)}:function(a,b,c){c=c==h?0:c<0?l.max(0,a[B]+c):c;if(Mb(a))return!Mb(b)||b[B]!=1?-1:a[r](b,c);for(;c<a[B];c++)if(c in a&&a[c]===b)return c;return-1},dc=bc.forEach?function(a,b,c){Q(a[B]!=h);bc.forEach[H](a,b,c)}:function(a,b,c){for(var d=a[B],e=Mb(a)?a[F](""):a,g=0;g<d;g++)g in e&&b[H](c,e[g],g,a)},ec=function(a,b){var c=cc(a,b),d;if(d=c>=0)Q(a[B]!=h),bc[Ab][H](a,c,1);return d},fc=function(a,b){for(var c=1;c<arguments[B];c++){var d=
arguments[c],e;if(Kb(d)||(e=Lb(d))&&d[jb]("callee"))a[n][I](a,d);else if(e)for(var g=a[B],i=d[B],q=0;q<i;q++)a[g+q]=d[q];else a[n](d)}},gc=function(a,b,c,d,e){for(var g=0,i=a[B],q;g<i;){var w=g+i>>1,v;v=c?b[H](e,a[w],w,a):b(d,a[w]);v>0?g=w+1:(i=w,q=!v)}return q?g:~g},hc=function(a,b){return a>b?1:a<b?-1:0};var ic=function(a,b,c){for(var d in a)b[H](c,a[d],d,a)},jc="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(","),kc=function(a,b){for(var c,d,e=1;e<arguments[B];e++){d=arguments[e];for(c in d)a[c]=d[c];for(var g=0;g<jc[B];g++)c=jc[g],j[C][jb][H](d,c)&&(a[c]=d[c])}};var lc,mc,nc,oc,pc=function(){return M[xb]?M[xb].userAgent:h};oc=nc=mc=lc=!1;var qc;if(qc=pc()){var rc=M[xb];lc=qc[r]("Opera")==0;mc=!lc&&qc[r]("MSIE")!=-1;nc=!lc&&qc[r]("WebKit")!=-1;oc=!lc&&!nc&&rc.product=="Gecko"}var sc=lc,R=mc,tc=oc,uc=nc,vc=M[xb],wc=(vc&&vc.platform||"")[r]("Mac")!=-1,xc;
a:{var yc="",zc;if(sc&&M.opera)var Ac=M.opera.version,yc=typeof Ac=="function"?Ac():Ac;else if(tc?zc=/rv\:([^\);]+)(\)|;)/:R?zc=/MSIE\s+([^\);]+)(\)|;)/:uc&&(zc=/WebKit\/(\S+)/),zc)var Bc=zc.exec(pc()),yc=Bc?Bc[1]:"";if(R){var Cc,Dc=M.document;Cc=Dc?Dc.documentMode:f;if(Cc>parseFloat(yc)){xc=String(Cc);break a}}xc=yc}var Ec=xc,Fc={},Gc=function(a){return Fc[a]||(Fc[a]=$b(Ec,a)>=0)},Hc={},Ic=function(a){return Hc[a]||(Hc[a]=R&&k.documentMode&&k.documentMode>=a)};!R||Ic(9);!tc&&!R||R&&Ic(9)||tc&&Gc("1.9.1");R&&Gc("9");var Jc=function(a){for(var b;b=a.firstChild;)a[lb](b)},Kc=function(a){return a&&a[yb]?a[yb][lb](a):h},Lc=function(a,b){var c=b[yb];c&&c.replaceChild(a,b)};var Mc=function(a){Mc[" "](a);return a};Mc[" "]=Ib;var Nc;!R||Ic(9);var Oc=R&&!Gc("8");var Pc=function(){};Pc[C].we=!1;Pc[C].Wa=function(){if(!this.we)this.we=!0,this.wa()};Pc[C].wa=function(){this.$f&&Qc[I](h,this.$f)};var Qc=function(a){for(var b=0,c=arguments[B];b<c;++b){var d=arguments[b];Lb(d)?Qc[I](h,d):d&&typeof d.Wa=="function"&&d.Wa()}};var Rc=function(a,b){ja(this,a);ma(this,b);ha(this,this[mb])};P(Rc,Pc);L=Rc[C];L.wa=function(){delete this[z];delete this[mb];delete this.currentTarget};L.Xa=!1;L.Lb=!0;L.stopPropagation=function(){this.Xa=!0};L.preventDefault=function(){this.Lb=!1};var Sc=function(a,b){a&&this[pb](a,b)};P(Sc,Rc);L=Sc[C];ma(L,h);L.relatedTarget=h;L.offsetX=0;L.offsetY=0;L.clientX=0;L.clientY=0;L.screenX=0;L.screenY=0;L.button=0;ia(L,0);L.charCode=0;L.ctrlKey=!1;L.altKey=!1;L.shiftKey=!1;L.metaKey=!1;L.Af=!1;L.Ea=h;
L.init=function(a,b){var c=ja(this,a[z]);Rc[H](this,c);ma(this,a[mb]||a.srcElement);ha(this,b);var d=a.relatedTarget;if(d){if(tc){var e;a:{try{Mc(d.nodeName);e=!0;break a}catch(g){}e=!1}e||(d=h)}}else if(c=="mouseover")d=a.fromElement;else if(c=="mouseout")d=a.toElement;this.relatedTarget=d;this.offsetX=a.offsetX!==f?a.offsetX:a.layerX;this.offsetY=a.offsetY!==f?a.offsetY:a.layerY;this.clientX=a.clientX!==f?a.clientX:a.pageX;this.clientY=a.clientY!==f?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=
a.screenY||0;this.button=a.button;ia(this,a[u]||0);this.charCode=a[Oa]||(c=="keypress"?a[u]:0);this.ctrlKey=a[gb];this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Af=wc?a.metaKey:a[gb];this.state=a.state;this.Ea=a;delete this.Lb;delete this.Xa};L.stopPropagation=function(){Sc.K[hb][H](this);this.Ea[hb]?this.Ea[hb]():this.Ea.cancelBubble=!0};
L.preventDefault=function(){Sc.K[Ha][H](this);var a=this.Ea;if(a[Ha])a[Ha]();else if(oa(a,!1),Oc)try{(a[gb]||a[u]>=112&&a[u]<=123)&&ia(a,-1)}catch(b){}};L.wa=function(){Sc.K.wa[H](this);this.Ea=h;ma(this,h);ha(this,h);this.relatedTarget=h};var Tc=function(a,b){this.oe=b;this.Ya=[];this.Nf(a)};P(Tc,Pc);L=Tc[C];L.zd=h;L.xe=h;L.Sb=function(a){this.zd=a};L.getObject=function(){return this.Ya[B]?this.Ya.pop():this.ve()};L.Rb=function(a){this.Ya[B]<this.oe?this.Ya[n](a):this.fe(a)};L.Nf=function(a){if(a>this.oe)throw da("[goog.structs.SimplePool] Initial cannot be greater than max");for(var b=0;b<a;b++)this.Ya[n](this.ve())};L.ve=function(){return this.zd?this.zd():{}};
L.fe=function(a){if(this.xe)this.xe(a);else if(Ob(a))if(Nb(a.Wa))a.Wa();else for(var b in a)delete a[b]};L.wa=function(){Tc.K.wa[H](this);for(var a=this.Ya;a[B];)this.fe(a.pop());delete this.Ya};var Uc,Vc=(Uc="ScriptEngine"in M&&M.ScriptEngine()=="JScript")?M.ScriptEngineMajorVersion()+"."+M.ScriptEngineMinorVersion()+"."+M.ScriptEngineBuildVersion():"0";var Wc=function(){},Xc=0;L=Wc[C];L.key=0;L.pb=!1;L.ke=!1;L.init=function(a,b,c,d,e,g){if(Nb(a))this.je=!0;else if(a&&a[Ua]&&Nb(a[Ua]))this.je=!1;else throw da("Invalid listener argument");this.Kb=a;this.$d=b;this.src=c;ja(this,d);this.capture=!!e;this.od=g;this.ke=!1;this.key=++Xc;this.pb=!1};L.handleEvent=function(a){return this.je?this.Kb[H](this.od||this.src,a):this.Kb[Ua][H](this.Kb,a)};var Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd;
(function(){function a(){return{s:0,ja:0}}function b(){return[]}function c(){var a=function(b){b=i[H](a.src,a.key,b);if(!b)return b};return a}function d(){return new Wc}function e(){return new Sc}var g=Uc&&!($b(Vc,"5.7")>=0),i;cd=function(a){i=a};if(g){Yc=function(){return q[Qa]()};Zc=function(a){q.Rb(a)};$c=function(){return w[Qa]()};ad=function(a){w.Rb(a)};bd=function(){return v[Qa]()};dd=function(){v.Rb(c())};ed=function(){return Pa[Qa]()};fd=function(a){Pa.Rb(a)};gd=function(){return J[Qa]()};
hd=function(a){J.Rb(a)};var q=new Tc(0,600);q.Sb(a);var w=new Tc(0,600);w.Sb(b);var v=new Tc(0,600);v.Sb(c);var Pa=new Tc(0,600);Pa.Sb(d);var J=new Tc(0,600);J.Sb(e)}else Yc=a,Zc=Ib,$c=b,ad=Ib,bd=c,dd=Ib,ed=d,fd=Ib,gd=e,hd=Ib})();var id={},S={},jd={},kd={},T=function(a,b,c,d,e){if(b)if(Kb(b)){for(var g=0;g<b[B];g++)T(a,b[g],c,d,e);return h}else{var d=!!d,i=S;b in i||(i[b]=Yc());i=i[b];d in i||(i[d]=Yc(),i.s++);var i=i[d],q=Rb(a),w;i.ja++;if(i[q]){w=i[q];for(g=0;g<w[B];g++)if(i=w[g],i.Kb==c&&i.od==e){if(i.pb)break;return w[g].key}}else w=i[q]=$c(),i.s++;g=bd();g.src=a;i=ed();i[pb](c,g,a,b,d,e);c=i.key;g.key=c;w[n](i);id[c]=i;jd[q]||(jd[q]=$c());jd[q][n](i);a.addEventListener?(a==M||!a.ae)&&a.addEventListener(b,g,d):a.attachEvent(b in
kd?kd[b]:kd[b]="on"+b,g);return c}else throw da("Invalid event type");},ld=function(a,b,c,d,e){if(Kb(b)){for(var g=0;g<b[B];g++)ld(a,b[g],c,d,e);return h}d=!!d;a:{g=S;if(b in g&&(g=g[b],d in g&&(g=g[d],a=Rb(a),g[a]))){a=g[a];break a}a=h}if(!a)return!1;for(g=0;g<a[B];g++)if(a[g].Kb==c&&a[g][Ja]==d&&a[g].od==e)return md(a[g].key);return!1},md=function(a){if(!id[a])return!1;var b=id[a];if(b.pb)return!1;var c=b.src,d=b[z],e=b.$d,g=b[Ja];c.removeEventListener?(c==M||!c.ae)&&c.removeEventListener(d,e,g):
c.detachEvent&&c.detachEvent(d in kd?kd[d]:kd[d]="on"+d,e);c=Rb(c);e=S[d][g][c];if(jd[c]){var i=jd[c];ec(i,b);i[B]==0&&delete jd[c]}b.pb=!0;e.de=!0;nd(d,g,c,e);delete id[a];return!0},nd=function(a,b,c,d){if(!d.zc&&d.de){for(var e=0,g=0;e<d[B];e++)if(d[e].pb){var i=d[e].$d;i.src=h;dd(i);fd(d[e])}else e!=g&&(d[g]=d[e]),g++;la(d,g);d.de=!1;g==0&&(ad(d),delete S[a][b][c],S[a][b].s--,S[a][b].s==0&&(Zc(S[a][b]),delete S[a][b],S[a].s--),S[a].s==0&&(Zc(S[a]),delete S[a]))}},od=function(a,b,c){var d=0,e=b==
h,g=c==h,c=!!c;if(a==h)ic(jd,function(a){for(var i=a[B]-1;i>=0;i--){var q=a[i];if((e||b==q[z])&&(g||c==q[Ja]))md(q.key),d++}});else if(a=Rb(a),jd[a])for(var a=jd[a],i=a[B]-1;i>=0;i--){var q=a[i];if((e||b==q[z])&&(g||c==q[Ja]))md(q.key),d++}return d},qd=function(a,b,c,d,e){var g=1,b=Rb(b);if(a[b]){a.ja--;a=a[b];a.zc?a.zc++:a.zc=1;try{for(var i=a[B],q=0;q<i;q++){var w=a[q];w&&!w.pb&&(g&=pd(w,e)!==!1)}}finally{a.zc--,nd(c,d,b,a)}}return Boolean(g)},pd=function(a,b){var c=a[Ua](b);a.ke&&md(a.key);return c};
cd(function(a,b){if(!id[a])return!0;var c=id[a],d=c[z],e=S;if(!(d in e))return!0;var e=e[d],g,i;Nc===f&&(Nc=R&&!M.addEventListener);if(Nc){var q;if(!(q=b))a:{q="window.event"[F](".");for(var w=M;g=q[ua]();)if(w[g]!=h)w=w[g];else{q=h;break a}q=w}g=q;q=!0 in e;w=!1 in e;if(q){if(g[u]<0||g[qb]!=f)return!0;a:{var v=!1;if(g[u]==0)try{ia(g,-1);break a}catch(Pa){v=!0}(v||g[qb]==f)&&oa(g,!0)}}v=gd();v[pb](g,this);g=!0;try{if(q){for(var J=$c(),E=v.currentTarget;E;E=E[yb])J[n](E);i=e[!0];i.ja=i.s;for(var za=
J[B]-1;!v.Xa&&za>=0&&i.ja;za--)ha(v,J[za]),g&=qd(i,J[za],d,!0,v);if(w){i=e[!1];i.ja=i.s;for(za=0;!v.Xa&&za<J[B]&&i.ja;za++)ha(v,J[za]),g&=qd(i,J[za],d,!1,v)}}else g=pd(c,v)}finally{J&&(la(J,0),ad(J)),v.Wa(),hd(v)}return g}d=new Sc(b,this);try{g=pd(c,d)}finally{d.Wa()}return g});var rd=function(){};P(rd,Pc);L=rd[C];L.ae=!0;L.kd=h;L.addEventListener=function(a,b,c,d){T(this,a,b,c,d)};L.removeEventListener=function(a,b,c,d){ld(this,a,b,c,d)};
L.dispatchEvent=function(a){var b=a[z]||a,c=S;if(b in c){if(Mb(a))a=new Rc(a,this);else if(a instanceof Rc)ma(a,a[mb]||this);else{var d=a,a=new Rc(b,this);kc(a,d)}var d=1,e,c=c[b],b=!0 in c,g;if(b){e=[];for(g=this;g;g=g.kd)e[n](g);g=c[!0];g.ja=g.s;for(var i=e[B]-1;!a.Xa&&i>=0&&g.ja;i--)ha(a,e[i]),d&=qd(g,e[i],a[z],!0,a)&&a.Lb!=!1}if(!1 in c)if(g=c[!1],g.ja=g.s,b)for(i=0;!a.Xa&&i<e[B]&&g.ja;i++)ha(a,e[i]),d&=qd(g,e[i],a[z],!1,a)&&a.Lb!=!1;else for(e=this;!a.Xa&&e&&g.ja;e=e.kd)ha(a,e),d&=qd(g,e,a[z],
!1,a)&&a.Lb!=!1;a=Boolean(d)}else a=!0;return a};L.wa=function(){rd.K.wa[H](this);od(this);this.kd=h};var td=function(a,b,c,d,e){if(!R&&(!uc||!Gc("525")))return!0;if(wc&&e)return sd(a);if(e&&!d)return!1;if(!c&&(b==17||b==18))return!1;if(R&&d&&b==a)return!1;switch(a){case 13:return!(R&&Ic(9));case 27:return!uc}return sd(a)},sd=function(a){if(a>=48&&a<=57)return!0;if(a>=96&&a<=106)return!0;if(a>=65&&a<=90)return!0;if(uc&&a==0)return!0;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;
default:return!1}};var ud=function(a,b){a&&this.Zf(a,b)};P(ud,rd);L=ud[C];L.Pb=h;L.Bc=h;L.qd=h;L.Cc=h;L.Oa=-1;L.Na=-1;
var vd={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},wd={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},xd={61:187,59:186},yd=R||uc&&Gc("525");L=ud[C];
L.yf=function(a){if(uc&&(this.Oa==17&&!a[gb]||this.Oa==18&&!a.altKey))this.Na=this.Oa=-1;yd&&!td(a[u],this.Oa,a.shiftKey,a[gb],a.altKey)?this[Ua](a):this.Na=tc&&a[u]in xd?xd[a[u]]:a[u]};L.zf=function(){this.Na=this.Oa=-1};
L.handleEvent=function(a){var b=a.Ea,c,d;R&&a[z]=="keypress"?(c=this.Na,d=c!=13&&c!=27?b[u]:0):uc&&a[z]=="keypress"?(c=this.Na,d=b[Oa]>=0&&b[Oa]<63232&&sd(c)?b[Oa]:0):sc?(c=this.Na,d=sd(c)?b[u]:0):(c=b[u]||this.Na,d=b[Oa]||0,wc&&d==63&&!c&&(c=191));var e=c,g=b.keyIdentifier;c?c>=63232&&c in vd?e=vd[c]:c==25&&a.shiftKey&&(e=9):g&&g in wd&&(e=wd[g]);a=e==this.Oa;this.Oa=e;b=new zd(e,d,a,b);try{this.dispatchEvent(b)}finally{b.Wa()}};
L.Zf=function(a,b){this.Cc&&this.detach();this.Pb=a;this.Bc=T(this.Pb,"keypress",this,b);this.qd=T(this.Pb,"keydown",this.yf,b,this);this.Cc=T(this.Pb,"keyup",this.zf,b,this)};L.detach=function(){if(this.Bc)md(this.Bc),md(this.qd),md(this.Cc),this.Cc=this.qd=this.Bc=h;this.Pb=h;this.Na=this.Oa=-1};L.wa=function(){ud.K.wa[H](this);this.detach()};var zd=function(a,b,c,d){d&&this[pb](d,f);ja(this,"key");ia(this,a);this.charCode=b;this.repeat=c};P(zd,Sc);var Ad=function(){};(function(a){a.xa=function(){return a.Qf||(a.Qf=new a)}})(Ad);Ad[C].ag=0;Ad[C].Ja=function(){return":"+(this.ag++)[A](36)};Ad.xa();var Bd="StopIteration"in M?M.StopIteration:da("StopIteration"),Cd=function(){};Cd[C].next=function(){throw Bd;};Cd[C].Xf=function(){return this};var Dd=function(a,b){this.Ma={};this.P=[];var c=arguments[B];if(c>1){if(c%2)throw da("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.wf(a)};L=Dd[C];L.s=0;L.pd=0;L.Ac=function(){this.ud();for(var a=[],b=0;b<this.P[B];b++)a[n](this.Ma[this.P[b]]);return a};L.Nb=function(){this.ud();return this.P.concat()};L.qb=function(a){return j[C][jb][H](this.Ma,a)};
L.ud=function(){if(this.s!=this.P[B]){for(var a=0,b=0;a<this.P[B];){var c=this.P[a];j[C][jb][H](this.Ma,c)&&(this.P[b++]=c);a++}la(this.P,b)}if(this.s!=this.P[B]){for(var d={},b=a=0;a<this.P[B];)c=this.P[a],j[C][jb][H](d,c)||(this.P[b++]=c,d[c]=1),a++;la(this.P,b)}};L.get=function(a,b){return j[C][jb][H](this.Ma,a)?this.Ma[a]:b};L.set=function(a,b){j[C][jb][H](this.Ma,a)||(this.s++,this.P[n](a),this.pd++);this.Ma[a]=b};
L.wf=function(a){var b;if(a instanceof Dd)b=a.Nb(),a=a.Ac();else{b=[];var c=0,d;for(d in a)b[c++]=d;c=[];d=0;for(var e in a)c[d++]=a[e];a=c}for(e=0;e<b[B];e++)this.set(b[e],a[e])};L.Xf=function(a){this.ud();var b=0,c=this.P,d=this.Ma,e=this.pd,g=this,i=new Cd;i.next=function(){for(;;){if(e!=g.pd)throw da("The map has changed since the iterator was created");if(b>=c[B])throw Bd;var i=c[b++];return a?i:d[i]}};return i};var Ed=function(a,b,c){this.rb=a||h;this.se=b||h;this.Of=!!c};L=Ed[C];L.ob=function(){if(!this.M&&(this.M=new Dd,this.s=0,this.rb))for(var a=this.rb[F]("&"),b=0;b<a[B];b++){var c=a[b][r]("="),d=h,e=h;c>=0?(d=a[b].substring(0,c),e=a[b].substring(c+1)):d=a[b];d=fa(d[o](/\+/g," "));d=this.nb(d);this.add(d,e?fa(e[o](/\+/g," ")):"")}};L.M=h;L.s=h;L.add=function(a,b){this.ob();this.Zd();a=this.nb(a);if(this.qb(a)){var c=this.M.get(a);Kb(c)?c[n](b):this.M.set(a,[c,b])}else this.M.set(a,b);this.s++;return this};
L.qb=function(a){this.ob();a=this.nb(a);return this.M.qb(a)};L.Nb=function(){this.ob();for(var a=this.M.Ac(),b=this.M.Nb(),c=[],d=0;d<b[B];d++){var e=a[d];if(Kb(e))for(var g=0;g<e[B];g++)c[n](b[d]);else c[n](b[d])}return c};L.Ac=function(a){this.ob();if(a)if(a=this.nb(a),this.qb(a)){var b=this.M.get(a);if(Kb(b))return b;else a=[],a[n](b)}else a=[];else for(var b=this.M.Ac(),a=[],c=0;c<b[B];c++){var d=b[c];Kb(d)?fc(a,d):a[n](d)}return a};
L.set=function(a,b){this.ob();this.Zd();a=this.nb(a);if(this.qb(a)){var c=this.M.get(a);Kb(c)?this.s-=c[B]:this.s--}this.M.set(a,b);this.s++;return this};L.get=function(a,b){this.ob();a=this.nb(a);if(this.qb(a)){var c=this.M.get(a);return Kb(c)?c[0]:c}else return b};
ka(L,function(){if(this.rb)return this.rb;if(!this.M)return"";for(var a=[],b=0,c=this.M.Nb(),d=0;d<c[B];d++){var e=c[d],g=Yb(e),e=this.M.get(e);if(Kb(e))for(var i=0;i<e[B];i++)b>0&&a[n]("&"),a[n](g),e[i]!==""&&a[n]("=",Yb(e[i])),b++;else b>0&&a[n]("&"),a[n](g),e!==""&&a[n]("=",Yb(e)),b++}return this.rb=a[Bb]("")});L.Zd=function(){delete this.pg;delete this.rb;this.se&&delete this.se.og};L.nb=function(a){a=String(a);this.Of&&(a=a[Hb]());return a};var U=function(a,b){this.x=a;this.y=b};U[C].W=function(a){var b=this.x*a.b+this.y*a.d+a.f;this.x=this.x*a.a+this.y*a.c+a.e;this.y=b};var V=function(a,b,c,d,e,g){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e;this.f=g};L=V[C];L.Yc=function(){var a=this.a*this.d-this.b*this.c;return new V(this.d/a,-this.b/a,-this.c/a,this.a/a,(this.c*this.f-this.d*this.e)/a,(this.b*this.e-this.a*this.f)/a)};
L.Jf=function(a){var b=l.cos(a),a=l.sin(a);return new V(this.a*b-this.c*a,this.b*b-this.d*a,this.a*a+this.c*b,this.b*a+this.d*b,this.e,this.f)};L.Gc=function(a,b){return new V(this.a*a,this.b*a,this.c*b,this.d*b,this.e,this.f)};L.translate=function(a,b){return new V(this.a,this.b,this.c,this.d,this.e+a,this.f+b)};ka(L,function(){return"matrix("+this.a+" "+this.b+" "+this.c+" "+this.d+" "+this.e+" "+this.f+")"});
L.multiply=function(a){return new V(this.a*a.a+this.c*a.b,this.b*a.a+this.d*a.b,this.a*a.c+this.c*a.d,this.b*a.c+this.d*a.d,this.a*a.e+this.c*a.f+this.e,this.b*a.e+this.d*a.f+this.f)};var Fd=function(a,b,c,d,e,g,i){this.qc=a;this.pc=b;this.oc=c;this.nc=d;this.mc=e;this.lc=g;this.jb=i};Fd[C].lf=function(a){return a!=h&&this.qc==a.qc&&this.pc==a.pc&&this.oc==a.oc&&this.nc==a.nc&&this.mc==a.mc&&this.lc==a.lc};
var Gd=function(a,b,c,d){this.Vd();if(N(a))this.v=a;if(N(b))this.w=b;if(N(c))this.z=c;if(N(d))this.A=d};L=Gd[C];L.Vd=function(){this.v=Number[wa];this.z=Number.NEGATIVE_INFINITY;this.w=Number[wa];this.A=Number.NEGATIVE_INFINITY};L.expand=function(a){if(a.x<this.v)this.v=a.x;if(a.x>this.z)this.z=a.x;if(a.y<this.w)this.w=a.y;if(a.y>this.A)this.A=a.y};L.add=function(a){this.w+=a.w;this.A+=a.A;this.v+=a.v;this.z+=a.z};
L.W=function(a){var b=new U(this.v,this.w),c=new U(this.v,this.A),d=new U(this.z,this.w),e=new U(this.z,this.A);this.Vd();b.W(a);c.W(a);d.W(a);e.W(a);this[Aa](b);this[Aa](c);this[Aa](d);this[Aa](e)};L.ef=function(a){return(this.v>=a.v&&this.v<=a.z||this.z>=a.v&&this.z<=a.z||a.v>=this.v&&a.v<=this.z)&&(this.w>=a.w&&this.w<=a.A||this.A>=a.w&&this.A<=a.A||a.w>=this.w&&a.w<=this.A)};L.contains=function(a,b){return a>=this.v&&a<=this.z&&b>=this.w&&b<=this.A};
L.Lf=function(a){this[Aa](new U(a.v,a.w));this[Aa](new U(a.v,a.A));this[Aa](new U(a.z,a.w));this[Aa](new U(a.z,a.A))};var Hd=function(){},Id={};Hd.registerClass=function(a,b){if(arguments[B]<2)return!1;Id[a]=b;return!0};var Jd=function(a,b,c,d,e,g,i){N(a)&&N(b)?(c=N(c)?c:1,d=N(d)?d:0,e=N(e)?e:0,g=N(g)?g:0,i=N(i)?i:0,this.Ad=new Date(a,b,c,d,e,g,i)):this.Ad=N(a)?new Date(a):new Date;if(!Jd[C].getDate){a=j.getOwnPropertyNames(this.Ad.__proto__);for(b=0;b<a[B];b++)a[b]!="constructor"&&(Jd[C][a[b]]=O(function(a,b){return this.Ad[a](b)},a[b]))}};P(Jd,Hd);Jd.UTC=Date.UTC;var Kd=function(){switch(arguments[B]){case 0:break;case 1:la(this,arguments[0]);break;default:for(var a=0;a<arguments[B];++a)this[n](arguments[a])}};P(Kd,ca);var Ld=function(){},Md={},Nd=0,Od=0,Pd=[];Ld.addListener=function(a){N(a)&&"onKeyUp"in a&&"onKeyDown"in a&&(cc(Pd,a)>=0||Pd[n](a))};Ld.getAscii=function(){return Od};Ld.getCode=function(){return Nd};Ld.isDown=function(a){return Md[a]?!0:!1};Ld.isToggled=function(){return!1};Ld.removeListener=function(a){ec(Pd,a)};
j.defineProperties(Ld,{BACKSPACE:{value:8,H:!0},CAPSLOCK:{value:20,H:!0},CONTROL:{value:17,H:!0},DELETEKEY:{value:46,H:!0},DOWN:{value:40,H:!0},END:{value:35,H:!0},ENTER:{value:13,H:!0},ESCAPE:{value:27,H:!0},HOME:{value:36,H:!0},INSERT:{value:45,H:!0},LEFT:{value:37,H:!0},PGDN:{value:34,H:!0},PGUP:{value:33,H:!0},RIGHT:{value:39,H:!0},SHIFT:{value:16,H:!0},SPACE:{value:32,H:!0},TAB:{value:9,H:!0},UP:{value:38,H:!0}});
T(k,"keyup",function(a){Nd=a[u];Md[a[u]]=!1;for(a=0;a<Pd[B];++a)Pd[a].onKeyUp()},!1);T(new ud(k),"key",function(a){Nd=a[u];Od=a[Oa];Md[a[u]]=!0;for(a=0;a<Pd[B];++a)Pd[a].onKeyDown()},!1);var Qd=function(a){this.O=a;this.lb=[];T(this.O.ea(),"mousedown",this.tb,!0,this);T(this.O.ea(),"mouseup",this.ub,!0,this);T(this.O.ea(),"mousemove",this.Tc,!0,this)};L=Qd[C];L.Ca=!0;L.update=function(){this.O.ea()[G].cursor=this.Ca?this.O.cb()?"pointer":this.O.of()?"pointer":!this.O[Db]()&&this.O.pf()?"pointer":"default":"none"};L.tb=function(){dc(this.lb,function(a){a.qg()})};L.Tc=function(){dc(this.lb,function(a){a.rg()})};L.ub=function(){dc(this.lb,function(a){a.sg()})};
Qd[C].addListener=function(a){if(N(a)){var b=this.O.p().h(a,"onMouseMove"),c=this.O.p().h(a,"onMouseUp");this.O.p().h(a,"onMouseDown")in a&&b in a&&c in a&&(cc(this.lb,a)>=0||this.lb[n](a))}};Qd[C].hide=function(){var a=this.Ca;this.Ca=!1;this[zb]();return a};Qd[C].show=function(){var a=this.Ca;this.Ca=!0;this[zb]();return a};Qd[C].removeListener=function(a){ec(this.lb,a)};var Vd=function(a,b,c,d){b=h;switch(a[z]){case 2:c=Rd("linearGradient",a,d);c[x]("x1",-16384);c[x]("x2",16384);b=c;break;case 3:case 4:c=Rd("radialGradient",a,d);c[x]("r",16384);c[x]("cx",0);c[x]("cy",0);a[bb].f&&d.ba(c,"fx",a[bb].f,function(a){return a*16384});b=c;break;case 5:case 7:if(d=k.getElementById("defmain").querySelector("#def"+a[ya]))c=Sd(Td(a[Eb]),c[0]),b=Ud(a,c,d[xa].baseVal.value,d[K].baseVal.value)}if(a[bb]&&a[bb].spread)switch(a[bb].spread){case 1:b[x]("spreadMethod","reflect");break;
case 2:b[x]("spreadMethod","repeat")}if(a[bb]&&a[bb].interpolation)switch(a[bb].interpolation){case 1:b[x]("color-interpolation","linearRGB")}if(b!=h)b.id=Ad.xa().Ja();return b},Rd=function(a,b,c){a=k[D]("http://www.w3.org/2000/svg",a);a[x]("gradientUnits","userSpaceOnUse");b[Eb]&&c.ba(a,"gradientTransform",b[Eb],Td);for(var d=0;d<b[bb].stops[B];d++)a[m](Wd(b[bb].stops[d],c));return a},Wd=function(a,b){var c=k[D]("http://www.w3.org/2000/svg","stop");b.ba(c,"offset",a.offset,function(a){return a/255});
b.ba(c,"stop-color",a[s],Xd);b.ba(c,"stop-opacity",a[s],Yd);return c},Zd=function(a,b,c,d){switch(b[z]){case 1:c.ba(a,"fill",b[s],Xd);c.ba(a,"fill-opacity",b[s],Yd);break;case 2:case 3:case 4:a[x]("fill","url(#"+d.id+")")}};function $d(a,b){this.le=a;this.me=b}
var Sd=function(a,b){function c(a,b){e.x=a;e.y=b;e.W(d);g[n](e.x);i[n](e.y)}var d=a.Yc(),e=new U(0,0),g=[],i=[];c(b[tb],b[qa]);c(b[wb],b[qa]);c(b[tb],b[va]);c(b[wb],b[va]);return new $d(g,i)},Ud=function(a,b,c,d){var e=k[D]("http://www.w3.org/2000/svg","g");e.id=Ad.xa().Ja();var g=k[D]("http://www.w3.org/2000/svg","g"),i=k[D]("http://www.w3.org/2000/svg","g");i[m](e);i[m](g);for(var q=l[Fa](l.min[I](l,b.le)/c),w=l.ceil(l.max[I](l,b.le)/c);q<w;q++){var v=k[D]("http://www.w3.org/2000/svg","use");v[Ia]("http://www.w3.org/1999/xlink",
"href","#def"+a[ya]);v[x]("x",q*c);e[m](v)}a=l[Fa](l.min[I](l,b.me)/d);for(b=l.ceil(l.max[I](l,b.me)/d);a<b;a++)c=k[D]("http://www.w3.org/2000/svg","use"),c[Ia]("http://www.w3.org/1999/xlink","href","#"+e.id),c[x]("y",a*d),g[m](c);return i};var ae=function(a,b,c,d){if(b!=h){if(b[$a]!=h)a[x]("stroke","url(#"+d.id+")");else if(b[s]!=h)c.ba(a,"stroke",b[s],Xd),c.ba(a,"stroke-opacity",b[s],function(a){return a?Yd(a):1});else a[x]("stroke","rgb(0,0,0)");c.ba(a,"stroke-width",b[xa],function(a){return l.max(14,a)});c="round";if(b.cap!=h)switch(b.cap){case 1:c="butt";break;case 2:c="square"}a[x]("stroke-linecap",c);c="round";if(b.joint!=h)switch(b.joint){case 1:c="bevel";break;case 2:c="miter"}a[x]("stroke-linejoin",c);b.miter!=h&&a[x]("stroke-miterlimit",
b.miter)}};var be=function(){this.C={}};be[C].Ga=function(a,b){this.C[a]=b};be[C].Gf=function(a){return this.C[a]||h};be[C].De=function(a,b){this.C[a]&&this.C[a].If(b)};var ce=function(a){this.q=[];this.ie=!1;this.We=a;this.tc=[]};L=ce[C];L.Q=function(){this.Wd=this.ie?k[D]("http://www.w3.org/2000/svg","clipPath"):k[D]("http://www.w3.org/2000/svg","g")};L.U=function(){return this.Wd};L.bb=function(a,b){a.depth=b;for(var c,d=0;d<this.q[B];++d){var e=this.q[d],g=e[y];if(b>g)b<=e.la&&a.Xd(e);else{Q(b<g);N(c)||(c=e.U(),c[yb]&&c[yb].insertBefore(a.U(),c),c=d);if(g>a.la)break;e.Xd(a)}}if(N(c))this.q[Ab](c,0,a);else this.Wd[m](a.U()),this.q[n](a);de(this.m,a)};
L.vd=function(a){return gc(this.q,function(a,c){return a-c[y]}||hc,!1,a)};L.ad=function(a){a=this.vd(a);return a>=0?this.Dc(a):h};L.ff=function(a){a.Td();Kc(a.U())};L.Dc=function(a,b){var c=this.q[a],d=c[y];this.ff(c);b!=!0&&(c.Ud()?(c.Ka(),this.tc[n](c)):(ee(this.m,c),c.R()));this.q[Ab](a,1);if(c.la>0)for(var e=a;e<this.q[B];++e){var g=this.q[e],i=g[y];if(i>c.la)break;i>d&&g.Td()}c.depth=f;return c};L.ye=function(a){a=this.vd(a);return a<0?h:this.Dc(a,!0)};
L.tf=function(a){for(var b=0;b<this.q[B];++b)if(this.q[b]==a)return this.Dc(b)};L.Xc=function(a){a=this.vd(a);return a>=0?this.q[a]:h};L.R=function(){for(var a=0;a<this.q[B];a++)this.Dc(a)};L.Ka=function(){for(var a=0;a<this.q[B];a++)this.q[a].Ka()};L.qf=function(){for(var a=0;a<this.tc[B];a++){var b=this.tc[a];b.R();ee(this.m,b)}this.tc=[]};L.Fe=function(a){this.ie=a};L.ua=function(a){for(var b=0;b<this.q[B];++b)this.q[b].ua(a)};
L.Y=function(a){for(var b=!1,c=0;c<this.q[B];++c)b=this.q[c].Y(a)||b;return b};L.Jd=function(a){this.m=a;for(var b=0;b<this.q[B];++b)de(a,this.q[b])};L.rd=function(a,b){this.m&&(ee(this.m,a),b&&de(this.m,a,b))};L.wd=function(a,b){var c=this.ye(a),d=this.ye(b);c&&this.bb(c,b);d&&this.bb(d,a)};var de=function(a,b,c){a&&(N(c)||(c=b[Na]()),c&&j[t](a,c,{get:function(){return b.I()},set:function(){},configurable:!0}))},ee=function(a,b){if(a){var c=b[Na]();c&&delete a[c]}};
ce[C].hf=function(a){for(var b=0,c=0;b<this.q[B]||c<a.q[B];){var d=this.q[b],e=a.q[c],g=d?d[y]:Number[wa],i=e?e[y]:Number[wa];i<g?(e instanceof fe&&e[Ea](),this.bb(e,i),c++,b++):i>g?d.zb()?b++:this.ad(g):(Q(g==i),Q(d&&e),d.zb()||(!d.Sa()||!e.Sa()||d.Cb!=e.Cb?(this.ad(i),e instanceof fe&&e[Ea](),this.bb(e,i)):(d[La](e.D()),d.ma(e.Ha()),e.R())),b++,c++)}};var W=function(){this.la=0;this.va=this.kb=this.ta=h;this.Eb="";this.La=h;this.aa=!1;this.Nc="";this.rc=new ge(this);this.ec=[];this.Ca=!0;this.Cb=0;this.Sd=this.Od=!1};L=W[C];L.Q=function(){this.S=this.Ta=this.Pa()};L.I=function(){var a=this.m;if(!a)a=new X,a.__swiffy_d=this,a.__swiffy_dm=!1,this.m=a;return a};L.zb=function(){return this.m!=f&&this.m.__swiffy_dm};L.U=function(){return this.S};
L.setTransform=function(a){this.td=a;var b=a[A]()+" "+this.Nc;this.la>0?dc(this.Ta[Wa],function(a){a[x]("transform",b)}):this.Ta[x]("transform",b);this.aa=!0};L.D=function(){if(!this.td)this.td=new V(1,0,0,1,0,0);return this.td};L.af=function(a){this.la=a};L.ic=function(a){this.Cb=a};L.R=function(){this.Sd=!0;this.ta!=h&&Kc(this.ta)};L.Ka=function(){this.Od=!0};L.ma=function(a){this.aa|=this.rc.ma(a)};L.Ha=function(){return this.rc.Ha()};
L.ya=function(){var a;a=h;for(var b=this.S;b instanceof SVGElement;){if(b[Eb]){var c=b[Eb].baseVal.consolidate();c!=h&&(a=a!=h?c[Ca].multiply(a):c[Ca])}b=b[yb]}return a!=h?new V(a.a,a.b,a.c,a.d,a.e,a.f):new V(1,0,0,1,0,0)};L.Xd=function(a){if(this.va==h)this.va=k[D]("http://www.w3.org/2000/svg","g"),Lc(this.va,this.S),this.va[m](this.S),this.S=this.va;a=a.U();if(a.id=="")a.id=Ad.xa().Ja();this.va[x]("clip-path","url(#"+a.id+")")};
L.Td=function(){if(this.va!=h){Q(this.va==this.S);var a=this.va.firstChild;Lc(a,this.S);this.S=a;this.va=h}};L.ga=function(){if(this.ta==h){this.ta=k[D]("http://www.w3.org/2000/svg","filter");this.ta.id=Ad.xa().Ja();k.getElementById("defmain")[m](this.ta);if(this.kb==h&&(this.kb=k[D]("http://www.w3.org/2000/svg","g"),Lc(this.kb,this.Ta),this.kb[m](this.Ta),this.S==this.Ta))this.S=this.kb;this.kb[x]("filter","url(#"+this.ta.id+")")}return this.ta};
L.Md=function(a){var b="SourceGraphic";if(this.gb())this.ec=[],Jc(this.ta),this.rc[I](b);for(var c=0;c<a[B];++c){var d=new he[a[c][z]](this,a[c]);d&&(this.ec[n](d),d[I](b),b=d[db]())}this.rc.sf(b);this.ee()};L.ee=function(){if(this.gb()){for(var a=h,b=0;b<this.ec[B];++b){var c=this.ec[b].region;a==h?a=c:c!=h&&a.add(c)}if(a!=h){var b=this.S.getBBox(),c=this.ga(),d=a.z-a.v,e=a.A-a.w;c[x]("x",a.v/b[xa]-0.1);c[x]("y",a.w/b[K]-0.1);c[x]("width",1.2+d/b[xa]);c[x]("height",1.2+e/b[K])}}};L.gb=function(){return!!this.ta};
L.cd=function(){var a=h,b=this;do b.gb()&&(a=b),b=b.La;while(b);if(a){for(b=this;b.La;)b=b.La;b.ld(a.S)}};L.Zb=function(a){a=String(a);a!=this.Eb&&this.La&&this.La.rd(this,a);this.Eb=a};L.getName=function(){return this.Eb};L.gc=function(a){this.La=a};L.getParent=function(){return this.La};L.ua=function(){this.gb()&&this.aa&&this.cd();this.aa=!1};L.Y=function(){this.aa&&this.ee();var a=this.aa;this.aa=!1;return a};L.cg=function(a){this.Ca=a;this.S[x]("display",this.Ca?"inline":"none")};L.Sa=function(){return!1};
L.Ud=function(){return!1};L.Db=function(){var a=this.S.getBBox(),b=[];b[0]=new U(a.x,a.y);b[1]=new U(a.x,a.y+a[K]);b[2]=new U(a.x+a[xa],a.y);b[3]=new U(a.x+a[xa],a.y+a[K]);for(var a=new Gd,c=0;c<b[B];++c)a[Aa](b[c]);return a};var X=function(){};P(X,Hd);j[t](X[C],"_x",{get:function(){return this.__swiffy_d.D().e/20},set:function(a){var b=this.__swiffy_d.D();this.__swiffy_d[La](b.translate(a*20-b.e,0));this.__swiffy_dm=!0}});
j[t](X[C],"_y",{get:function(){return this.__swiffy_d.D().f/20},set:function(a){var b=this.__swiffy_d.D();this.__swiffy_d[La](b.translate(0,a*20-b.f));this.__swiffy_dm=!0}});j[t](X[C],"_xscale",{get:function(){var a=this.__swiffy_d.D();return 100*l[Sa](a.a*a.a+a.b*a.b)},set:function(a){var b=this.__swiffy_d,c=b.D();b[La](c.Gc(a/(100*l[Sa](c.a*c.a+c.b*c.b)),1));this.__swiffy_dm=!0}});
j[t](X[C],"_yscale",{get:function(){var a=this.__swiffy_d.D();return 100*l[Sa](a.c*a.c+a.d*a.d)},set:function(a){var b=this.__swiffy_d,c=b.D();b[La](c.Gc(1,a/(100*l[Sa](c.c*c.c+c.d*c.d))));this.__swiffy_dm=!0}});j[t](X[C],"_alpha",{get:function(){return this.__swiffy_d.Ha().jb/2.56},set:function(a){var b=this.__swiffy_d.Ha();b.jb=a*2.56;this.__swiffy_d.ma(b);this.__swiffy_dm=!0}});
j[t](X[C],"_visible",{get:function(){return this.__swiffy_d.Ca},set:function(a){this.__swiffy_d.cg(a);this.__swiffy_dm=!0}});j[t](X[C],"_rotation",{get:function(){var a=this.__swiffy_d.D();return-180*l.atan2(a.c,a.a)/l.PI},set:function(a){var b=this.__swiffy_d,c=b.D(),a=a*l.PI/-180;a-=l.atan2(c.c,c.a);b[La](c.Jf(a));this.__swiffy_dm=!0}});j[t](X[C],"_name",{get:function(){return this.__swiffy_d[Na]()},set:function(a){this.__swiffy_d.Zb(a);this.__swiffy_dm=!0}});
j[t](X[C],"__quality",{get:function(){return 0},set:function(){}});j[t](X[C],"__highquality",{get:function(){return 0},set:function(){}});j[t](X[C],"__soundbuftime",{get:function(){return 0},set:function(){}});j[t](X[C],"_parent",{get:function(){var a=this.__swiffy_d.La;return a?a.I():a},set:function(){}});j[t](X[C],"_xmouse",{get:function(){var a=this.__swiffy_d;return ie(a.ya(),a.i.ac).x},set:function(){}});j[t](X[C],"_ymouse",{get:function(){var a=this.__swiffy_d;return ie(a.ya(),a.i.ac).y},set:function(){}});
j[t](X[C],"_url",{get:function(){return k.location.href},set:function(){}});j[t](X[C],"_width",{get:function(){var a=this.__swiffy_d,b=a.Db();b.W(a.D());return(b.z-b.v)/20},set:function(a){a/=this._width;this.__swiffy_d[La](this.__swiffy_d.D().Gc(a,1));this.__swiffy_dm=!0}});j[t](X[C],"_height",{get:function(){var a=this.__swiffy_d,b=a.Db();b.W(a.D());return(b.A-b.w)/20},set:function(a){a/=this._height;this.__swiffy_d[La](this.__swiffy_d.D().Gc(1,a));this.__swiffy_dm=!0}});var je=function(a,b){W[H](this);this.g=a;this.k=b;this.Ra=[]};P(je,W);L=je[C];
L.Pa=function(){var a=k[D]("http://www.w3.org/2000/svg","g");this.Rc=this.hc("up");this.Le=this.Rc.U();this.Qc=this.hc("over");this.Ke=this.Qc.U();this.Oc=this.hc("down");this.Je=this.Oc.U();this.Pc=this.hc("hit");this.N=this.Pc.U();this.N[x]("style","pointer-events:all;visibility:hidden;");var b;"createTouch"in k||(b=T(this.N,"mouseover",this.Ve,!1,this),this.Ra[n](b));b=T(this.N,"mouseout",this.Jc,!1,this);this.Ra[n](b);b=T(this.N,"createTouch"in k?"touchend":"mouseup",this.ub,!1,this);this.Ra[n](b);
b=T(this.N,"createTouch"in k?"touchstart":"mousedown",this.tb,!1,this);this.Ra[n](b);if(b=this.g[fb])for(var c=Ub(this.Ue,this),d=0;d<b[B];d++){var e=b[d];e.convertedActions=ke(e[fb]);var g=O(c,e);e[u]&&g(k,"keydown",!0,function(a,b){return a[u]==b[u]});e.keyAscii&&g(k,"keypress",!0,function(a,b){return a[Oa]==b.keyAscii})}a[m](this.N);this.Gd(1);return a};L.Kd=function(a){this.k.p().nd(new le(a.convertedActions,this.k))};
L.Ye=function(a){var b=this.g[fb];if(b){for(var c=0;c<b[B];c++){var d=b[c];d[jb](a[Na]())&&this.Kd(d)}this.k.p().Wc(!1)}};L.oa=function(a){var b=this.g.sounds;b&&b[jb](a[Na]())&&this.k.ab().Ld(b[a[Na]()]);this.Ye(a);this.Gd(a.F)};L.Gd=function(a){this.F=a;this.kf();this.aa=!0;this.k.sc()};L.Ve=function(){this.k.i.He(this.N);this.k[Db]()==!1&&this.F==1?this.oa(me):this.g[ub]&&this.k.cb()==!1&&this.F==1?this.oa(ne):this.k.yb(this.N)&&this.F==2&&this.oa(oe)};
L.Jc=function(){this.k.i.Ie(this.N);this.k[Db]()==!1&&this.F==2?this.oa(pe):this.g[ub]&&this.k.cb()==!1&&this.F==3?this.oa(qe):this.k.yb(this.N)&&this.F==3&&this.oa(re)};L.tb=function(a){this.g[ub]?this.k[Da](this.N):this.k[Da](this.N,!0,Ub(this.$e,this));a[hb]();this.oa(se)};L.ub=function(a){var b=this.g[ub]&&this.k.cb()==!1||this.k.yb(this.N);this.k[Za](this.N);a[hb]();b?this.oa(te):this.oa(me)};L.$e=function(){this.oa(ue)};
L.Ue=function(a,b,c,d,e){this.Ra[n](T(b,c,function(b){e(b,a)&&(this.Kd(a),this.k.p().Wc(),b[hb]())},d,this))};L.kf=function(){var a=this.N,b=function(b,d){b?a[yb]&&a[yb].insertBefore(d,a):Kc(d)};b(this.F==1,this.Le);b(this.F==3,this.Je);b(this.F==2,this.Ke)};L.hc=function(a){var b=new ce(!1);b.Q();var c=this.g.records;if(c)for(var d=0;d<c[B];d++){var e=c[d];if(e[a]){var g=this.k.Kc(e.id);g.gc(this);g.Q();g instanceof fe&&g[Ea]();b.bb(g,e[y]);e[Eb]&&g[La](Td(e[Eb]));e[sb]&&g.ma(ve(e[sb]))}}return b};
L.ua=function(a){if(this.gb())this.Y(a)&&this.cd();else{var b=this.aa;this.aa=!1;this.F==1&&this.Rc.ua(b||a);this.F==2&&this.Qc.ua(b||a);this.F==3&&this.Oc.ua(b||a);this.Pc.ua(b||a)}};L.Y=function(a){function b(b,d){if(b&&d.Y(c||a))e=!0}var c=je.K.Y[H](this,a),d=this.Pc.Y(c||a),e=!1;b(this.F==1,this.Rc);b(this.F==2,this.Qc);b(this.F==3,this.Oc);return c||d||e};L.R=function(){for(var a=0;a<this.Ra[B];a++)md(this.Ra[a]);je.K.R[H](this)};L.Sa=function(){return!0};
var we=function(a,b){this.Eb=a;this.F=b};we[C].getName=function(){return this.Eb};var ne=new we("IdleToOverDown",3),me=new we("IdleToOverUp",2),ue=new we("OutDownToIdle",1),oe=new we("OutDownToOverDown",3),qe=new we("OverDownToIdle",1),re=new we("OverDownToOutDown",2),te=new we("OverDownToOverUp",2),pe=new we("OverUpToIdle",1),se=new we("OverUpToOverDown",3);var xe=function(a,b){W[H](this);this.g=a;this.k=b};P(xe,W);
xe[C].Pa=function(){var a=this.g.bounds,b=k[D]("http://www.w3.org/2000/svg","g"),c=k[D]("http://www.w3.org/2000/svg","foreignObject"),d=k[Ra]("body");c[m](d);var e=k[Ra]("div");this.$c=e;e[G]["font-family"]="font"+this.g[ra];e[G]["font-size"]=this.g[K]+"px";this.g.bold&&(e[G]["font-weight"]="bold");this.g.italic&&(e[G]["font-style"]="italic");if(this.g[s]){var g=Xd(this.g[s]);e[G].color=g[A]();e[G].opacity=g.a}e[G]["text-align"]=ye(this.g.align);this.g.wrap?this.g.html||(e[G]["white-space"]="pre-wrap"):
e[G]["white-space"]="nowrap";e[G]["word-wrap"]="break-word";this.g.selectable&&(e[G]["pointer-events"]="all");e[G]["text-indent"]=this.g[sa]+"px";if(this.g[sa]+this.g.leftMargin<0){var i=-(this.g[sa]+this.g.leftMargin),q=-this.g[sa],g=a[tb]+30-i;c[x]("width",a[wb]-a[tb]-60+i);e[G]["margin-left"]=q+"px"}else g=a[tb]+30,c[x]("width",a[wb]-a[tb]-60),e[G]["margin-left"]=this.g.leftMargin+"px";e[G]["margin-right"]=this.g.rightMargin+"px";this.Nc="translate("+g+" 0)";c[x]("x",0);this.g.border&&(i=k[D]("http://www.w3.org/2000/svg",
"rect"),i[x]("x",a[tb]-g),i[x]("y",a[qa]),i[x]("width",a[wb]-a[tb]),i[x]("height",a[va]-a[qa]),i[x]("fill","white"),i[x]("stroke","black"),i[x]("stroke-width","10"),b[m](i));g=this.g[K]*1.15;this.g[ra]!=f&&(i=k.getElementById("def"+this.g[ra]))&&(g=this.g[K]*i.getAttribute("line-height"));i=g;this.g.leading&&(g+=this.g.leading);e[G]["line-height"]=g+"px";e[G]["padding-top"]=this.g[K]+(i-g)*0.5+"px";c[x]("y",a[qa]+40-this.g[K]);c[x]("height",a[va]-a[qa]-80+this.g[K]);d[m](e);b[m](c);this.g.variable&&
this.k.p().Xe(this.g.variable,this,this.k);this.g.text&&!N(this.bc)&&this.Sc(this.g.text);return b};xe[C].Sc=function(a){this.bc=a;this.Vf()};xe[C].Vf=function(){Jc(this.$c);if(N(this.bc)){var a=String(this.bc);if(this.g.html)ze(this.$c,a,this.g.multiline);else for(var b=this.$c,a=a[F](/\r\n|\r|\n/g),c=0;c<a[B];c++)if(a[c]==""){var d=k[Ra]("br");b[m](d)}else{var d=k.createTextNode(a[c]),e=k[Ra]("p");e[G].margin=0;e[m](d);b[m](e)}}};
var ze=function(a,b,c){var d=a,e=[],g=function(a,b){var c=k[Ra](a);d[m](c);d=c;e[n](b)},a=b[o](/&nbsp;/g," ");Ae(a,{Uf:function(a,b){switch(a){case "p":g("p",a);d[G].margin=0;var e=b[Ga]("align");e&&(d[G]["text-align"]=e[Fb]);c||(d[G].display="inline");break;case "b":case "i":case "u":g(a,a);break;case "a":g(a,a);(e=b[Ga]("href"))&&d[x]("href",e[Fb]);(e=b[Ga]("target"))&&d[x]("target",e[Fb]);d[G]["pointer-events"]="all";d[G].color="inherit";break;case "br":e=k[Ra]("br");d[m](e);break;case "font":g("span",
a);if(e=b[Ga]("color"))d[G].color=e[Fb];(e=b[Ga]("size"))&&(d[G]["font-size"]=e[Fb]*20+"px");(e=b[Ga]("face"))&&(d[G]["font-family"]=e[Fb])}},Sf:function(a){e[e[B]-1]==a&&(e.pop(),d=d[yb])},Rf:function(a){d[m](k.createTextNode(a))}})},ye=function(a){switch(a){case 0:return"left";case 2:return"center";case 1:return"right";case 3:return"justify";default:return"left"}},Ae=function(a,b){var c=k[Ra]("div");c.innerHTML=a;for(var d=0;d<c[Wa][B];d++)Be(c[Wa][d],b)},Be=function(a,b){switch(a.nodeType){case Node.ELEMENT_NODE:var c=
a.nodeName[Hb]();b.Uf(c,a.attributes);for(var d=0;d<a[Wa][B];d++)Be(a[Wa][d],b);b.Sf(c);break;case Node.TEXT_NODE:b.Rf(a.textContent)}};xe[C].Sa=function(){return this.g.variable!=f};var Ce=function(a,b){W[H](this);this.g=a;this.k=b;this.hb=[];this.cc=[]};P(Ce,W);Ce[C].Pa=function(){var a=this.g.fillstyles;if(a)for(var b=0;b<a[B];b++){if(a[b]!=f)var c=Vd(a[b],this.k,this.g.bounds,this);c!=h&&(this.hb[b]=c,this.k.Fa[m](c))}if(a=this.g.linestyles)for(b=0;b<a[B];b++){if(a[b]!=f&&a[b][$a]!=f)var d=Vd(a[b][$a],this.k,this.g.bounds,this);d!=h&&(this.cc[b]=d,this.k.Fa[m](d))}return this.bf()};Ce[C].R=function(){Ce.K.R[H](this);for(var a=0;a<this.hb[B];a++)Kc(this.hb[a]);for(a=0;a<this.cc[B];a++)Kc(this.cc[a])};
Ce[C].bf=function(){var a=this.g,b;b=this.la==0?k[D]("http://www.w3.org/2000/svg","g"):k[D]("http://www.w3.org/2000/svg","clipPath");for(var c=0;c<a.paths[B];c++){var d=a.paths[c],e=k[D]("http://www.w3.org/2000/svg","path");this.ba(e,"d",d[p],De);e.onclick=function(){};b[m](e);if(d.line!=h&&a.linestyles!=h){var g=a.linestyles[d.line];ae(e,g,this,g[$a]?this.cc[d.line]:h)}if(d[$a]!=h)if(g=a.fillstyles[d[$a]],g[ya]==h)Zd(e,g,this,this.hb[d[$a]]);else{var i=k[D]("http://www.w3.org/2000/svg","clipPath");
i.id=Ad.xa().Ja();i[m](e);this.k.Fa[m](i);e=k[D]("http://www.w3.org/2000/svg","g");e[x]("clip-path","url(#"+i.id+")");b[m](e);i=k[D]("http://www.w3.org/2000/svg","use");if(g[z]==5||g[z]==7)Q(this.hb[d[$a]].id!=h),i[Ia]("http://www.w3.org/1999/xlink","href","#"+this.hb[d[$a]].id);else i[Ia]("http://www.w3.org/1999/xlink","href","#def"+g[ya]);g[Eb]&&i[x]("transform",Td(g[Eb])[A]());e[m](i)}else e[x]("fill","none")}return b[Wa][B]==1&&this.la==0?b[Wa][0]:b};
Ce[C].ba=function(a,b,c,d){Q(c[B]==1);c=c[0];if(c instanceof Ee||c instanceof V)c=c[A]();a[x](b,d?d(c):c)};var Fe=function(a,b){this.Cf=a;this.Bf=b};Fe[C].sb=function(){return 0};var Ge=function(a,b,c,d){Fe[H](this,a,b);this.t=c;this.Z=d};P(Ge,Fe);Ge[C].sb=function(a){return this.t+(this.Z-this.t)*a};var He=function(a,b,c,d){Fe[H](this,a,b);this.t=c;this.Z=d};P(He,Fe);He[C].sb=function(a){return(new V(this.t.a+(this.Z.a-this.t.a)*a,this.t.b+(this.Z.b-this.t.b)*a,this.t.c+(this.Z.c-this.t.c)*a,this.t.d+(this.Z.d-this.t.d)*a,this.t.e+(this.Z.e-this.t.e)*a,this.t.f+(this.Z.f-this.t.f)*a))[A]()};
var Ie=function(a,b,c,d){Fe[H](this,a,b);this.t=c;this.Z=d};P(Ie,Fe);Ie[C].sb=function(a){return(new Ee(l.round(this.t.Va+(this.Z.Va-this.t.Va)*a),l.round(this.t.Ua+(this.Z.Ua-this.t.Ua)*a),l.round(this.t.b+(this.Z.b-this.t.b)*a),this.t.a+(this.Z.a-this.t.a)*a))[A]()};var Je=function(a,b,c,d){Fe[H](this,a,b);this.Be=c[F](" ");this.Ce=d[F](" ");Q(this.Be[B]==this.Ce[B])};P(Je,Fe);
Je[C].sb=function(a){for(var b="",c=this.Be,d=this.Ce,e=0;e<c[B];e++){var g=ea(c[e],10);isNaN(g)?(Q(c[e]==d[e]),b+=c[e]+" "):b+=g+(ea(d[e],10)-g)*a+" "}return b};var Ke=function(a,b){Ce[H](this,a,b);this.Vb=[]};P(Ke,Ce);L=Ke[C];L.Pa=function(){return Ke.K.Pa[H](this)};L.ba=function(a,b,c,d){if(c[B]==1)a[x](b,d?d(c[0]):c[0]);else Q(c[B]==2),this.Yf(a,b,d?d(c[0]):c[0],d?d(c[1]):c[1])};
L.Yf=function(a,b,c,d){var e;c instanceof V?e=He:typeof c=="number"?e=Ge:c instanceof Ee?e=Ie:(Q(b=="d"),e=Je);c=new e(a,b,c,d);a[x](b,c.sb(this.Cb/65535));this.Vb[n](c)};L.Ef=function(){for(var a=this.Cb/65535,b=0;b<this.Vb[B];b++){var c=this.Vb[b].Cf,d=this.Vb[b].Bf,e=this.Vb[b].sb(a);c[x](d,e)}};L.ic=function(a){Ke.K.ic[H](this,a);this.Ef()};var Le=function(a){W[H](this);this.g=a};P(Le,W);
Le[C].Pa=function(){var a;a=this.la==0?k[D]("http://www.w3.org/2000/svg","g"):k[D]("http://www.w3.org/2000/svg","clipPath");this.Nc=Td(this.g[Ca])[A]();for(var b=0;b<this.g.records[B];b++){var c=this.g.records[b],d=k[D]("http://www.w3.org/2000/svg","text");d[m](k.createTextNode(c.text));d[x]("font-family","font"+c[ra]);d[x]("font-size",c[K]);c.bold&&d[x]("font-weight","bold");c.italic&&d[x]("font-style","italic");d[x]("x",Me(c.x));d[x]("y",c.y);d[x]("fill-rule","nonzero");d[x]("style","white-space:pre");
c[s]&&(c=Xd(c[s]),d[x]("fill",c[A]()),d[x]("fill-opacity",c.a));a[m](d)}a.id=Ad.xa().Ja();return a};var Ne=function(a,b){W[H](this);this.g=a;this.k=b};P(Ne,W);
Ne[C].Pa=function(){this.sa=k[D]("http://www.w3.org/1999/xhtml","video");this.sa[x]("width",this.g[xa]);this.sa[x]("height",this.g[K]);this.sa[x]("src",this.g.videoUri);this.sa[x]("autoplay",!0);this.sa[x]("preload",!0);var a=0,b=0,c=this.k.Vc(),d=this.k.ea(),e=d.offsetWidth,d=d.offsetHeight;e/d>c?a=(e-d*c)/2:b=(d-e/c)/2;this.sa[x]("style","-webkit-transform-origin:top left;position:absolute;left:"+a+"px;top:"+b+"px;");this.k.ea()[m](this.sa);return k[D]("http://www.w3.org/2000/svg","g")};
Ne[C].R=function(){Kc(this.sa);Ne.K.R[H](this)};Ne[C].vf=function(){var a=this.ya();a!=h?this.sa[G]["-webkit-transform"]="matrix("+a.a+","+a.b+","+a.c+","+a.d+","+a.e/20+","+a.f/20+")":this.sa[G].removeProperty("-webkit-transform")};Ne[C].Y=function(a){var b=Ne.K.Y[H](this,a);(b||a)&&this.vf();return b};var Oe=function(){};Oe[C].If=function(a){this.Dg=a};Oe[C].Ff=function(a){return this.Za(a)};var Pe=function(){W[H](this);this.o=new ce(!1)};P(Pe,W);L=Pe[C];L.Lc=function(a,b){a[ta]()!=h&&a[ta]()[lb](a);a.gc(this);this.o.bb(a,b)};L.removeChild=function(a){this.o.tf(a);a.gc(h)};L.Zc=function(a){(a=this.o.ad(a))&&a.gc(h)};L.ua=function(a){if(this.gb())this.Y(a)&&this.cd();else{var b=this.aa;this.aa=!1;this.o.ua(b||a)}};L.Y=function(a){var b=Pe.K.Y[H](this,a),a=this.o.Y(b||a);return b||a};L.rd=function(a,b){this.o.rd(a,b)};
L.I=function(){var a=this.m;if(!a)a=new Qe,a.__swiffy_d=this,a.__swiffy_dm=!1,this.o.Jd(a),this.m=a;return a};L.wd=function(a,b){this.o.wd(a,b)};var Qe=function(){};P(Qe,X);var Re=function(a){a instanceof X||(a=f);this.m=a;this.ge=0};Re[C].getRGB=function(){return this.ge};Re[C].setRGB=function(a){if(this.m)this.ge=a,this.m.__swiffy_d.ma(new Fd(0,(a&16711680)>>16,0,(a&65280)>>8,0,a&255,256)),this.m.__swiffy_dm=!0};
Re[C].setTransform=function(a){if(this.m&&a){var b=this.m.__swiffy_d;this.m.__swiffy_d.ma(new Fd(a[b.i.p().h(a,"ra")]*256/100,a[b.i.p().h(a,"rb")],a[b.i.p().h(a,"ga")]*256/100,a[b.i.p().h(a,"gb")],a[b.i.p().h(a,"ba")]*256/100,a[b.i.p().h(a,"bb")],a[b.i.p().h(a,"aa")]*256/100));this.m.__swiffy_dm=!0}};Re[C].getTransform=function(){if(!this.m)return h;var a=this.m.__swiffy_d.Ha(a),b={};b.lg=a.qc*100/256;b.mg=a.pc;b.jg=a.oc*100/256;b.kg=a.nc;b.hg=a.mc*100/256;b.ig=a.lc;b.fg=a.jb*100/256;b.gg=0;return b};var fe=function(a,b,c){Pe[H](this);this.g=a;this.i=b;this.wb={};this.Yb={};this.G=-1;this.fb=a.frameCount;this.$b=!1;this.fa=0;this.C=c;this.Ic={};this.$a=b.$a;this.eb={};this.Qa=[];this.Hd=!1;this.Ge=[]};P(fe,Pe);var Se={wg:1,vg:2,Ag:4,yg:8,zg:16,Bg:32,ug:64,xg:128};L=fe[C];
L.Pa=function(){this.i.Ee(this);this.Fa=k[D]("http://www.w3.org/2000/svg","defs");for(var a=0;a<this.g.tags[B];a++){var b=this.g.tags[a];switch(b[z]){case 10:var c=new Te(b);this.C.Ga(b.id,c);break;case 13:c=new Ue(b);this.C.Ga(b.id,c);break;case 5:c=new Ve(b);this.Fa[m](c.Q());break;case 8:c=new We(b);this.Fa[m](c.Q());break;case 1:c=new Xe(b);this.C.Ga(b.id,c);break;case 17:c=new Ye(b);this.C.Ga(b.id,c);break;case 11:c=new Ze(b);c.Mc(this.ab());break;case 7:c=new $e(b,this.i,this.C);this.C.Ga(b.id,
c);break;case 6:c=new af(b);this.C.Ga(b.id,c);break;case 14:c=new bf(b);this.C.Ga(b.id,c);break;case 9:c=new cf(b);this.vb(this.fa,c);break;case 20:this.Yb[this.fa]||(this.Yb[this.fa]=[]);this.Yb[this.fa][n](b);break;case 18:this.i.dg.eg(h);break;case 19:var b=b.references,d;for(d in b)c=Number(d),this.C.De(c,b[c]);break;case 15:this.Ic[b.label]=this.fa;break;case 3:c=new df(b);this.vb(this.fa,c);break;case 4:c=new ef(b);this.vb(this.fa,c);break;case 2:this.fa++;break;case 12:c=new ff(b);this.vb(this.fa,
c);break;case 16:c=new gf(b),this.vb(this.fa,c)}}this.la==0?(this.o.Q(),a=k[D]("http://www.w3.org/2000/svg","g"),this.Cd=this.o.U(),a[m](this.Fa),a[m](this.Cd)):(this.o.Fe(!0),this.o.Q(),a=this.o.U());d=O(this.Ia,1);d=T(k,"keyup",d,!1,this);this.Qa[n](d);d=O(this.Ia,2);d=T(k,"keydown",d,!1,this);this.Qa[n](d);d=O(this.Ia,4);d=T(this.i.ea(),"createTouch"in k?"touchend":"mouseup",d,!1,this);this.Qa[n](d);d=O(this.Ia,8);d=T(this.i.ea(),"createTouch"in k?"touchstart":"mousedown",d,!1,this);this.Qa[n](d);
d=O(this.Ia,16);d=T(this.i.ea(),"createTouch"in k?"touchmove":"mousemove",d,!1,this);this.Qa[n](d);this.Dd();this.Ia(128);this.Xb||this.Ed();return a};L.load=function(){if(!this.Hd)this.Hd=!0,this[Ta](),this.ce(!1),this.Xb&&this.Ed()};L.Ze=function(a,b){for(var c in Se){var d=Se[c];a&d&&(this.eb[d]||(this.eb[d]=[]),this.eb[d][n](new le(b,this)))}};L.Ia=function(a){if(a=this.eb[a])for(var b=0;b<a[B];++b)this.p().nd(a[b])};L.Ud=function(){return this.eb!=f&&this.eb[32]!=f};
L.Kc=function(a){return(a=this.C.Gf(a))?a.Ff(this):h};L.R=function(){this.i.df(this);Kc(this.Fa);Kc(this.Cd);this.o.R();for(var a=0;a<this.Qa[B];a++)md(this.Qa[a]);fe.K.R[H](this)};L.Ka=function(){this.Od||(this.o.Ka(),this.Ia(32));fe.K.Ka[H](this)};L.vb=function(a,b){this.wb[a]||(this.wb[a]=[]);this.wb[a][n](b)};L.play=function(){this.$b=!0};L.Mf=function(){this.o.qf();this.$b?this.ce(!0):this.gd()};L.ce=function(a){var b=this.G+1;b>=this.fb&&(b=0);(this.fb!=0||this.i.V!=this)&&this.vc(b,a)};
L.gd=function(){this.Ia(64);this.p().be(Ub(function(){this.I().onEnterFrame()},this))};L.Ed=function(){this.p().be(Ub(function(){this.I().onLoad()},this))};L.stop=function(){this.$b=!1};L.Mb=function(a,b){a>=0&&a<this.fb?this.vc(a):this.G=this.fb+1;this.$b=b};L.Jb=function(a){var b=f;typeof a=="string"&&this.Ic[a]!=f?b=this.Ic[a]:(a=Number(a)-1,a>=0&&a==l[Fa](a)&&(b=a));return b};L.nf=function(a){return this.wb[a]};
L.vc=function(a,b){var c=!1,d=this.o;if(a<this.G)c=!0,this.o=new ce(!0),this.o.Q(),this.G=-1;for(a==this.G&&b&&this.gd();this.G<a;){this.G++;this.G==a&&b&&this.gd();this.gf(this.G);var e=this.wb[this.G];if(e)for(var g=0;g<e[B];g++)e[g].Ib(this),this.G==a&&e[g].Hb(this)}e=this.Ge[this.G];Nb(e)&&e();if(c)d.hf(this.o),this.o=d};L.gf=function(a){for(a=this.Yb[a];a&&a[B]>0;){var b=a[ua](),b=ke(b[fb]);this.p().sd(new le(b,this))}};L.re=function(){this.G>0&&this.vc(this.G-1);this[ab]()};
L.qe=function(){this.G+1<this.fb&&this.vc(this.G+1);this[ab]()};L.p=function(){return this.i.p()};L.ab=function(){return this.i.ab()};L.ea=function(){return this.i.ea()};L.Vc=function(){return this.i.Vc()};L.Hf=function(a,b){this.I()[a]=b};L.isCaptured=function(){return this.i[Db]()};L.cb=function(){return this.i.cb()};L.yb=function(a){return this.i.yb(a)};L.setCapture=function(a,b,c){this.i[Da](a,b,c)};L.releaseCapture=function(a){this.i[Za](a)};
L.duplicate=function(a,b,c){var d=new fe(this.g,this.i,this.C);d.Xb=!0;d.Q();d[Ea]();d.Zb(b);d[La](this.D());a.Lc(d,c);d.ma(this.Ha());return d};L.ld=function(a){this.i.ld(a)};L.sc=function(){this.i.sc()};L.I=function(){this.m||this.Dd();return this.m};L.Dd=function(){var a=Y;if(this.g.id){var b=Id[this.i.Bd[this.g.id]];b!=h&&(a=b)}this.m=j.create(a[C]);this.m.__swiffy_d=this;this.m.__swiffy_dm=!1;this.o.Jd(this.m);a[I](this.m)};L.Sa=function(){return!0};var Y=function(){};P(Y,Qe);
Y[C].gotoAndStop=function(a){var b=this.__swiffy_d;b.Mb(b.Jb(a),!1)};Y[C].gotoAndPlay=function(a){var b=this.__swiffy_d;b.Mb(b.Jb(a),!0)};Y[C].play=function(){this.__swiffy_d[Ta]()};Y[C].stop=function(){this.__swiffy_d[ab]()};Y[C].nextFrame=function(){this.__swiffy_d.qe()};Y[C].prevFrame=function(){this.__swiffy_d.re()};Y[C].onEnterFrame=function(){};Y[C].onLoad=function(){};
Y[C].globalToLocal=function(a){var b=this.__swiffy_d,c=b.i.p(),d=c.Rd(a);if(d!=h){var e=c.h(a,"x"),c=c.h(a,"y"),b=b.ya(),d=ie(b,d);a[e]=d.x;a[c]=d.y}};Y[C].localToGlobal=function(a){var b=this.__swiffy_d,c=b.i.p(),d=c.Rd(a);if(d!=h){var e=c.h(a,"x"),c=c.h(a,"y"),b=b.ya(),d=new U(d.x*20,d.y*20);d.W(b);d.x/=20;d.y/=20;a[e]=d.x;a[c]=d.y}};
Y[C].attachMovie=function(a,b,c,d){var e=this.__swiffy_d,a=e.i.Fd[a];if(N(a)&&(a=e.Kc(a),a.Xb=!0,a.Zb(b),a.Q(),a[Ea](),e.Lc(a,c),N(d))){var b=a.I(),g;for(g in d)b[g]=d[g]}};Y[C].duplicateMovieClip=function(a,b,c){var d=this.__swiffy_d,e=d[ta]();if(e&&(a=d.duplicate(e,a,b),N(c))){var a=a.I(),g;for(g in c)a[g]=c[g]}};Y[C].removeMovieClip=function(){var a=this.__swiffy_d,b=a[ta]();a.Xb&&b&&(a.R(),b[lb](a))};
Y[C].swapDepths=function(a){var b=this.__swiffy_d,c=b[ta]();if(!c){if(a instanceof X){a=a.__swiffy_d;if(a[ta]()!=c)return;a=a[y]}else a=Number(a);c.wd(b[y],a)}};Y[C].getBytesLoaded=function(){return this.getBytesTotal()};Y[C].getBytesTotal=function(){return 1E3};
Y[C].getBounds=function(a){var b=this.__swiffy_d,c=b.Db();if(N(a)){var d=h;a instanceof Y?d=a.__swiffy_d:Mb(a)&&(d=b.i.p().xb(b,a));if(d!=h)a=d.ya().Yc(),c.W(a.multiply(b.ya()));else return}b={};b.v=c.v/20;b.z=c.z/20;b.w=c.w/20;b.A=c.A/20;return b};Y[C].hitTest=function(a,b,c){if(N(a)){var d=this.__swiffy_d,e=d.Db();e.W(d.ya());if(!N(b)&&!N(c)){if(b=h,a instanceof Y?b=a.__swiffy_d:Mb(a)&&(b=d.i.p().xb(d,a)),b!=h)return a=b.Db(),a.W(b.ya()),e.ef(a)}else if(N(b))return e.contains(a*20,b*20)}return!1};
j[t](Y[C],"_currentframe",{get:function(){return this.__swiffy_d.G+1},set:function(){}});j[t](Y[C],"_totalframes",{get:function(){return this.__swiffy_d.fb},set:function(){}});j[t](Y[C],"_framesloaded",{get:function(){return this.__swiffy_d.fa},set:function(){}});j[t](Y[C],"_root",{get:function(){return this.__swiffy_d.i.V.I()},set:function(){}});j[t](Y[C],"_target",{get:function(){var a=this._root;if(this==a)return"/";else{for(var b="",c=this;c&&c!=a;)b="/"+c._name+b,c=c._parent;return b}},set:function(){}});
j[t](Y[C],"_level0",{get:function(){return this.__swiffy_d.i.V.I()},set:function(){}});var hf=function(){this.Ae=[];this.Hc=[]};hf[C].Mc=function(a,b){this.Ae[a]=b};hf[C].Ld=function(a){this.Hc[a]=new Audio(this.Ae[a]);this.Hc[a][Ta]()};hf[C].Df=function(){for(var a in this.Hc)this.Hc[a].pause()};var lf=function(a,b){this.ac=new U(0,0);this.ha=k[D]("http://www.w3.org/1999/xhtml","div");this.ha[x]("style","position:relative;");a[m](this.ha);this.Re=new hf;this.qa=k[D]("http://www.w3.org/2000/svg","svg");var c="fill-rule:evenodd;";c+="pointer-events:none;";c+="width:"+b[ob][wb]/20+";";c+="height:"+b[ob][va]/20+";";b.backgroundColor!=f&&(c+="background:"+Xd(b.backgroundColor)[A]());this.qa[x]("style",c);this.qa[x]("viewBox",b[ob][tb]+" "+b[ob][qa]+" "+b[ob][wb]+" "+b[ob][va]);this.ha[m](this.qa);
this.Me=b[ob][wb]/b[ob][va];c=new be;c.Ga(0,new $e(b,this,c));this.$a=b.version;this.V=new fe(b,this,c);this.Bb=new jf(this.V);this.ib=new kf;this.ib.Qe(this.Bb);this.ib.Pe(b.frameRate);this.V.Q();this.qa[m](this.V.U());this.V.Fa.id="defmain";this.za=h;this.Uc=!1;this.fc=h;this.Fd={};this.Bd={};this.Ab=new Qd(this);this.Aa={};this.Aa.s=0;T(this.ha,"mousedown",this.tb,!1,this);T(this.ha,"mouseup",this.ub,!1,this);T(this.ha,"mouseout",this.Jc,!1,this);"createTouch"in k||T(this.ha,"mousemove",this.Tc,
!1,this);T(k,"mousedown",this.Ne,!1,this);T(k,"mouseup",this.Oe,!1,this);T(this.ha,"touchstart",this.Te,!1,this);T(this.ha,"touchmove",this.Se,!1,this)},mf="swiffy.Stage"[F]("."),nf=M;!(mf[0]in nf)&&nf.execScript&&nf.execScript("var "+mf[0]);for(var of;mf[B]&&(of=mf[ua]());)!mf[B]&&N(lf)?nf[of]=lf:nf=nf[of]?nf[of]:nf[of]={};L=lf[C];L.tb=function(a){a[hb]();this[Da](this.qa)};L.ub=function(a){a[hb]();this[Za](this.qa)};L.Ne=function(){this[Da](this.qa,!0)};L.Oe=function(){this[Za](this.qa)};
L.Jc=function(a){this[Db]()&&a[mb]==this.ha&&this[Da](this.qa)};L.Tc=function(a){this.xd(a)};L.Te=function(a){var b=a.Ea.touches;b[B]==1&&(this.xd(b[0]),a[Ha]())};L.Se=function(a){var b=a.Ea.touches;b[B]==1&&(this.xd(b[0]),a[Ha]())};L.xd=function(a){var b;b=this.qa;var c=0,d=0;if(b.offsetParent){do c+=b.offsetLeft,d+=b.offsetTop;while(b=b.offsetParent)}b=[c,d];this.ac.x=a.clientX-b[0];this.ac.y=a.clientY-b[1]};L.pf=function(){return this.Aa.s>0};
L.He=function(a){a=Rb(a);a in this.Aa||(this.Aa[a]=!0,this.Aa.s++);this.Ab[zb]()};L.Ie=function(a){a=Rb(a);a in this.Aa&&(delete this.Aa[a],this.Aa.s--);this.Ab[zb]()};L.isCaptured=function(){return this.za!=h};L.cb=function(){return this.za!=h&&this.Uc};L.yb=function(a){return this.za==a};L.of=function(){return this.za?Rb(this.za)in this.Aa:!1};L.setCapture=function(a,b,c){this[Za](a);this.za=a;k.uf=function(){return!1};if(b)this.Uc=!0;if(c)this.fc=c,this.Ab[zb]()};
L.releaseCapture=function(a){if(this.za)this.Ab[zb](),k.uf=h,this.za!=a&&this.fc&&this.fc(),this.za=this.fc=h,this.Uc=!1};L.start=function(){this.V[Ta]();this.ib.start()};lf[C].start=lf[C].start;L=lf[C];L.Ee=function(a){this.ib.yd(a)};L.df=function(a){this.ib.Tf(a)};L.p=function(){return this.Bb};L.ab=function(){return this.Re};L.yd=function(a){this.ib.yd(a)};L.sc=function(){this.Tb=[];this.V.ua(!1);for(var a=0;a<this.Tb[B];a++)this.Tb[a][x]("transform",this.Tb[a].getAttribute("transform"))};
L.ld=function(a){this.Tb[r](a)==-1&&this.Tb[n](a)};L.ea=function(){return this.ha};L.Vc=function(){return this.Me};L.bg=function(a){for(var a=new Ed(a),b=a.Nb(),c=0;c<b[B];c++){var d=b[c];this.V.Hf(d,a.get(d))}};lf[C].setFlashVars=lf[C].bg;var Ee=function(a,b,c,d){this.Va=a;this.Ua=b;this.b=c;this.a=d};ka(Ee[C],function(){return"rgb("+this.Va+","+this.Ua+","+this.b+")"});
var Xd=function(a){var b=a&255;a>>=8;var c=a&255;a>>=8;var d=a&255;a>>=8;return new Ee(b,c,d,1-(a&255)/255)},Yd=function(a){return Xd(a).a},Td=function(a){var b=0,c=pf(function(){return a[rb](b++)});return new V(c()/1E3+1,c()/1E3,c()/1E3,c()/1E3+1,c(),c())},Me=function(a){for(var b=0,c=qf(function(){return a[rb](b++)}),d=[],e=0;b<a[B];)e+=ea(c(),10),d[n](e);return d[Bb](" ")},qf=function(a){return function(){var b=a();if(b==58)return 0;for(var c="";b>=48&&b<=57;)c+=String.fromCharCode(b),b=a();return(b>=
97?b-96:-(b-64))+c}},pf=function(a){var b=qf(a);return function(){return ea(b(),10)}},De=function(a){for(var b=0,c=a[r](":"),d=c+1,e=qf(function(){return a[rb](d++)}),g="",i;b<c;)switch(i=a.charAt(b++),g[B]>0&&(g+=" "),g+=i+" ",i){case "q":g+=e()+" "+e()+" ";case "l":case "m":g+=e()+" ";case "h":case "v":g+=e();break;default:return""}return g},ve=function(a){var b=0,c=pf(function(){return a[rb](b++)});return new Fd(c()+256,c(),c()+256,c(),c()+256,c(),c()+256)},rf=function(a){return a<=0.04045?a/12.92:
l.pow((a+0.055)/1.055,2.4)},sf=function(a){return a<=0.0031308?a*12.92:l.pow(a,1/2.4)*1.055-0.055},ie=function(a,b){var c=new U(b.x*20,b.y*20);c.W(a.Yc());c.x/=20;c.y/=20;return c};var tf=function(a){this.T=a;this.rf=Ad.xa().Ja();this.region=new Gd(0,0,0,0)},he=[];L=tf[C];pa(L,function(){});L.result=function(){return this.rf};L.ne=function(a,b,c,d,e){var g=1;switch(a){case 1:g=5;break;case 2:g=3;break;case 3:g=2}a=b*20/g;c=c*20/g;g=k[D]("http://www.w3.org/2000/svg","feGaussianBlur");N(d)&&g[x]("in",d);N(e)&&g[x]("result",e);g[x]("stdDeviation",a+" "+c);this.T.ga()[m](g);d=new Gd;d[Aa](new U(-a*3,-c*3));d[Aa](new U(+a*3,+c*3));return d};
L.Da=function(a,b,c,d,e,g,i){var q=k[D]("http://www.w3.org/2000/svg","feComponentTransfer");N(g)&&q[x]("in",g);N(i)&&q[x]("result",i);N(e)||(e="linear");g=["feFuncR","feFuncG","feFuncB","feFuncA"];a=[a,b,c,d];for(b=0;b<4;++b){var c=h,w;for(w in a[b])c==h&&(c=k[D]("http://www.w3.org/2000/svg",g[b]),c[x]("type",e)),c[x](w,a[b][w]);c&&q[m](c)}this.T.ga()[m](q)};
L.ka=function(a,b,c,d,e){var g=k[D]("http://www.w3.org/2000/svg","feComposite");N(e)&&g[x]("result",e);N(b)&&g[x]("in",b);N(c)&&g[x]("in2",c);g[x]("operator",a);if(N(d))for(var i in d)g[x](i,d[i]);this.T.ga()[m](g)};L.jf=function(a){var b=k[D]("http://www.w3.org/2000/svg","feFlood");N(a)&&b[x]("result",a);this.T.ga()[m](b)};
L.Kf=function(a,b,c,d){var e=l.cos(a)*b*20,a=l.sin(a)*b*20,b=k[D]("http://www.w3.org/2000/svg","feOffset");N(c)&&b[x]("in",c);N(d)&&b[x]("result",d);b[x]("dx",e);b[x]("dy",a);this.T.ga()[m](b);return new Gd(e,a,e,a)};L.hd=function(a,b,c,d,e,g){this.Da({slope:0},{slope:0},{slope:0},{},"linear",a);a=this.ne(b,c,d);g!=0&&this.region.Lf(this.Kf(e,g));this.region.add(a)};L.wc=function(){return Ad.xa().Ja()};var uf=function(a,b){tf[H](this,a);this.Qb=b[Ca];this.Qb[4]/=255;this.Qb[9]/=255;this.Qb[14]/=255;this.Qb[19]/=255};P(uf,tf);he[3]=uf;
pa(uf[C],function(a){for(var b=[],c=[],d=0;d<256;d++)b[d]=sf(d/255),c[d]=rf(d/255);var e={tableValues:b[Bb](" ")},c={tableValues:c[Bb](" ")},b=this.wc(),d=this.wc();this.Da(e,e,e,e,"discrete",a,b);a=this.T.ga();e=k[D]("http://www.w3.org/2000/svg","feColorMatrix");e[x]("in",b);e[x]("result",d);e[x]("type","matrix");e[x]("values",this.Qb[Bb](" "));a[m](e);this.Da(c,c,c,c,"discrete",d,this[db]())});var ge=function(a){tf[H](this,a);this.ia=new Fd(256,0,256,0,256,0,256);this.uc="SourceGraphic"};P(ge,tf);L=ge[C];L.ma=function(a){this.T.Ta[x]("opacity",a.jb/256);if(!(this.ng instanceof xe)&&!this.ia.lf(a))return this.ia=a,this.da==h&&this[I](this.uc),this[zb](),!0;else if(this.ia.jb!=a.jb)return this.ia=a,!0;return!1};
L.update=function(){this.da!=h&&(this.fd[x]("tableValues",this.md(this.ia.qc,this.ia.pc)),this.ed[x]("tableValues",this.md(this.ia.oc,this.ia.nc)),this.dd[x]("tableValues",this.md(this.ia.mc,this.ia.lc)))};L.sf=function(a){this.uc=a;this.da!=h&&(this.da[x]("in",this.uc),a=this.T.ga(),a[lb](this.da),a[m](this.da))};
pa(L,function(a){this.uc=a;var b=this.T.ga();this.da=k[D]("http://www.w3.org/2000/svg","feComponentTransfer");this.da[x]("in",a);this.da[x]("result",this[db]());this.fd=k[D]("http://www.w3.org/2000/svg","feFuncR");this.fd[x]("type","discrete");this.da[m](this.fd);this.ed=k[D]("http://www.w3.org/2000/svg","feFuncG");this.ed[x]("type","discrete");this.da[m](this.ed);this.dd=k[D]("http://www.w3.org/2000/svg","feFuncB");this.dd[x]("type","discrete");this.da[m](this.dd);b[m](this.da);this[zb]()});
L.md=function(a,b){a/=256;b/=256;for(var c=[],d=0;d<256;d++)c[d]=rf(sf(d/255)*a+b);return c[Bb](" ")};L.Ha=function(){return this.ia};var vf=function(a,b){tf[H](this,a);this.Gb=b};P(vf,tf);he[2]=vf;pa(vf[C],function(a){var b=this.Gb;this.region=this.ne(b[Gb],b.x,b.y,a,this[db]())});var wf=function(a,b){tf[H](this,a);this.Gb=b};P(wf,tf);he[1]=wf;
pa(wf[C],function(a){var b=this.Gb,c=this.T.ga();b[eb]&&this.jf("black");this.hd(a,b[Gb],b.x,b.y,b.angle,b.distance);b[eb]&&this.ka("arithmetic",f,"black",{k2:-1,k3:1});var d=Xd(b[s]);this.Da({intercept:rf(d.Va/255)},{intercept:rf(d.Ua/255)},{intercept:rf(d.b/255)},{slope:b.strength});d.a<1&&this.Da({},{},{},{slope:d.a});c[nb][x]("result","shadow");!b[eb]&&!b[Ma]&&!b.hideObject?this.ka("over",a,"shadow"):b[eb]&&!b[Ma]&&!b.hideObject?this.ka("atop","shadow",a):!b[eb]&&b[Ma]?this.ka("out","shadow",
a):b[eb]&&this.ka("in","shadow",a);c[nb][x]("result",this[db]())});var xf=function(a,b){tf[H](this,a);this.Gb=b};P(xf,tf);he[4]=xf;
pa(xf[C],function(a){var b=this.Gb,c=this.T.ga(),d=this.wc(),e=this.wc();this.hd(a,b[Gb],b.x,b.y,b.angle,-b.distance);var g=Xd(b.highlight);this.Da({intercept:rf(g.Va/255)},{intercept:rf(g.Ua/255)},{intercept:rf(g.b/255)},{slope:b.strength});g.a<1&&this.Da({},{},{},{slope:g.a});c[nb][x]("result",e);this.hd(a,b[Gb],b.x,b.y,b.angle,b.distance);g=Xd(b.shadow);this.Da({intercept:rf(g.Va/255)},{intercept:rf(g.Ua/255)},{intercept:rf(g.b/255)},{slope:b.strength});g.a<1&&this.Da({},{},{},{slope:g.a});c[nb][x]("result",
d);this.ka("xor",d,e,{},"shadow");b[Ma]?b[eb]?this.ka("in","shadow",a):b.onTop||this.ka("out","shadow",a):b[eb]?this.ka("atop","shadow",a):b.onTop?this.ka("over","shadow",a):this.ka("over",a,"shadow");c[nb][x]("result",this[db]())});var Te=function(a){this.g=a};P(Te,Oe);Te[C].Za=function(a){return new je(this.g,a)};var Ue=function(a){this.g=a};P(Ue,Oe);Ue[C].Za=function(a){return new xe(this.g,a)};var Ve=function(a){this.g=a};
Ve[C].Q=function(){var a;a=this.g.emSquareSize?this.g.emSquareSize:1024;var b,c,d;if(this.g.ascent&&this.g.descent)b=this.g.ascent,c=this.g.descent,d=(b+c)/a;else{if(this.g[Ya]&&!this.g[ib]){var e=k[D]("http://www.w3.org/1999/xhtml","div");e[G].fontFamily=this.g[Ya];e[G].fontSize="1024px";e.innerHTML="A";k[kb][m](e);d=e.clientHeight/1024;Kc(e)}else d=1.15;b=a*0.9;c=a*(d-0.9)}e=k[D]("http://www.w3.org/2000/svg","font-face");e[x]("id","def"+this.g.id);e[x]("line-height",d);e[x]("units-per-em",a);e[x]("ascent",
b);e[x]("descent",c);d="font"+this.g.id;this.g[Ya]&&(d+=',"'+this.g[Ya]+'"');e[x]("font-family",d);e[x]("font-weight",this.g.bold?"bold":"normal");e[x]("font-style",this.g.italic?"italic":"normal");if(this.g[Ya]&&!this.g[ib])return a=k[D]("http://www.w3.org/2000/svg","font-face-src"),d=k[D]("http://www.w3.org/2000/svg","font-face-name"),d[x]("name",this.g[Ya]),a[m](d),e[m](a),e;else{d=k[D]("http://www.w3.org/2000/svg","font");d[x]("horiz-adv-x",a);d[m](e);if(this.g[ib])for(e=0;e<this.g[ib][B];e++)a=
this.g[ib][e],b=k[D]("http://www.w3.org/2000/svg","glyph"),b[x]("d",De(a[p])),b[x]("unicode",a.unicode),a.advance&&b[x]("horiz-adv-x",a.advance),d[m](b);return d}};var We=function(a){this.g=a};
We[C].Q=function(){var a=k[D]("http://www.w3.org/2000/svg","image");a.id="def"+this.g.id;a[x]("width",this.g[xa]);a[x]("height",this.g[K]);if(this.g.mask){var b=this.g[xa],c=this.g[K],d=k[Ra]("canvas");d.width=this.g[xa];d.height=this.g[K];var e=new Image,g=new Image,i=!1,q=!1,w=function(){if(i&&q){var v=d.getContext("2d");v.clearRect(0,0,b,c);v.drawImage(e,0,0,b,c);v.globalCompositeOperation="xor";v.drawImage(g,0,0,b,c);a[Ia]("http://www.w3.org/1999/xlink","href",d.toDataURL("image/png"))}};e.onload=
function(){i=!0;w()};g.onload=function(){q=!0;w()};e.src=this.g[p];g.src=this.g.mask}else a[Ia]("http://www.w3.org/1999/xlink","href",this.g[p]);return a};var Ye=function(a){this.g=a};P(Ye,Oe);Ye[C].Za=function(a){return new Ke(this.g,a)};var Xe=function(a){this.g=a};P(Xe,Oe);Xe[C].Za=function(a){return new Ce(this.g,a)};var Ze=function(a){this.g=a};Ze[C].Mc=function(a){a.Mc(this.g.id,this.g[p])};var $e=function(a,b,c){this.g=a;this.O=b;this.C=c};P($e,Oe);$e[C].Za=function(){return new fe(this.g,this.O,this.C)};var af=function(a){this.g=a};P(af,Oe);af[C].Za=function(){return new Le(this.g)};var bf=function(a){this.g=a};P(bf,Oe);bf[C].Za=function(a){return new Ne(this.g,a)};var cf=function(a){this.tg=a;this.he=ke(a[fb])};cf[C].Ib=function(){};cf[C].Hb=function(a){a.p().nd(new le(this.he,a))};cf[C].Ob=function(a){a.p().sd(new le(this.he,a))};var ff=function(a){this.Pf=a};ff[C].Ib=function(a){a.ab().Ld(this.Pf.id)};ff[C].Hb=function(){};ff[C].Ob=function(){};var df=function(a){this.l=a};
df[C].Ib=function(a){var b=a.o.Xc(this.l[y]);if(!b||!b.zb())if(b||!this.l[o])if(!b||this.l[o]||!this.l.id)if(b&&(b.Sa()||!this.l.id))this.Nd(b);else{var c=b,b=a.Kc(this.l.id);if(b!=h)if(b.Sa()&&c)this.Nd(c);else{this.l[Ya]&&b.Zb(this.l[Ya]);var d=h;this.l[Ca]&&(d=Td(this.l[Ca]));var e=h;this.l[sb]&&(e=ve(this.l[sb]));this.l[o]&&(d||(d=c.D()),e||(e=c.Ha()));this.l.clip&&b.af(this.l.clip);if(this.l[fb])for(var g=0;g<this.l[fb][B];++g){var i=ke(this.l[fb][g].action);b.Ze(this.l[fb][g].events,i)}c&&a.Zc(this.l[y]);
b.Q();a.Lc(b,this.l[y]);this.l[Ka]!=f&&b.ic(this.l[Ka]);d&&b[La](d);this.l[vb]&&b.Md(this.l[vb]);e&&b.ma(e);b instanceof fe&&!c&&!a.o.We&&b[Ea]()}}};df[C].Nd=function(a){this.l[Ca]&&a[La](Td(this.l[Ca]));this.l[sb]&&a.ma(ve(this.l[sb]));this.l[Ka]!=f&&a.ic(this.l[Ka]);var b=[];this.l[vb]&&(b=this.l[vb]);a.Md(b)};df[C].Hb=function(){};df[C].Ob=function(){};var ef=function(a){this.yc=a};ef[C].Ib=function(a){var b=a.o.Xc(this.yc[y]);if(!b||!b.zb())b&&b.Ka(),a.Zc(this.yc[y])};
ef[C].Hb=function(a){var b=a.o.Xc(this.yc[y]);b&&b.zb()&&(b.Ka(),a.Zc(this.yc[y]))};ef[C].Ob=function(){};var gf=function(a){this.mf=a};gf[C].Ib=function(a){var b=this.mf,c;for(c in b[p])a.i.Fd[c]=b[p][c],a.i.Bd[b[p][c]]=c};gf[C].Hb=function(){};gf[C].Ob=function(){};var kf=function(){this.Fc=[];this.te=1;this.ue=!1};L=kf[C];L.Pe=function(a){this.te=a};L.yd=function(a){this.Fc[n](a)};L.Tf=function(a){ec(this.Fc,a)};L.Qe=function(a){this.Bb=a};L.ze=function(){for(var a=this.Fc[B]-1;a>=0;--a)this.Fc[a].Mf();this.Bb&&this.Bb.Wc()};L.start=function(){if(!this.ue)this.ue=!0,this.ze(),aa.setInterval(Ub(this.ze,this),1E3/this.te)};var le=function(a,b){this.pe=a;this.T=b};var Z=function(a){this.O=a};Z[C].clearInterval=function(a){aa.clearInterval(a)};Z[C].escape=function(a){return escape(a)[o](/[-@*+./_]/g,function(a){return"%"+a[rb](0)[A](16).toUpperCase()})};Z[C].parseFloat=function(a){return parseFloat(a)};Z[C].parseInt=function(a,b){return ea(a,b)};Z[C].isFinite=function(a){return isFinite(a)};Z[C].isNaN=function(a){return isNaN(a)};Z[C].unescape=function(a){return unescape(a)};
Z[C].setInterval=function(a){if(Nb(a)&&arguments[B]>=2)return aa.setInterval[I](h,arguments);else if(Ob(a)&&arguments[B]>=3&&Nb(a[arguments[1]])){var b=Ub(a[arguments[1]],a),c=arguments[2],d=ca[C][Ba][H](arguments,3);return aa.setInterval[I](h,[b,c].concat(d))}};Z[C].Math=l;Z[C].MovieClip=Y;Z[C].String=String;Z[C].Number=Number;Z[C].Date=Jd;Z[C].Array=Kd;Z[C].Object=Hd;Z[C].Color=Re;Z[C].Key=Ld;j[t](Z[C],"Mouse",{get:function(){return this.O.Ab},set:function(){}});var yf=function(a,b){this.u=a;ga(this,{});this.L=b};L=yf[C];L.get=function(a){var b=this.u.h(this[p],a);return b in this[p]?this[p][b]:this.L.get(a)};na(L,function(a,b){var c=this.u.h(this[p],a);return c in this[p]?this[p][c][I](this.pa(),b):this.L[H](a,b)});L.set=function(a,b){var c=this.u.h(this[p],a);return c in this[p]?(this[p][c]=b,!0):this.L.set(a,b)};L.Ba=function(a,b){this[p][this.u.h(this[p],a)]=b};L.Fb=function(a){a=this.u.h(this[p],a);a in this[p]||(this[p][a]=f)};L.mb=function(){};
ka(L,function(){return"function->"+this.L[A]()});L.ca=function(a){return this.L.ca(a)};L.pa=function(){return this.L.pa()};var zf=function(a,b,c){this.u=a;ga(this,c);this.L=b};L=zf[C];L.get=function(a){var b=this.u.h(this[p],a);return b in this[p]?this[p][b]:this.L.get(a)};na(L,function(a,b){var c=this.u.h(this[p],a);if(c in this[p]){if(c=this[p][c],Nb(c))return c[I](this[p],b)}else return this.L[H](a,b)});
L.set=function(a,b){var c=this.u.h(this[p],a);return c in this[p]?(this[p][c]=b,this[p]instanceof X&&(this[p].__swiffy_dm=!0),!0):this.L.set(a,b)};L.Ba=function(a,b){var c=this.u.h(this[p],a);c in this[p]?(this[p][c]=b,this[p]instanceof X&&(this[p].__swiffy_dm=!0)):this.L.Ba(a,b)};L.Fb=function(a){this.u.h(this[p],a)in this[p]||this.L.Fb(a)};L.mb=function(a){var b=this.u.h(this[p],a);b in this[p]?delete this[p][b]:this.L.mb(a)};ka(L,function(){var a=this[p]._name;a+="->"+this.L[A]();return a});
L.ca=function(a){return this.L.ca(a)};L.pa=function(){return this.L.pa()};var Af=function(a,b,c){this.u=a;ga(this,c);this.jd=b;this.Yd=c};L=Af[C];L.get=function(a){var b=this.u.h(this[p],a);return b in this[p]?this[p][b]:a[Hb]()=="this"?this.Yd:this.jd.get(a)};na(L,function(a,b){var c=this.u.h(this[p],a),d=this[p][c];if(c in this[p]){if(Nb(d))return d[I](this[p],b)}else return this.jd[H](a,b)});L.set=function(a,b){this[p][this.u.h(this[p],a)]=b;return this[p].__swiffy_dm=!0};
L.Ba=function(a,b){this[p][this.u.h(this[p],a)]=b;this[p].__swiffy_dm=!0};L.Fb=function(a){a=this.u.h(this[p],a);if(!(a in this[p]))this[p][a]=f,this[p].__swiffy_dm=!0};L.mb=function(a){var b=this.u.h(this[p],a);b in this[p]?delete this[p][b]:this.jd.mb(a)};ka(L,function(){var a=this[p]._name;!a&&this[p]instanceof Y&&!this[p]._parent&&(a="_root");return a});L.ca=function(a){return ga(this,a?a:this.Yd)};L.pa=function(){return this[p]};
var Bf=function(a,b){this.u=a;ga(this,new Z(b));this[p]._global=this[p]};L=Bf[C];L.get=function(a){return this[p][this.u.h(this[p],a)]};na(L,function(a,b){var c=this[p][this.u.h(this[p],a)];if(Nb(c))return c[I](this[p],b)});L.set=function(){return!1};L.Ba=function(){};L.Fb=function(){};L.mb=function(a){delete this[p][this.u.h(this[p],a)]};ka(L,function(){return"_global"});L.ca=function(){};L.pa=function(){return h};var jf=function(a){this.B=[];this.na=this.J=h;this.Qd=[];this.ra=[];this.V=a;this.cf=this.Pd();this.jc=[];this.dc=!1;this.X=0;this.Id=new Bf(this,a.i)};L=jf[C];L.nd=function(a){this.jc[n](Ub(function(){this.sd(a)},this))};L.be=function(a){this.jc[n](a)};L.Wc=function(a){if(!this.dc){for(this.dc=!0;this.jc[B]>0;)this.jc[ua]()();this.dc=!1}a!==!1&&this.V.sc()};L.Pd=function(){return(new Date).getTime()};
L.reset=function(a){this.J=this.na=a;this.B=[];this.X=0;this.B.length+=4;this.n=new Af(this,this.Id,a.I())};L.sd=function(a){if(!a.T.Sd){this.reset(a.T);for(var b=0;b<a.pe[B];)b=a.pe[b](this,b+1)}};var Cf=function(a){a=a[o](/\.\.|\/:?|:/g,function(a){return a==".."?"_parent":"."});a[0]=="."&&(a="_root"+a);a[a[B]-1]=="."&&(a=a.substring(0,a[B]-1));return a};jf[C].bd=function(a,b){if(!N(b))b=this.J;var c=a[F](":");return c[B]>1?{path:this.xb(b,c[0]),kc:c[1]}:{path:b,kc:a}};
jf[C].Wf=function(a){for(var b=0;b<this.Qd[B];b++)this.Qd[b](a)};var Df=new Boolean(!1),Ef=new Number(0),Ff=new String("");L=jf[C];
L.h=function(a,b){if(this.na.$a>=7){if(a instanceof X){if(b in a)return b;var c=b[Hb]();if(c in a&&Gf[r](c)>-1)return c}}else{switch(typeof a){case "object":case "function":break;case "boolean":a=Df;break;case "number":a=Ef;break;case "string":a=Ff;break;default:return b}if(b in a)return b;c=b[Hb]();if(c in a)return c;do for(var d=j.getOwnPropertyNames(a),e=0;e<d[B];e++)if(d[e][Hb]()==c)return d[e];while(a=a.__proto__)}return b};
L.Rd=function(a){if(Ob(a)){var b=a[this.h(a,"x")],a=a[this.h(a,"y")];if(typeof b=="number"&&typeof a=="number")return new U(b,a)}return h};L.ca=function(a){(this.J=a)?this.n.ca(a.I()):this.n.ca(h)};L.pa=function(){return this.J};L.push=function(a){this.B[n](a)};L.pop=function(){return this.B.pop()};L.Ec=function(a){var b=this.na.$a;typeof a=="boolean"&&b<5&&(a=a?"1":"0");return!N(a)&&b<7?"":String(a)};
L.Ub=function(a){var b=this.na.$a;return!N(a)||a===h?b<7?0:Number.NaN:Mb(a)?(a=Number(a),b<5&&isNaN(a)?0:a):Number(a)};L.j=function(){return this.Ub(this.B.pop())};L.r=function(){return this.Ec(this.B.pop())};L.Wb=function(){var a=this.B.pop();typeof a=="string"&&(a=Number(a));return Boolean(a)};L.xc=function(){var a=this.pop();if(a instanceof X)return a;(a=this.xb(this.J,String(a)))&&(a=a.I());return a};
L.xb=function(a,b){if(!a||!b)return a;for(var b=Cf(b),c=a.I(),d=b[F]("."),e=0;e<d[B]&&c;e++)c=c[this.h(c,d[e])];return c?c.__swiffy_d:h};L.Xe=function(a,b,c){this.dc||this.reset(c);c=this.bd(a,c);if(c[Va]){a=c[Va].I();c=this.h(a,c.kc);if(c in a&&(b.Sc(a[c]),j.getOwnPropertyDescriptor(a,c).get))return;j[t](a,c,{get:function(){return b.bc},set:function(a){b.Sc(a)},configurable:!0})}};L.xf=function(a,b){b[r]("_level")!=0&&a[Hb]()[r]("fscommand:")!=0&&a!="undefined"&&(b==""&&(b="_self"),aa.open(a,b))};
var ke=function(a){for(var b=[],c=0;c<a[B];++c){var d=b,e=c,g;g=a[c];var i=$[g[z]];g=!i?O(Hf,g[z]):i.$?i(g):i;d[e]=g}return b},Gf="_x,_y,_xscale,_yscale,_currentframe,_totalframes,_alpha,_visible,_width,_height,_rotation,_target,_framesloaded,_name,_droptarget,_url,_highquality,_focusrect,_soundbuftime,_quality,_xmouse,_ymouse".split(","),$={4:function(a,b){var c=a.J;c!=h&&c.qe();return b},5:function(a,b){var c=a.J;c!=h&&c.re();return b},6:function(a,b){var c=a.J;c!=h&&c[Ta]();return b},7:function(a,
b){var c=a.J;c!=h&&c[ab]();return b},9:function(a,b){var c=a.J;c!=h&&c.ab().Df();return b},10:function(a,b){var c=a.j(),d=a.j();a[n](d+c);return b},11:function(a,b){var c=a.j(),d=a.j();a[n](d-c);return b},12:function(a,b){var c=a.j(),d=a.j();a[n](d*c);return b},13:function(a,b){var c=a.j(),d=a.j();a[n](d/c);return b},14:function(a,b){var c=a.j(),c=a.j()==c;a.na.$a<5&&(c=c?1:0);a[n](c);return b},15:function(a,b){var c=a.j(),d=a.j();a[n](d<c);return b},16:function(a,b){var c=a.Wb(),d=a.Wb();a[n](d&&
c);return b},17:function(a,b){var c=a.Wb(),d=a.Wb();a[n](d||c);return b},18:function(a,b){var c=a.Wb();a[n](!c);return b},19:function(a,b){var c=a.r(),d=a.r();a[n](d==c);return b},20:function(a,b){var c=a.r();a[n](c[B]);return b},21:function(a,b){var c=Number(a.pop()),d=l.max(0,Number(a.pop())-1),e=a.r();a[n](e.substr(d,c));return b},23:function(a,b){a.pop();return b},24:function(a,b){var c=a.j(),c=c<0?l.ceil(c):l[Fa](c);a[n](c);return b},28:function(a,b){var c=a.r(),c=Cf(c),c=c[F]("."),d=a.n.get(c[0]);
if(c[B]>1){var e;for(e=1;N(d)&&e<c[B]-1;++e)d=d[a.h(d,c[e])];N(d)&&(d=d[a.h(d,c[e])])}a[n](d);return b},29:function(a,b){var c=a.pop(),d=a.r(),d=Cf(d),e=d[F](".");if(e[B]==1)a.n.set(d,c);else{var d=a.n.get(e[0]),g;for(g=1;N(d)&&g<e[B]-1;++g)d=d[a.h(d,e[g])];N(d)&&(d[a.h(d,e[g])]=c)}return b},33:function(a,b){var c=a.r(),d=a.r();a[n](d+c);return b},34:function(a,b){var c=Gf[a.j()],d=a.xc();d?a[n](d[c]):a[n](f);return b},35:function(a,b){var c=a.pop(),d=Gf[a.j()],e=a.xc();e&&d&&(e[d]=c);return b},36:function(a,
b){var c=a.j(),d=a.r(),e=a.xc();e&&e.__swiffy_d.duplicate(a.J,d,c);return b},37:function(a,b){var c=a.xc();c instanceof Y&&c.removeMovieClip();return b},38:function(a,b){var c=a.pop();a.Wf(N(c)?a.Ec(c):"undefined");return b}},Hf=function(a,b,c){return c};$[51]=function(a,b){var c=a.j();a[n](String.fromCharCode(c));return b};$[50]=function(a,b){var c=a.r();a[n](c[rb](0));return b};$[52]=function(a,b){a[n](a.Pd()-a.cf);return b};
$[48]=function(a,b){var c=a.j(),d;do d=l[Fa](l.random()*c);while(d==c&&c>0);a[n](d);return b};$[60]=function(a,b){var c=a.pop(),d=a.pop();a.n.Ba(d,c);return b};$[65]=function(a,b){var c=a.pop();a.n.Fb(c);return b};$[59]=function(a,b){var c=a.pop();a.n.mb(c);return b};$[62]=function(a){oa(a,a.pop());return Number.MAX_VALUE};$[63]=function(a,b){var c=a.j(),d=a.j();a[n](d%c);return b};$[71]=function(a,b){var c=a.pop(),d=a.pop();Mb(c)||Mb(d)?a[n](a.Ec(d)+a.Ec(c)):a[n](a.Ub(d)+a.Ub(c));return b};
$[72]=function(a,b){var c=a.pop(),d=a.pop();if(!Mb(c)||!Mb(d))c=a.Ub(c),d=a.Ub(d);c!==c||d!==d?a[n](f):a[n](d<c);return b};$[103]=function(a,b){var c=a.pop(),d=a.pop();a[n](d>c);return b};$[73]=function(a,b){var c=a.pop(),d=a.pop();a[n](d==c);return b};$[102]=function(a,b){var c=a.pop(),d=a.pop();a[n](d===c);return b};$[41]=function(a,b){var c=a.r(),d=a.r();a[n](d<c);return b};$[104]=function(a,b){var c=a.r(),d=a.r();a[n](d>c);return b};$[74]=function(a,b){var c=a.j();a[n](c);return b};
$[75]=function(a,b){var c=a.r();a[n](c);return b};$[76]=function(a,b){var c=a.pop();a[n](c);a[n](c);return b};$[77]=function(a,b){var c=a.pop(),d=a.pop();a[n](c);a[n](d);return b};$[78]=function(a,b){var c=a.r(),d=a.pop(),e;d&&(e=d[a.h(d,c)]);a[n](e);return b};$[79]=function(a,b){var c=a.pop(),d=a.r(),e=a.pop();e&&(e[a.h(e,d)]=c);return b};$[80]=function(a,b){var c=a.j();a[n](++c);return b};$[81]=function(a,b){var c=a.j();a[n](--c);return b};$[96]=function(a,b){var c=a.j(),d=a.j();a[n](c&d);return b};
$[97]=function(a,b){var c=a.j(),d=a.j();a[n](c|d);return b};$[98]=function(a,b){var c=a.j(),d=a.j();a[n](d^c);return b};$[99]=function(a,b){var c=a.j(),d=a.j();a[n](d<<c);return b};$[100]=function(a,b){var c=a.j(),d=a.j();a[n](d>>c);return b};$[101]=function(a,b){var c=a.j(),d=a.j();a[n](d>>>c);return b};$[58]=function(a,b){var c=a.r(),d=a.pop();d&&delete d[a.h(d,c)];return b};$[129]=function(a){return O(If,a.frame)};$[129].$=!0;var If=function(a,b,c){b=b.J;b!=h&&b.Mb(a,!1);return c};
$[140]=function(a){return O(Jf,a.label)};$[140].$=!0;var Jf=function(a,b,c){b=b.J;b!=h&&(a=b.Jb(a),a!=f&&b.Mb(a,!1));return c};$[136]=function(a){return O(Kf,a.constants)};$[136].$=!0;var Kf=function(a,b,c){b.ra=a;return c};$[32]=function(a,b){var c=a.pop();c=c instanceof X?c.__swiffy_d:(c=String(c))?a.xb(a.na,c):a.n.ca(h).__swiffy_d;a.ca(c);return b};$[69]=function(a,b){var c=a.pop(),d;if(c instanceof Y){d="";for(c=c.__swiffy_d;c&&c!=a.V;)d="."+c[Na]()+d,c=c[ta]();c&&(d="_root"+d)}a[n](d);return b};
$[305]=function(a){return O(Lf,a.value)};$[305].$=!0;var Lf=function(a,b,c){b[n](a);return c};$[306]=function(a,b){a[n](f);return b};$[307]=function(a,b){a[n](Number[wa]);return b};$[308]=function(a,b){a[n](Number.NEGATIVE_INFINITY);return b};$[309]=function(a,b){a[n](Number.NaN);return b};$[304]=function(a){return O(Mf,a.index)};$[304].$=!0;var Mf=function(a,b,c){b[n](b.ra[a]);return c};$[303]=function(a){return O(Nf,a.index)};$[303].$=!0;var Nf=function(a,b,c){b[n](b.B[b.X+a]);return c};
$[135]=function(a){return O(Of,a.index)};$[135].$=!0;var Of=function(a,b,c){b.B[b.X+a]=b.B[b.B[B]-1];return c};$[154]=function(a,b){var c=a.r(),d=a.r();a.xf(d,c);return b};$[148]=function(a){return O(Pf,ke(a[kb]))};$[148].$=!0;
var Pf=function(a,b,c){var d=b.pop();if(!(d instanceof Hd))return c;var e=b.n;b.n=new zf(b,e,d);for(d=0;d<a[B];)d=a[d](b,d+1);b.n=e;return c},Qf=function(a,b,c,d){var e=d.n,g=d.X,i=d.ra,q=d.J,w=d.na;d.n=new yf(d,new Af(d,d.Id,this));d.ra=c;if(this instanceof X)d.J=this.__swiffy_d;d.X=d.B[B];d.B.length+=4;var v;for(v=0;v<a[B];++v)d.n.Ba(a[v],arguments[4+v]);d.n.Ba("this",this);oa(d,f);for(v=0;v<b[B];)v=b[v](d,v+1);la(d.B,d.X);d.n=e;d.X=g;d.ra=i;d.na=w;d.J=q;return d[qb]};
$[155]=function(a){return O(Rf,a.args,ke(a[kb]))};$[155].$=!0;
var Rf=function(a,b,c,d){a=O(Qf,a,b,c.ra,c);P(a,Hd);c[n](a);return d},Sf=function(a,b,c,d,e,g,i){var q=i.n,w=i.X,v=i.ra,Pa=i.pa(),J=i.na;i.n=new yf(i,g);i.ra=e;i.ca(g.pa().__swiffy_d);i.X=i.B[B];i.B.length+=d;i.n.Ba("this",this);for(var E=0;E<c[B];++E)i.B[i.X+E+1]=i.n.get(c[E]);for(E=0;E<a[B];++E)Mb(a[E])?i.n.Ba(a[E],arguments[7+E]):i.B[i.X+a[E]]=arguments[7+E];oa(i,f);for(E=0;E<b[B];)E=b[E](i,E+1);la(i.B,i.X);i.n=q;i.X=w;i.ra=v;i.na=J;i.ca(Pa);return i[qb]};
$[142]=function(a){return O(Tf,a.args,ke(a[kb]),a.preloads,a.registerCount)};$[142].$=!0;var Tf=function(a,b,c,d,e,g){a=O(Sf,a,b,c,d,e.ra,e.n,e);P(a,Hd);e[n](a);return g};$[61]=function(a,b){for(var c=a.r(),d=a.j(),e=[],g=0;g<d;++g)e[g]=a.pop();a[n](a.n[H](c,e));return b};$[82]=function(a,b){for(var c=a.pop(),d=a.pop(),e=a.j(),g=[],i=0;i<e;i++)g[i]=a.pop();if(d!=h)if(c)(c=d[a.h(d,String(c))])?a[n](c[I](d,g)):a[n](f);else a[n](d[I](a.n.pa(),g));else a[n](f);return b};
$[64]=function(a,b){for(var c=a.r(),c=a.n.get(c),d=a.j(),e=[],g=0;g<d;++g)e[g]=a.pop();Nb(c)||(c=Hd);d=j.create(c[C]);c[I](d,e);a[n](d);return b};$[83]=function(a,b){for(var c=a.pop(),d=a.pop(),e=a.j(),g=[],i=0;i<e;i++)g[i]=a.pop();var q;d!=h&&(q=c?d[a.h(d,String(c))]:d);Nb(q)||(q=Hd);c=j.create(q[C]);q[I](c,g);a[n](c);return b};$[67]=function(a,b){for(var c=new Hd,d=a.j(),e=0;e<d;e++){var g=a.pop(),i=a.r();c[i]=g}a[n](c);return b};
$[66]=function(a,b){for(var c=[],d=a.j(),e=0;e<d;e++){var g=a.pop();c[e]=g}a[n](c);return b};$[68]=function(a,b){var c=a.pop();a[n](c instanceof Y?"movieclip":c==h||c==f?String(c):typeof c);return b};$[85]=function(a,b){var c=a.pop();a[n](h);for(var d in c)a[n](d);return b};$[153]=function(a){return O(Uf,a[mb])};$[153].$=!0;var Uf=function(a){return a};$[157]=function(a){return O(Vf,a[mb])};$[157].$=!0;var Vf=function(a,b,c){return Boolean(b.pop())?a:c};
$[158]=function(a,b){var c=a.r(),c=a.bd(c);if(c[Va]){var d=c[Va].Jb(c.kc);if(d!=f&&(d=c[Va].nf(d)))for(var e=0;e<d[B];e++)d[e].Ob(c[Va])}return b};$[159]=function(a){return O(Wf,a.frameBias,a[Ta])};$[159].$=!0;var Wf=function(a,b,c,d){var e=c.r(),c=c.bd(e);c[Va]&&(e=c[Va].Jb(c.kc),e!=f&&c[Va].Mb(e+a,b));return d};