/*
 * Copyright 2011 Google Inc.
 *
 * Swiffy runtime version 3.5.1
 *
 * In addition to the Google Terms of Service (http://www.google.com/accounts/TOS),
 * Google grants you and the Google Swiffy end users a personal, worldwide,
 * royalty-free, non-assignable and non-exclusive license to use the Google Swiffy
 * runtime to host it for Google Swiffy end users and to use it in connection with
 * the Google Swiffy service.
 */
var f=void 0,h=true,j=null,k=false,aa=window,l=Object,ba=Function,m=document,n=Math,ca=Array,da=Error,ea=parseInt,fa=decodeURIComponent;function ga(a,b){return a.data=b}function ia(a,b){return a.currentTarget=b}function ja(a,b){return a.keyCode=b}function ka(a,b){return a.type=b}function la(a,b){return a.toString=b}function ma(a,b){return a.length=b}function na(a,b){return a.target=b}function oa(a,b){return a.call=b}function pa(a,b){return a.start=b}function qa(a,b){return a.returnValue=b}
function ra(a,b){return a.apply=b}
var o="appendChild",p="push",sa="ymin",ta="indent",ua="getParent",va="shift",wa="ymax",xa="POSITIVE_INFINITY",ya="width",za="bitmap",Aa="text",Ba="expand",Ca="slice",Da="replace",Ea="matrix",Fa="setCapture",r="data",Ga="floor",Ha="getNamedItem",Ia="preventDefault",Ja="setAttributeNS",s="indexOf",Ka="defineProperties",La="color",Ma="capture",Na="ratio",Oa="setTransform",Pa="knockout",Qa="getName",Ra="charCode",Sa="createElement",Ta="defineProperty",t="keyCode",Ua="sqrt",Va="states",v="setAttribute",
Wa="play",Xa="handleEvent",w="path",x="depth",y="type",Ya="childNodes",Za="bind",$a="name",ab="releaseCapture",bb="fill",cb="stop",z="toString",db="gradient",A="length",eb="propertyIsEnumerable",C="prototype",fb="result",gb="inner",hb="actions",ib="variable",D="createElementNS",jb="ctrlKey",E="split",kb="constructor",lb="stopPropagation",mb="glyphs",nb="hasOwnProperty",F="style",ob="body",pb="removeChild",qb="target",rb="lastChild",G="call",sb="frameSize",tb="start",ub="init",vb="returnValue",wb=
"charCodeAt",xb="colortransform",yb="xmin",zb="__proto__",Ab="trackAsMenu",I="apply",Bb="filters",Cb="xmax",Db="navigator",Eb="parentNode",Fb="update",K="height",Gb="splice",Hb="join",Ib="unshift",Jb="isCaptured",Kb="transform",Lb="nodeValue",Mb="quality",Nb="toLowerCase",L,M=this,Ob=function(){},Pb=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof ca)return"array";else if(a instanceof l)return b;var c=l[C][z][G](a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a[A]==
"number"&&typeof a[Gb]!="undefined"&&typeof a[eb]!="undefined"&&!a[eb]("splice"))return"array";if(c=="[object Function]"||typeof a[G]!="undefined"&&typeof a[eb]!="undefined"&&!a[eb]("call"))return"function"}else return"null";else if(b=="function"&&typeof a[G]=="undefined")return"object";return b},N=function(a){return a!==f},Qb=function(a){return Pb(a)=="array"},Rb=function(a){var b=Pb(a);return b=="array"||b=="object"&&typeof a[A]=="number"},Sb=function(a){return typeof a=="string"},O=function(a){return Pb(a)==
"function"},Tb=function(a){a=Pb(a);return a=="object"||a=="array"||a=="function"},Wb=function(a){return a[Ub]||(a[Ub]=++Vb)},Ub="closure_uid_"+n[Ga](n.random()*2147483648)[z](36),Vb=0,Xb=function(a,b,c){return a[G][I](a[Za],arguments)},Yb=function(a,b,c){if(!a)throw da();if(arguments[A]>2){var d=ca[C][Ca][G](arguments,2);return function(){var c=ca[C][Ca][G](arguments);ca[C][Ib][I](c,d);return a[I](b,c)}}else return function(){return a[I](b,arguments)}},P=function(a,b,c){P=ba[C][Za]&&ba[C][Za][z]()[s]("native code")!=
-1?Xb:Yb;return P[I](j,arguments)},Zb=function(a,b){var c=ca[C][Ca][G](arguments,1);return function(){var b=ca[C][Ca][G](arguments);b[Ib][I](b,c);return a[I](this,b)}},R=function(a,b){function c(){}c.prototype=b[C];a.p=b[C];a.prototype=new c;a[C].constructor=a};ba[C].bind=ba[C][Za]||function(a,b){if(arguments[A]>1){var c=ca[C][Ca][G](arguments,1);c[Ib](this,a);return P[I](j,c)}else return P(this,a)};var $b=function(a){this.stack=da().stack||"";if(a)this.message=String(a)};R($b,da);$b[C].name="CustomError";var ac=function(a,b){for(var c=1;c<arguments[A];c++)var d=String(arguments[c])[Da](/\$/g,"$$$$"),a=a[Da](/\%s/,d);return a},bc=/^[a-zA-Z0-9\-_.!~*'()]*$/,cc=function(a){a=String(a);return!bc.test(a)?encodeURIComponent(a):a},ec=function(a,b){for(var c=0,d=String(a)[Da](/^[\s\xa0]+|[\s\xa0]+$/g,"")[E]("."),e=String(b)[Da](/^[\s\xa0]+|[\s\xa0]+$/g,"")[E]("."),g=n.max(d[A],e[A]),i=0;c==0&&i<g;i++){var q=d[i]||"",u=e[i]||"",B=RegExp("(\\d*)(\\D*)","g"),ha=RegExp("(\\d*)(\\D*)","g");do{var J=B.exec(q)||
["","",""],X=ha.exec(u)||["","",""];if(J[0][A]==0&&X[0][A]==0)break;c=dc(J[1][A]==0?0:ea(J[1],10),X[1][A]==0?0:ea(X[1],10))||dc(J[2][A]==0,X[2][A]==0)||dc(J[2],X[2])}while(c==0)}return c},dc=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var fc=function(a,b){b[Ib](a);$b[G](this,ac[I](j,b));b[va]();this.hh=a};R(fc,$b);fc[C].name="AssertionError";var S=function(a,b,c){if(!a){var d=ca[C][Ca][G](arguments,2),e="Assertion failed";if(b){e+=": "+b;var g=d}throw new fc(""+e,g||[]);}return a};var gc=ca[C],hc=gc[s]?function(a,b,c){S(a[A]!=j);return gc[s][G](a,b,c)}:function(a,b,c){c=c==j?0:c<0?n.max(0,a[A]+c):c;if(Sb(a))return!Sb(b)||b[A]!=1?-1:a[s](b,c);for(;c<a[A];c++)if(c in a&&a[c]===b)return c;return-1},ic=gc.forEach?function(a,b,c){S(a[A]!=j);gc.forEach[G](a,b,c)}:function(a,b,c){for(var d=a[A],e=Sb(a)?a[E](""):a,g=0;g<d;g++)g in e&&b[G](c,e[g],g,a)},jc=function(a,b){var c=hc(a,b),d;if(d=c>=0)S(a[A]!=j),gc[Gb][G](a,c,1);return d},kc=function(a,b){for(var c=1;c<arguments[A];c++){var d=
arguments[c],e;if(Qb(d)||(e=Rb(d))&&d[nb]("callee"))a[p][I](a,d);else if(e)for(var g=a[A],i=d[A],q=0;q<i;q++)a[g+q]=d[q];else a[p](d)}},mc=function(a,b,c,d){S(a[A]!=j);return gc[Gb][I](a,lc(arguments,1))},lc=function(a,b,c){S(a[A]!=j);return arguments[A]<=2?gc[Ca][G](a,b):gc[Ca][G](a,b,c)},nc=function(a,b,c,d,e){for(var g=0,i=a[A],q;g<i;){var u=g+i>>1,B;B=c?b[G](e,a[u],u,a):b(d,a[u]);B>0?g=u+1:(i=u,q=!B)}return q?g:~g},oc=function(a,b){return a>b?1:a<b?-1:0},pc=function(a,b,c){c=nc(a,c||oc,k,b);return c<
0?(mc(a,-(c+1),0,b),h):k};var qc=function(a,b,c){for(var d in a)b[G](c,a[d],d,a)},rc="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(","),sc=function(a,b){for(var c,d,e=1;e<arguments[A];e++){d=arguments[e];for(c in d)a[c]=d[c];for(var g=0;g<rc[A];g++)c=rc[g],l[C][nb][G](d,c)&&(a[c]=d[c])}};var tc,uc,vc,wc,xc=function(){return M[Db]?M[Db].userAgent:j};wc=vc=uc=tc=k;var yc;if(yc=xc()){var zc=M[Db];tc=yc[s]("Opera")==0;uc=!tc&&yc[s]("MSIE")!=-1;vc=!tc&&yc[s]("WebKit")!=-1;wc=!tc&&!vc&&zc.product=="Gecko"}var Ac=tc,T=uc,Bc=wc,Cc=vc,Dc=M[Db],Ec=(Dc&&Dc.platform||"")[s]("Mac")!=-1,Fc;
a:{var Gc="",Hc;if(Ac&&M.opera)var Ic=M.opera.version,Gc=typeof Ic=="function"?Ic():Ic;else if(Bc?Hc=/rv\:([^\);]+)(\)|;)/:T?Hc=/MSIE\s+([^\);]+)(\)|;)/:Cc&&(Hc=/WebKit\/(\S+)/),Hc)var Jc=Hc.exec(xc()),Gc=Jc?Jc[1]:"";if(T){var Kc,Lc=M.document;Kc=Lc?Lc.documentMode:f;if(Kc>parseFloat(Gc)){Fc=String(Kc);break a}}Fc=Gc}var Mc=Fc,Nc={},Oc=function(a){return Nc[a]||(Nc[a]=ec(Mc,a)>=0)},Pc={},Qc=function(a){return Pc[a]||(Pc[a]=T&&m.documentMode&&m.documentMode>=a)};!T||Qc(9);!Bc&&!T||T&&Qc(9)||Bc&&Oc("1.9.1");T&&Oc("9");var Rc=function(a){for(var b;b=a.firstChild;)a[pb](b)},Sc=function(a){return a&&a[Eb]?a[Eb][pb](a):j},Tc=function(a,b){var c=b[Eb];c&&c.replaceChild(a,b)};var Uc=function(a){Uc[" "](a);return a};Uc[" "]=Ob;var Vc;!T||Qc(9);var Wc=T&&!Oc("8");var Xc=function(){};Xc[C].Ve=k;Xc[C].jb=function(){if(!this.Ve)this.Ve=h,this.Ba()};Xc[C].Ba=function(){this.yg&&Yc[I](j,this.yg)};var Yc=function(a){for(var b=0,c=arguments[A];b<c;++b){var d=arguments[b];Rb(d)?Yc[I](j,d):d&&typeof d.jb=="function"&&d.jb()}};var Zc=function(a,b){ka(this,a);na(this,b);ia(this,this[qb])};R(Zc,Xc);L=Zc[C];L.Ba=function(){delete this[y];delete this[qb];delete this.currentTarget};L.kb=k;L.hc=h;L.stopPropagation=function(){this.kb=h};L.preventDefault=function(){this.hc=k};var $c=function(a,b){a&&this[ub](a,b)};R($c,Zc);L=$c[C];na(L,j);L.relatedTarget=j;L.offsetX=0;L.offsetY=0;L.clientX=0;L.clientY=0;L.screenX=0;L.screenY=0;L.button=0;ja(L,0);L.charCode=0;L.ctrlKey=k;L.altKey=k;L.shiftKey=k;L.metaKey=k;L.Zf=k;L.ua=j;
L.init=function(a,b){var c=ka(this,a[y]);Zc[G](this,c);na(this,a[qb]||a.srcElement);ia(this,b);var d=a.relatedTarget;if(d){if(Bc){var e;a:{try{Uc(d.nodeName);e=h;break a}catch(g){}e=k}e||(d=j)}}else if(c=="mouseover")d=a.fromElement;else if(c=="mouseout")d=a.toElement;this.relatedTarget=d;this.offsetX=a.offsetX!==f?a.offsetX:a.layerX;this.offsetY=a.offsetY!==f?a.offsetY:a.layerY;this.clientX=a.clientX!==f?a.clientX:a.pageX;this.clientY=a.clientY!==f?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=
a.screenY||0;this.button=a.button;ja(this,a[t]||0);this.charCode=a[Ra]||(c=="keypress"?a[t]:0);this.ctrlKey=a[jb];this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Zf=Ec?a.metaKey:a[jb];this.state=a.state;this.ua=a;delete this.hc;delete this.kb};L.stopPropagation=function(){$c.p[lb][G](this);this.ua[lb]?this.ua[lb]():this.ua.cancelBubble=h};
L.preventDefault=function(){$c.p[Ia][G](this);var a=this.ua;if(a[Ia])a[Ia]();else if(qa(a,k),Wc)try{(a[jb]||a[t]>=112&&a[t]<=123)&&ja(a,-1)}catch(b){}};L.Ba=function(){$c.p.Ba[G](this);this.ua=j;na(this,j);ia(this,j);this.relatedTarget=j};var ad=function(a,b){this.Qe=b;this.lb=[];this.mg(a)};R(ad,Xc);L=ad[C];L.Qd=j;L.We=j;L.mc=function(a){this.Qd=a};L.kc=function(){return this.lb[A]?this.lb.pop():this.Ue()};L.lc=function(a){this.lb[A]<this.Qe?this.lb[p](a):this.Be(a)};L.mg=function(a){if(a>this.Qe)throw da("[goog.structs.SimplePool] Initial cannot be greater than max");for(var b=0;b<a;b++)this.lb[p](this.Ue())};L.Ue=function(){return this.Qd?this.Qd():{}};L.Be=function(a){if(this.We)this.We(a);else if(Tb(a))if(O(a.jb))a.jb();else for(var b in a)delete a[b]};
L.Ba=function(){ad.p.Ba[G](this);for(var a=this.lb;a[A];)this.Be(a.pop());delete this.lb};var bd,cd=(bd="ScriptEngine"in M&&M.ScriptEngine()=="JScript")?M.ScriptEngineMajorVersion()+"."+M.ScriptEngineMinorVersion()+"."+M.ScriptEngineBuildVersion():"0";var dd=function(){},ed=0;L=dd[C];L.key=0;L.Bb=k;L.Oe=k;L.init=function(a,b,c,d,e,g){if(O(a))this.Le=h;else if(a&&a[Xa]&&O(a[Xa]))this.Le=k;else throw da("Invalid listener argument");this.fc=a;this.ze=b;this.src=c;ka(this,d);this.capture=!!e;this.Fd=g;this.Oe=k;this.key=++ed;this.Bb=k};L.handleEvent=function(a){return this.Le?this.fc[G](this.Fd||this.src,a):this.fc[Xa][G](this.fc,a)};var fd,gd,hd,id,jd,kd,ld,md,nd,od,pd;
(function(){function a(){return{v:0,va:0}}function b(){return[]}function c(){var a=function(b){b=i[G](a.src,a.key,b);if(!b)return b};return a}function d(){return new dd}function e(){return new $c}var g=bd&&!(ec(cd,"5.7")>=0),i;kd=function(a){i=a};if(g){fd=function(){return q.kc()};gd=function(a){q.lc(a)};hd=function(){return u.kc()};id=function(a){u.lc(a)};jd=function(){return B.kc()};ld=function(){B.lc(c())};md=function(){return ha.kc()};nd=function(a){ha.lc(a)};od=function(){return J.kc()};pd=function(a){J.lc(a)};
var q=new ad(0,600);q.mc(a);var u=new ad(0,600);u.mc(b);var B=new ad(0,600);B.mc(c);var ha=new ad(0,600);ha.mc(d);var J=new ad(0,600);J.mc(e)}else fd=a,gd=Ob,hd=b,id=Ob,jd=c,ld=Ob,md=d,nd=Ob,od=e,pd=Ob})();var qd={},U={},rd={},sd={},V=function(a,b,c,d,e){if(b)if(Qb(b)){for(var g=0;g<b[A];g++)V(a,b[g],c,d,e);return j}else{var d=!!d,i=U;b in i||(i[b]=fd());i=i[b];d in i||(i[d]=fd(),i.v++);var i=i[d],q=Wb(a),u;i.va++;if(i[q]){u=i[q];for(g=0;g<u[A];g++)if(i=u[g],i.fc==c&&i.Fd==e){if(i.Bb)break;return u[g].key}}else u=i[q]=hd(),i.v++;g=jd();g.src=a;i=md();i[ub](c,g,a,b,d,e);c=i.key;g.key=c;u[p](i);qd[c]=i;rd[q]||(rd[q]=hd());rd[q][p](i);a.addEventListener?(a==M||!a.Ae)&&a.addEventListener(b,g,d):a.attachEvent(b in
sd?sd[b]:sd[b]="on"+b,g);return c}else throw da("Invalid event type");},td=function(a,b,c,d,e){if(Qb(b)){for(var g=0;g<b[A];g++)td(a,b[g],c,d,e);return j}d=!!d;a:{g=U;if(b in g&&(g=g[b],d in g&&(g=g[d],a=Wb(a),g[a]))){a=g[a];break a}a=j}if(!a)return k;for(g=0;g<a[A];g++)if(a[g].fc==c&&a[g][Ma]==d&&a[g].Fd==e)return ud(a[g].key);return k},ud=function(a){if(!qd[a])return k;var b=qd[a];if(b.Bb)return k;var c=b.src,d=b[y],e=b.ze,g=b[Ma];c.removeEventListener?(c==M||!c.Ae)&&c.removeEventListener(d,e,g):
c.detachEvent&&c.detachEvent(d in sd?sd[d]:sd[d]="on"+d,e);c=Wb(c);e=U[d][g][c];if(rd[c]){var i=rd[c];jc(i,b);i[A]==0&&delete rd[c]}b.Bb=h;e.He=h;vd(d,g,c,e);delete qd[a];return h},vd=function(a,b,c,d){if(!d.Tc&&d.He){for(var e=0,g=0;e<d[A];e++)if(d[e].Bb){var i=d[e].ze;i.src=j;ld(i);nd(d[e])}else e!=g&&(d[g]=d[e]),g++;ma(d,g);d.He=k;g==0&&(id(d),delete U[a][b][c],U[a][b].v--,U[a][b].v==0&&(gd(U[a][b]),delete U[a][b],U[a].v--),U[a].v==0&&(gd(U[a]),delete U[a]))}},wd=function(a,b,c){var d=0,e=b==j,
g=c==j,c=!!c;if(a==j)qc(rd,function(a){for(var i=a[A]-1;i>=0;i--){var q=a[i];if((e||b==q[y])&&(g||c==q[Ma]))ud(q.key),d++}});else if(a=Wb(a),rd[a])for(var a=rd[a],i=a[A]-1;i>=0;i--){var q=a[i];if((e||b==q[y])&&(g||c==q[Ma]))ud(q.key),d++}return d},yd=function(a,b,c,d,e){var g=1,b=Wb(b);if(a[b]){a.va--;a=a[b];a.Tc?a.Tc++:a.Tc=1;try{for(var i=a[A],q=0;q<i;q++){var u=a[q];u&&!u.Bb&&(g&=xd(u,e)!==k)}}finally{a.Tc--,vd(c,d,b,a)}}return Boolean(g)},xd=function(a,b){var c=a[Xa](b);a.Oe&&ud(a.key);return c};
kd(function(a,b){if(!qd[a])return h;var c=qd[a],d=c[y],e=U;if(!(d in e))return h;var e=e[d],g,i;Vc===f&&(Vc=T&&!M.addEventListener);if(Vc){var q;if(!(q=b))a:{q="window.event"[E](".");for(var u=M;g=q[va]();)if(u[g]!=j)u=u[g];else{q=j;break a}q=u}g=q;q=h in e;u=k in e;if(q){if(g[t]<0||g[vb]!=f)return h;a:{var B=k;if(g[t]==0)try{ja(g,-1);break a}catch(ha){B=h}(B||g[vb]==f)&&qa(g,h)}}B=od();B[ub](g,this);g=h;try{if(q){for(var J=hd(),X=B.currentTarget;X;X=X[Eb])J[p](X);i=e[h];i.va=i.v;for(var H=J[A]-1;!B.kb&&
H>=0&&i.va;H--)ia(B,J[H]),g&=yd(i,J[H],d,h,B);if(u){i=e[k];i.va=i.v;for(H=0;!B.kb&&H<J[A]&&i.va;H++)ia(B,J[H]),g&=yd(i,J[H],d,k,B)}}else g=xd(c,B)}finally{J&&(ma(J,0),id(J)),B.jb(),pd(B)}return g}d=new $c(b,this);try{g=xd(c,d)}finally{d.jb()}return g});var zd=function(){};R(zd,Xc);L=zd[C];L.Ae=h;L.Bd=j;L.addEventListener=function(a,b,c,d){V(this,a,b,c,d)};L.removeEventListener=function(a,b,c,d){td(this,a,b,c,d)};
L.dispatchEvent=function(a){var b=a[y]||a,c=U;if(b in c){if(Sb(a))a=new Zc(a,this);else if(a instanceof Zc)na(a,a[qb]||this);else{var d=a,a=new Zc(b,this);sc(a,d)}var d=1,e,c=c[b],b=h in c,g;if(b){e=[];for(g=this;g;g=g.Bd)e[p](g);g=c[h];g.va=g.v;for(var i=e[A]-1;!a.kb&&i>=0&&g.va;i--)ia(a,e[i]),d&=yd(g,e[i],a[y],h,a)&&a.hc!=k}if(k in c)if(g=c[k],g.va=g.v,b)for(i=0;!a.kb&&i<e[A]&&g.va;i++)ia(a,e[i]),d&=yd(g,e[i],a[y],k,a)&&a.hc!=k;else for(e=this;!a.kb&&e&&g.va;e=e.Bd)ia(a,e),d&=yd(g,e,a[y],k,a)&&
a.hc!=k;a=Boolean(d)}else a=h;return a};L.Ba=function(){zd.p.Ba[G](this);wd(this);this.Bd=j};var Bd=function(a,b,c,d,e){if(!T&&(!Cc||!Oc("525")))return h;if(Ec&&e)return Ad(a);if(e&&!d)return k;if(!c&&(b==17||b==18))return k;if(T&&d&&b==a)return k;switch(a){case 13:return!(T&&Qc(9));case 27:return!Cc}return Ad(a)},Ad=function(a){if(a>=48&&a<=57)return h;if(a>=96&&a<=106)return h;if(a>=65&&a<=90)return h;if(Cc&&a==0)return h;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return h;
default:return k}};var Cd=function(a,b){a&&this.xg(a,b)};R(Cd,zd);L=Cd[C];L.nc=j;L.Vc=j;L.Jd=j;L.Wc=j;L.Sa=-1;L.Ra=-1;
var Dd={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},Ed={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},Fd={61:187,59:186},Gd=T||Cc&&Oc("525");L=Cd[C];
L.bg=function(a){if(Cc&&(this.Sa==17&&!a[jb]||this.Sa==18&&!a.altKey))this.Ra=this.Sa=-1;Gd&&!Bd(a[t],this.Sa,a.shiftKey,a[jb],a.altKey)?this[Xa](a):this.Ra=Bc&&a[t]in Fd?Fd[a[t]]:a[t]};L.cg=function(){this.Ra=this.Sa=-1};
L.handleEvent=function(a){var b=a.ua,c,d;T&&a[y]=="keypress"?(c=this.Ra,d=c!=13&&c!=27?b[t]:0):Cc&&a[y]=="keypress"?(c=this.Ra,d=b[Ra]>=0&&b[Ra]<63232&&Ad(c)?b[Ra]:0):Ac?(c=this.Ra,d=Ad(c)?b[t]:0):(c=b[t]||this.Ra,d=b[Ra]||0,Ec&&d==63&&!c&&(c=191));var e=c,g=b.keyIdentifier;c?c>=63232&&c in Dd?e=Dd[c]:c==25&&a.shiftKey&&(e=9):g&&g in Ed&&(e=Ed[g]);a=e==this.Sa;this.Sa=e;b=new Hd(e,d,a,b);try{this.dispatchEvent(b)}finally{b.jb()}};
L.xg=function(a,b){this.Wc&&this.detach();this.nc=a;this.Vc=V(this.nc,"keypress",this,b);this.Jd=V(this.nc,"keydown",this.bg,b,this);this.Wc=V(this.nc,"keyup",this.cg,b,this)};L.detach=function(){if(this.Vc)ud(this.Vc),ud(this.Jd),ud(this.Wc),this.Wc=this.Jd=this.Vc=j;this.nc=j;this.Ra=this.Sa=-1};L.Ba=function(){Cd.p.Ba[G](this);this.detach()};var Hd=function(a,b,c,d){d&&this[ub](d,f);ka(this,"key");ja(this,a);this.charCode=b;this.repeat=c};R(Hd,$c);var Id=function(){};(function(a){a.xa=function(){return a.og||(a.og=new a)}})(Id);Id[C].zg=0;Id[C].Fa=function(){return":"+(this.zg++)[z](36)};Id.xa();var Jd="StopIteration"in M?M.StopIteration:da("StopIteration"),Kd=function(){};Kd[C].next=function(){throw Jd;};Kd[C].vg=function(){return this};var Ld=function(a,b){this.Qa={};this.V=[];var c=arguments[A];if(c>1){if(c%2)throw da("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.ag(a)};L=Ld[C];L.v=0;L.Id=0;L.Uc=function(){this.Md();for(var a=[],b=0;b<this.V[A];b++)a[p](this.Qa[this.V[b]]);return a};L.jc=function(){this.Md();return this.V.concat()};L.Cb=function(a){return l[C][nb][G](this.Qa,a)};
L.Md=function(){if(this.v!=this.V[A]){for(var a=0,b=0;a<this.V[A];){var c=this.V[a];l[C][nb][G](this.Qa,c)&&(this.V[b++]=c);a++}ma(this.V,b)}if(this.v!=this.V[A]){for(var d={},b=a=0;a<this.V[A];)c=this.V[a],l[C][nb][G](d,c)||(this.V[b++]=c,d[c]=1),a++;ma(this.V,b)}};L.get=function(a,b){return l[C][nb][G](this.Qa,a)?this.Qa[a]:b};L.set=function(a,b){l[C][nb][G](this.Qa,a)||(this.v++,this.V[p](a),this.Id++);this.Qa[a]=b};
L.ag=function(a){var b;if(a instanceof Ld)b=a.jc(),a=a.Uc();else{b=[];var c=0,d;for(d in a)b[c++]=d;c=[];d=0;for(var e in a)c[d++]=a[e];a=c}for(e=0;e<b[A];e++)this.set(b[e],a[e])};L.vg=function(a){this.Md();var b=0,c=this.V,d=this.Qa,e=this.Id,g=this,i=new Kd;i.next=function(){for(;;){if(e!=g.Id)throw da("The map has changed since the iterator was created");if(b>=c[A])throw Jd;var i=c[b++];return a?i:d[i]}};return i};var Md=function(a,b,c){this.Db=a||j;this.Te=b||j;this.ng=!!c};L=Md[C];L.Ab=function(){if(!this.R&&(this.R=new Ld,this.v=0,this.Db))for(var a=this.Db[E]("&"),b=0;b<a[A];b++){var c=a[b][s]("="),d=j,e=j;c>=0?(d=a[b].substring(0,c),e=a[b].substring(c+1)):d=a[b];d=fa(d[Da](/\+/g," "));d=this.zb(d);this.add(d,e?fa(e[Da](/\+/g," ")):"")}};L.R=j;L.v=j;L.add=function(a,b){this.Ab();this.xe();a=this.zb(a);if(this.Cb(a)){var c=this.R.get(a);Qb(c)?c[p](b):this.R.set(a,[c,b])}else this.R.set(a,b);this.v++;return this};
L.Cb=function(a){this.Ab();a=this.zb(a);return this.R.Cb(a)};L.jc=function(){this.Ab();for(var a=this.R.Uc(),b=this.R.jc(),c=[],d=0;d<b[A];d++){var e=a[d];if(Qb(e))for(var g=0;g<e[A];g++)c[p](b[d]);else c[p](b[d])}return c};L.Uc=function(a){this.Ab();if(a)if(a=this.zb(a),this.Cb(a)){var b=this.R.get(a);if(Qb(b))return b;else a=[],a[p](b)}else a=[];else for(var b=this.R.Uc(),a=[],c=0;c<b[A];c++){var d=b[c];Qb(d)?kc(a,d):a[p](d)}return a};
L.set=function(a,b){this.Ab();this.xe();a=this.zb(a);if(this.Cb(a)){var c=this.R.get(a);Qb(c)?this.v-=c[A]:this.v--}this.R.set(a,b);this.v++;return this};L.get=function(a,b){this.Ab();a=this.zb(a);if(this.Cb(a)){var c=this.R.get(a);return Qb(c)?c[0]:c}else return b};
la(L,function(){if(this.Db)return this.Db;if(!this.R)return"";for(var a=[],b=0,c=this.R.jc(),d=0;d<c[A];d++){var e=c[d],g=cc(e),e=this.R.get(e);if(Qb(e))for(var i=0;i<e[A];i++)b>0&&a[p]("&"),a[p](g),e[i]!==""&&a[p]("=",cc(e[i])),b++;else b>0&&a[p]("&"),a[p](g),e!==""&&a[p]("=",cc(e)),b++}return this.Db=a[Hb]("")});L.xe=function(){delete this.Jg;delete this.Db;this.Te&&delete this.Te.Ig};L.zb=function(a){a=String(a);this.ng&&(a=a[Nb]());return a};var W=function(a,b){this.x=a;this.y=b};W[C].Z=function(a){var b=this.x*a.b+this.y*a.d+a.f;this.x=this.x*a.a+this.y*a.c+a.e;this.y=b};var Nd=function(a,b,c,d,e,g){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e;this.f=g};L=Nd[C];L.ud=function(){var a=this.a*this.d-this.b*this.c;return new Nd(this.d/a,-this.b/a,-this.c/a,this.a/a,(this.c*this.f-this.d*this.e)/a,(this.b*this.e-this.a*this.f)/a)};
L.Yf=function(a){var b=n.cos(a),a=n.sin(a);return new Nd(this.a*b-this.c*a,this.b*b-this.d*a,this.a*a+this.c*b,this.b*a+this.d*b,this.e,this.f)};L.ac=function(a,b){return new Nd(this.a*a,this.b*a,this.c*b,this.d*b,this.e,this.f)};L.translate=function(a,b){return new Nd(this.a,this.b,this.c,this.d,this.e+a,this.f+b)};la(L,function(){return"matrix("+this.a+" "+this.b+" "+this.c+" "+this.d+" "+this.e+" "+this.f+")"});
L.multiply=function(a){return new Nd(this.a*a.a+this.c*a.b,this.b*a.a+this.d*a.b,this.a*a.c+this.c*a.d,this.b*a.c+this.d*a.d,this.a*a.e+this.c*a.f+this.e,this.b*a.e+this.d*a.f+this.f)};var Od=function(a,b,c,d,e,g,i){this.Vb=a;this.Ub=b;this.Tb=c;this.Sb=d;this.Rb=e;this.Qb=g;this.dd=i};Od[C].Ff=function(a){return a!=j&&this.Vb==a.Vb&&this.Ub==a.Ub&&this.Tb==a.Tb&&this.Sb==a.Sb&&this.Rb==a.Rb&&this.Qb==a.Qb};
var Pd=function(a,b,c,d){this.se();if(N(a))this.A=a;if(N(b))this.B=b;if(N(c))this.G=c;if(N(d))this.H=d};L=Pd[C];L.se=function(){this.A=Number[xa];this.G=Number.NEGATIVE_INFINITY;this.B=Number[xa];this.H=Number.NEGATIVE_INFINITY};L.expand=function(a){if(a.x<this.A)this.A=a.x;if(a.x>this.G)this.G=a.x;if(a.y<this.B)this.B=a.y;if(a.y>this.H)this.H=a.y};L.add=function(a){this.B+=a.B;this.H+=a.H;this.A+=a.A;this.G+=a.G};
L.Z=function(a){var b=new W(this.A,this.B),c=new W(this.A,this.H),d=new W(this.G,this.B),e=new W(this.G,this.H);this.se();b.Z(a);c.Z(a);d.Z(a);e.Z(a);this[Ba](b);this[Ba](c);this[Ba](d);this[Ba](e)};L.Df=function(a){return(this.A>=a.A&&this.A<=a.G||this.G>=a.A&&this.G<=a.G||a.A>=this.A&&a.A<=this.G)&&(this.B>=a.B&&this.B<=a.H||this.H>=a.B&&this.H<=a.H||a.B>=this.B&&a.B<=this.H)};L.contains=function(a,b){return a>=this.A&&a<=this.G&&b>=this.B&&b<=this.H};
L.kg=function(a){this[Ba](new W(a.A,a.B));this[Ba](new W(a.A,a.H));this[Ba](new W(a.G,a.B));this[Ba](new W(a.G,a.H))};var Qd=function(){};l[Ta](Qd[C],"unwatch",{get:function(){return function(a){if(arguments[A]<1)return k;var b=this[a];delete this[a];this[a]=b;return h}}});l[Ta](Qd[C],"watch",{get:function(){return function(a,b,c){if(arguments[A]<2)return k;for(var d=this,e=j,g=this;g[zb];g=g[zb])if(l.getOwnPropertyDescriptor(g,a)!=j){d=g;e=l.getOwnPropertyDescriptor(g,a);break}if(!e||e.configurable){var i=d[a];delete d[a];l[Ta](d,a,{get:function(){return i},set:function(d){return i=b[G](this,a,i,d,c)},configurable:h})}return h}}});
var Rd={};Qd.registerClass=function(a,b){if(arguments[A]<2)return k;Rd[a]=b;return h};var Sd=function(a,b,c,d,e,g,i){N(a)&&N(b)?(c=N(c)?c:1,d=N(d)?d:0,e=N(e)?e:0,g=N(g)?g:0,i=N(i)?i:0,this.Rd=new Date(a,b,c,d,e,g,i)):this.Rd=N(a)?new Date(a):new Date;if(!Sd[C].getDate){a=l.getOwnPropertyNames(this.Rd[zb]);for(b=0;b<a[A];b++)a[b]!="constructor"&&(Sd[C][a[b]]=Zb(function(a,b){return this.Rd[a](b)},a[b]))}};Sd.UTC=Date.UTC;var Td=function(){switch(arguments[A]){case 0:break;case 1:ma(this,arguments[0]);break;default:for(var a=0;a<arguments[A];++a)this[p](arguments[a])}};R(Td,ca);var Ud=function(){},Vd={},Wd=0,Xd=0,Yd=[];Ud.addListener=function(a){N(a)&&"onKeyUp"in a&&"onKeyDown"in a&&(hc(Yd,a)>=0||Yd[p](a))};Ud.getAscii=function(){return Xd};Ud.getCode=function(){return Wd};Ud.isDown=function(a){return Vd[a]?h:k};Ud.isToggled=function(){return k};Ud.removeListener=function(a){jc(Yd,a)};
l[Ka](Ud,{BACKSPACE:{value:8,O:h},CAPSLOCK:{value:20,O:h},CONTROL:{value:17,O:h},DELETEKEY:{value:46,O:h},DOWN:{value:40,O:h},END:{value:35,O:h},ENTER:{value:13,O:h},ESCAPE:{value:27,O:h},HOME:{value:36,O:h},INSERT:{value:45,O:h},LEFT:{value:37,O:h},PGDN:{value:34,O:h},PGUP:{value:33,O:h},RIGHT:{value:39,O:h},SHIFT:{value:16,O:h},SPACE:{value:32,O:h},TAB:{value:9,O:h},UP:{value:38,O:h}});V(m,"keyup",function(a){Wd=a[t];Vd[a[t]]=k;for(a=0;a<Yd[A];++a)Yd[a].onKeyUp()},k);
V(new Cd(m),"key",function(a){Wd=a[t];Xd=a[Ra];Vd[a[t]]=h;for(a=0;a<Yd[A];++a)Yd[a].onKeyDown()},k);var Zd=function(a){this.I=a;this.xb=[];V(this.I.Ga(),"mousedown",this.Fb,h,this);V(this.I.Ga(),"mouseup",this.Gb,h,this);V(this.I.Ga(),"mousemove",this.hd,h,this)};L=Zd[C];L.ya=h;L.update=function(){this.I.Ga()[F].cursor=this.ya?this.I.Jc()?"pointer":this.I.Sf()?"pointer":!this.I[Jb]()&&this.I.Tf()?"pointer":"default":"none"};L.Fb=function(){ic(this.xb,function(a){a.Lg()})};L.hd=function(){ic(this.xb,function(a){a.Mg()})};L.Gb=function(){ic(this.xb,function(a){a.Ng()})};
Zd[C].addListener=function(a){if(N(a)){var b=this.I.l().j(a,"onMouseMove"),c=this.I.l().j(a,"onMouseUp");this.I.l().j(a,"onMouseDown")in a&&b in a&&c in a&&(hc(this.xb,a)>=0||this.xb[p](a))}};Zd[C].hide=function(){var a=this.ya;this.ya=k;this[Fb]();return a};Zd[C].show=function(){var a=this.ya;this.ya=h;this[Fb]();return a};Zd[C].removeListener=function(a){jc(this.xb,a)};var de=function(a,b,c,d){var e=j;switch(a[y]){case 2:d=$d("linearGradient",a,c);d[v]("x1",-16384);d[v]("x2",16384);e=d;break;case 3:case 4:d=$d("radialGradient",a,c);d[v]("r",16384);d[v]("cx",0);d[v]("cy",0);a[db].f&&c.la(d,"fx",a[db].f,function(a){return a*16384});e=d;break;case 5:case 7:if(c=d.Da[a[za]])b=ae(be(a[Kb]),b[0]),e=ce(a,b,c.h[ya],c.h[K],d)}if(a[db]&&a[db].spread)switch(a[db].spread){case 1:e[v]("spreadMethod","reflect");break;case 2:e[v]("spreadMethod","repeat")}if(a[db]&&a[db].interpolation)switch(a[db].interpolation){case 1:e[v]("color-interpolation",
"linearRGB")}if(e!=j)e.id=Id.xa().Fa();return e},$d=function(a,b,c){a=m[D]("http://www.w3.org/2000/svg",a);a[v]("gradientUnits","userSpaceOnUse");b[Kb]&&c.la(a,"gradientTransform",b[Kb],be);for(var d=0;d<b[db].stops[A];d++)a[o](ee(b[db].stops[d],c));return a},ee=function(a,b){var c=m[D]("http://www.w3.org/2000/svg","stop");b.la(c,"offset",a.offset,function(a){return a/255});b.la(c,"stop-color",a[La],fe);b.la(c,"stop-opacity",a[La],ge);return c},he=function(a,b,c,d){switch(b[y]){case 1:c.la(a,"fill",
b[La],fe);c.la(a,"fill-opacity",b[La],ge);break;case 2:case 3:case 4:a[v]("fill","url(#"+d.id+")")}};function ie(a,b){this.De=a;this.Ee=b}
var ae=function(a,b){function c(a,b){e.x=a;e.y=b;e.Z(d);g[p](e.x);i[p](e.y)}var d=a.ud(),e=new W(0,0),g=[],i=[];c(b[yb],b[sa]);c(b[Cb],b[sa]);c(b[yb],b[wa]);c(b[Cb],b[wa]);return new ie(g,i)},ce=function(a,b,c,d,e){var g=m[D]("http://www.w3.org/2000/svg","g");g.id=Id.xa().Fa();var i=m[D]("http://www.w3.org/2000/svg","g"),q=m[D]("http://www.w3.org/2000/svg","g");q[o](g);q[o](i);for(var a=e.Da[a[za]].fa(),u=n[Ga](n.min[I](n,b.De)/c),e=n.ceil(n.max[I](n,b.De)/c);u<e;u++){var B=m[D]("http://www.w3.org/2000/svg",
"use");B[Ja]("http://www.w3.org/1999/xlink","href","#"+a.id);B[v]("x",u*c);g[o](B)}c=n[Ga](n.min[I](n,b.Ee)/d);for(b=n.ceil(n.max[I](n,b.Ee)/d);c<b;c++)a=m[D]("http://www.w3.org/2000/svg","use"),a[Ja]("http://www.w3.org/1999/xlink","href","#"+g.id),a[v]("y",c*d),i[o](a);return q};var je=function(a,b,c,d){if(b!=j){if(b[bb]!=j)a[v]("stroke","url(#"+d.id+")");else if(b[La]!=j)c.la(a,"stroke",b[La],fe),c.la(a,"stroke-opacity",b[La],function(a){return a?ge(a):1});else a[v]("stroke","rgb(0,0,0)");c.la(a,"stroke-width",b[ya],function(a){return n.max(14,a)});c="round";if(b.cap!=j)switch(b.cap){case 1:c="butt";break;case 2:c="square"}a[v]("stroke-linecap",c);c="round";if(b.joint!=j)switch(b.joint){case 1:c="bevel";break;case 2:c="miter"}a[v]("stroke-linejoin",c);b.miter!=j&&a[v]("stroke-miterlimit",
b.miter)}};var ke=function(){this.K={}};ke[C].Ua=function(a,b){this.K[a]=b};ke[C].fg=function(a){return this.K[a]?this.K[a]:j};ke[C].qf=function(a,b){this.K[a]&&this.K[a].ig(b)};var me=function(a){this.u=[];this.me=k;this.cf=a;this.Lc=[];this.o=new le(this)};L=me[C];L.qb=function(a,b){a.depth=b;pc(this.u,a,function(a,b){return a[x]-b[x]});ne(this.r,a)};L.Nd=function(a){return nc(this.u,function(a,c){return a-c[x]}||oc,k,a)};L.vc=function(a){a=this.Nd(a);return a>=0?this.Xc(a):j};L.Xc=function(a,b){var c=this.u[a];b!=h&&(c.qe()?(c.Oa(),this.Lc[p](c)):(oe(this.r,c),c.J(),this.o.pe(c)));this.u[Gb](a,1);c.depth=f;return c};
L.Xe=function(a){a=this.Nd(a);return a<0?j:this.Xc(a,h)};L.Uf=function(a){for(var b=0;b<this.u[A];++b)if(this.u[b]==a)return this.Xc(b)};L.md=function(a){a=this.Nd(a);return a>=0?this.u[a]:j};L.J=function(){for(var a=0;a<this.u[A];a++)this.Xc(a)};L.Oa=function(){for(var a=0;a<this.u[A];a++)this.u[a].Oa()};L.Vf=function(){for(var a=0;a<this.Lc[A];a++){var b=this.Lc[a];b.J();this.o.pe(b);oe(this.r,b)}this.Lc=[]};L.Qf=function(a){this.me=a};
L.te=function(a){this.r=a;for(var b=0;b<this.u[A];++b)ne(a,this.u[b])};L.gc=function(a,b){this.r&&(oe(this.r,a),b&&ne(this.r,a,b))};L.Ld=function(a,b){var c=this.Xe(a),d=this.Xe(b);c&&this.qb(c,b);d&&this.qb(d,a)};var ne=function(a,b,c){a&&(N(c)||(c=b[Qa]()),c&&(a[c]=b.D()))},oe=function(a,b){if(a){var c=b[Qa]();c&&delete a[c]}};
me[C].Mf=function(a){for(var b=0,c=0;b<this.u[A]||c<a.u[A];){var d=this.u[b],e=a.u[c],g=d?d[x]:Number[xa],i=e?e[x]:Number[xa];i<g?(e[tb](),this.qb(e,i),c++,b++):i>g?d.Jb()?b++:this.vc(g):(S(g==i),S(d&&e),d.Jb()||(!d.Ea()||!e.Ea()||d.ob!=e.ob?(this.vc(i),e[tb](),this.qb(e,i)):(d[Oa](e.L()),d.Ma(e.ea),e.J())),b++,c++)}};var le=function(a){this.t=a;this.Oc=[]};le[C].pe=function(a){this.Oc[p](a)};
le[C].q=function(){if(!this.C)this.C=this.t.me?m[D]("http://www.w3.org/2000/svg","clipPath"):m[D]("http://www.w3.org/2000/svg","g");this.de();for(var a=j,b=-1,c=this.t.u,d=0;d<c[A];++d){var e=c[d],g=e.o;e[x]>b&&(a=j);g.q();g.Af(a);g=g.fa();if(this.C[Ya][d]!=g){var i=this.C;i.insertBefore(g,i[Ya][d]||j)}if(e.pa>0)a=e,b=e.pa}};le[C].fa=function(){return this.C};le[C].de=function(){for(var a=0;a<this.Oc[A];++a){var b=this.Oc[a].o;Sc(b.fa());b.J()}this.Oc=[]};var pe=function(a){this.g=a;this.pa=0;this.Xb="";this.eb=j;this.P=1;this.Va=k;this.Na=[];this.ya=h;this.ob=0;this.fe=this.ee=k;this.Ec=new Nd(1,0,0,1,0,0);this.ea=new Od(256,0,256,0,256,0,256)};L=pe[C];L.Ja=function(a){l[Ta](a,"__swiffy_d",{value:this});l[Ka](a,qe)};L.D=function(){if(!this.r)this.r=new re,this.Ja(this.r);return this.r};L.ka=function(){this.Ag=h};L.Jb=function(){return!!this.Ag};L.setTransform=function(a){if(this.Ec!=a)this.W(2),this.Ec=a};L.L=function(){return this.Ec};
L.jd=function(a){S(this.pa==0);this.pa=a};L.W=function(a){a&&this.eb!=j&&this.eb.Ie();this.P|=a};L.Ie=function(){!this.Va&&this[ua]()!=j&&this[ua]().Ie();this.Va=h};L.wc=function(a){this.ob=a};L.J=function(){this.fe=h};L.Oa=function(){this.ee=h};L.Ma=function(a){if(this.ea!=a)this.W(8),this.ea=a};L.za=function(){return this.o.za()};L.be=function(a){if(this.Na!=a)this.W(4),this.Na=a};L.nb=function(a){a=String(a);a!=this.Xb&&this.eb&&this.eb.gc(this,a);this.Xb=a};L.getName=function(){return this.Xb};
L.Gc=function(a){this.eb=a};L.getParent=function(){return this.eb};L.lg=function(a){if(this.ya!=a)this.W(16),this.ya=a};L.Ea=function(){return k};L.qe=function(){return k};L.cb=function(){return this.o.cb()};L.Ca=function(){};pa(L,function(){});var te=function(a){this.i=a;this.ne=this.Ka=this.vb=this.qa=j;this.fd=new se(this);this.Na=[];this.Hb=j;this.Wd=eval("typeof SVGFilterElement")!="undefined"};L=te[C];L.fa=function(){return this.C};
L.q=function(){var a=this.i.P;if(a||this.i.Va){if(a&1)a^=1,this.C=this.Xa=this.$a();a&16&&(a^=16,this.C[v]("display",this.i.ya?"inline":"none"));a&2&&(a^=2,this.i.pa==0&&this.Xa[v]("transform",this.cd()));if(a&4&&(a^=4,this.Wd)){var b="SourceGraphic";if(this.qa)this.Na=[],Rc(this.qa),this.fd[I](b);for(var c=0;c<this.i.Na[A];++c){var d=new ue[this.i.Na[c][y]](this,this.i.Na[c]);if(d)this.Na[p](d),d[I](b),b=d[fb](),d=d.region,this.Hb==j?this.Hb=d:d!=j&&this.Hb.add(d)}this.fd.ef(b);var e=this;this.i.g.Yd(function(){e.ff()})}a&
8&&(a^=8,this.Xa[v]("opacity",this.i.ea.dd/256),this.Wd&&this.fd.q());if(this.qa){var g=this.C;this.i.g.Yd(function(){g[v]("transform",g.getAttribute("transform"))})}this.i.P=a}};L.cd=function(){var a=this.i.Ec[z]();N(this.qd)&&(a+=" "+this.qd);var b=this.i[ua]();b&&b.pa>0&&(a=b.o.cd()+" "+a);return a};
L.Af=function(a){if(this.ne!=a){if(a){if(!this.Ka)this.Ka=m[D]("http://www.w3.org/2000/svg","g"),Tc(this.Ka,this.C),this.Ka[o](this.C),this.C=this.Ka;this.Ka[v]("clip-path","url(#"+a.o.Of()+")")}else if(this.Ka==this.C){var b=this.Ka.firstChild;Tc(b,this.C);this.C=b;this.Ka=j}this.ne=a}};L.Of=function(){if(!N(this.Kd))this.Kd=Id.xa().Fa(),this.C.id=this.Kd;return this.Kd};L.J=function(){this.qa!=j&&Sc(this.qa)};
L.cb=function(){this.i.g.q();var a=this.C.getBBox(),b=[];b[0]=new W(a.x,a.y);b[1]=new W(a.x,a.y+a[K]);b[2]=new W(a.x+a[ya],a.y);b[3]=new W(a.x+a[ya],a.y+a[K]);for(var a=new Pd,c=0;c<b[A];++c)a[Ba](b[c]);return a};L.za=function(){this.i.g.q();var a;a=j;for(var b=this.C;b instanceof SVGElement;){if(b[Kb]){var c=b[Kb].baseVal.consolidate();c!=j&&(a=a!=j?c[Ea].multiply(a):c[Ea])}b=b[Eb]}return a!=j?new Nd(a.a,a.b,a.c,a.d,a.e,a.f):new Nd(1,0,0,1,0,0)};
L.$=function(){if(this.qa==j){this.qa=m[D]("http://www.w3.org/2000/svg","filter");this.qa.id=Id.xa().Fa();this.i.g.mb[o](this.qa);if(this.vb==j&&(this.vb=m[D]("http://www.w3.org/2000/svg","g"),Tc(this.vb,this.Xa),this.vb[o](this.Xa),this.C==this.Xa))this.C=this.vb;this.vb[v]("filter","url(#"+this.qa.id+")")}return this.qa};
L.ff=function(){if(this.Hb!=j){var a=this.Hb,b=this.C.getBBox(),c=this.$(),d=a.G-a.A,e=a.H-a.B;if(b[ya]<=0)b.width=1;if(b[K]<=0)b.height=1;d/=b[ya];var g=a.B/b[K];e/=b[K];c[v]("x",a.A/b[ya]-0.1);c[v]("width",1.2+d);c[v]("y",g-0.1);c[v]("height",1.2+e)}};var ve=function(a){pe[G](this,a);this.ma=1;this.Me=k};R(ve,pe);var we={Wg:1,Ug:2,$g:4,Yg:8,Zg:16,gh:32,Sg:64,Xg:128,Rg:256,eh:512,fh:1024,dh:2048,bh:4096,ah:8192,Tg:16384,Pg:32768,Og:65536,Vg:131072,Qg:262144},xe={256:"onDragOver",512:"onRollOut",1024:"onRollOver",2048:"onReleaseOutside",4096:"onRelease",8192:"onPress",262144:"onDragOut"},ye=function(a,b){l[Ta](this,a,{value:b});var c=this.__swiffy_d;c&&c.ge()},ze=function(){};L=ve[C];L.ge=function(){if(!this.Me)this.W(128),this.Me=h};
L.na=function(a){this.yd(a.ma);this.Gd(a.ua)};L.Gd=function(a){var b=xe[a];b&&this.D()[b]&&this.g.l().zd(P(function(){this.D()[b]()},this))};L.yd=function(a){if(this.ma!=a)this.ma=a};L.trackAsMenu=function(){return k};L.yf=function(){this.g.Gf(this);this.g[Jb]()==k&&this.ma==1?this.na(Ae):this[Ab]()&&this.g.Jc()==k&&this.ma==1?this.na(Be):this.g.Ad(this)&&this.ma==2&&this.na(Ce)};
L.ad=function(){this.g.Hf(this);this.g[Jb]()==k&&this.ma==2?this.na(De):this[Ab]()&&this.g.Jc()==k&&this.ma==4?this.na(Ee):this.g.Ad(this)&&this.ma==4&&this.na(Fe)};L.Fb=function(a){this[Ab]()?this.g[Fa](this):this.g[Fa](this,h,P(this.Jf,this));a[lb]();this.na(Ge)};L.Gb=function(a){var b=this[Ab]()&&this.g.Jc()==k||this.g.Ad(this);this.g[ab](this);a[lb]();b?this.na(He):this.na(Ae)};L.Jf=function(){this.na(Ie)};var Je=function(a){te[G](this,a);this.ja=[]};R(Je,te);
Je[C].q=function(){Je.p.q[G](this);if(this.i.P&128){this.i.P^=128;var a=this.Hc();a[F].pointerEvents="all";var b=this.i,c;"createTouch"in m||(c=V(a,"mouseover",b.yf,k,this.i),this.ja[p](c));c=V(a,"mouseout",b.ad,k,this.i);this.ja[p](c);c=V(a,"createTouch"in m?"touchend":"mouseup",b.Gb,k,this.i);this.ja[p](c);c=V(a,"createTouch"in m?"touchstart":"mousedown",b.Fb,k,this.i);this.ja[p](c)}};
Je[C].re=function(a,b,c){var d,e;if(a)d="keydown",e=function(b){return b[t]==a};else if(b)d="keypress",e=function(a){return a[Ra]==b};else return;this.ja[p](V(m,d,function(a){e(a)&&(c(),a[lb]())},h,this.i))};Je[C].J=function(){Je.p.J[G](this);for(var a=0;a<this.ja[A];a++)ud(this.ja[a])};var Ke=function(a,b,c){this.Xb=a;this.ma=b;this.ua=c};Ke[C].getName=function(){return this.Xb};
var Be=new Ke("IdleToOverDown",4,256),Ae=new Ke("IdleToOverUp",2,1024),Ie=new Ke("OutDownToIdle",1,2048),Ce=new Ke("OutDownToOverDown",4,256),Ee=new Ke("OverDownToIdle",1,262144),Fe=new Ke("OverDownToOutDown",2,262144),He=new Ke("OverDownToOverUp",2,4096),De=new Ke("OverUpToIdle",1,512),Ge=new Ke("OverUpToOverDown",4,8192);var Me=function(a,b){ve[G](this,b.g);this.h=a;this.Wa=b;this.u=new me(k);this.gd=new me(k);this.o=new Le(this);this.h[hb]&&this.uf(this.h[hb]);this.od(this.u,1);this.od(this.gd,8);this.ge()};R(Me,ve);L=Me[C];L.Ja=function(a){Me.p.Ja[G](this,a);this.u.te(a)};L.uf=function(a){for(var b=0;b<a[A];b++){var c=a[b];c.convertedActions=this.Wa.l().Ya(c[hb]);if(c[t]||c.keyAscii){var d=P(this.ve,this,c);this.o.re(c[t],c.keyAscii,d)}}};
L.yd=function(a){a!=this.ma&&this.od(this.u,a,this.ma);Me.p.yd[G](this,a);var b=this.o;setTimeout(function(){b.q()},0)};L.ve=function(a){this.ke(a);this.g.l().td()};L.wf=function(a){var b=this.h[hb];if(b){for(var c=0;c<b[A];c++){var d=b[c];d[nb](a[Qa]())&&this.ke(d)}this.g.l().td()}};L.Ge=function(){return this.Wa};L.na=function(a){var b=this.h.sounds;b&&b[nb](a[Qa]())&&this.g.sb().he(b[a[Qa]()]);this.wf(a);Me.p.na[G](this,a)};L.trackAsMenu=function(){return this.h[Ab]};
L.ke=function(a){this.Wa.l().Hd(new Ne(a.convertedActions,this.Ge()))};L.od=function(a,b,c){this.W(32);var d=this.h.records;if(d){if(N(c))for(var e=0;e<d[A];e++){var g=d[e],i=g[Va]&c,q=g[Va]&b;i&&!q&&a.vc(g[x])}for(e=0;e<d[A];e++)if(g=d[e],i=g[Va]&c,(q=g[Va]&b)&&!i)i=this.Wa.$c(g.id),i.Ea()&&b!=8&&i.nb(this.g.Ud()),i.Gc(this),i.Ca(),i[tb](),a.qb(i,g[x]),g[Kb]&&i[Oa](be(g[Kb])),g[xb]&&i.Ma(Oe(g[xb]))}};L.Ea=function(){return h};L.gc=function(a,b){this.u.gc(a,b)};var Le=function(a){Je[G](this,a)};
R(Le,Je);Le[C].$a=function(){var a=this.i.u.o;a.q();this.i.gd.o.q();this.Hc()[v]("style","visibility:hidden;");var b=m[D]("http://www.w3.org/2000/svg","g");b[o](a.fa());b[o](this.Hc());return b};Le[C].q=function(){Le.p.q[G](this);var a=this.i.P;if(this.i.Va||a&32)a&=-33,this.i.Va=k,this.i.u.o.q();this.i.P=a};Le[C].Hc=function(){return this.i.gd.o.fa()};var Qe=function(a,b){pe[G](this,b.g);this.h=a;this.Wa=b;this.o=new Pe(this);this.h[ib]&&b.g.l().sf(this.h[ib],this,b,this.h[Aa]);this.h[Aa]&&!N(this.qc)&&this.kd(this.h[Aa])};R(Qe,pe);Qe[C].kd=function(a){if(this.qc!=a)this.W(64),this.qc=a};Qe[C].J=function(){Qe.p.J[G](this);this.h[ib]&&this.Wa.l().zf(this.h[ib],this,this.Wa)};Qe[C].Ea=function(){return this.h[ib]!=f};var Pe=function(a){te[G](this,a)};R(Pe,te);
Pe[C].q=function(){Pe.p.q[G](this);if(this.i.P&64&&(this.i.P^=64,Rc(this.ld),N(this.i.qc))){var a=String(this.i.qc);if(this.i.h.html)Re(this.ld,a,this.i.h.multiline);else for(var b=this.ld,a=a[E](/\r\n|\r|\n/g),c=0;c<a[A];c++)if(a[c]==""){var d=m[Sa]("br");b[o](d)}else{var d=m.createTextNode(a[c]),e=m[Sa]("p");e[F].margin=0;e[o](d);b[o](e)}}};
Pe[C].$a=function(){var a=this.i.h,b=a.bounds,c=m[D]("http://www.w3.org/2000/svg","g"),d=m[D]("http://www.w3.org/2000/svg","foreignObject"),e=m[Sa]("body");d[o](e);var g=m[Sa]("div");this.ld=g;var i=this.i.g.Da[a.font];if(i)g[F].fontFamily="'"+i.rd+"'";g[F].fontSize=a[K]+"px";if(a.bold)g[F].fontWeight="bold";if(a.italic)g[F].fontStyle="italic";if(a[La]){var q=fe(a[La]);g[F].color=q[z]();g[F].opacity=q.a}g[F].textAlign=Se(a.align);if(a.wrap){if(!a.html)g[F].whiteSpace="pre-wrap"}else g[F].whiteSpace=
"nowrap";g[F].wordWrap="break-word";if(a.selectable)g[F].Fg="all";g[F].textIndent=a[ta]+"px";if(a[ta]+a.leftMargin<0){var u=-(a[ta]+a.leftMargin),B=-a[ta],q=b[yb]+30-u;d[v]("width",b[Cb]-b[yb]-60+u);g[F].marginLeft=B+"px"}else q=b[yb]+30,d[v]("width",b[Cb]-b[yb]-60),g[F].marginLeft=a.leftMargin+"px";g[F].marginRight=a.rightMargin+"px";this.qd="translate("+q+" 0)";d[v]("x",0);a.border&&(u=m[D]("http://www.w3.org/2000/svg","rect"),u[v]("x",b[yb]-q),u[v]("y",b[sa]),u[v]("width",b[Cb]-b[yb]),u[v]("height",
b[wa]-b[sa]),u[v]("fill","white"),u[v]("stroke","black"),u[v]("stroke-width","10"),c[o](u));q=a[K]*1.15;a.font!=f&&i&&(q=a[K]*i.rf);i=q;a.leading&&(q+=a.leading);g[F].lineHeight=q+"px";g[F].paddingTop=a[K]+(i-q)*0.5+"px";d[v]("y",b[sa]+40-a[K]);d[v]("height",b[wa]-b[sa]-80+a[K]);e[o](g);c[o](d);return c};
var Re=function(a,b,c){var d=a,e=[],g=function(a,b){var c=m[Sa](a);d[o](c);d=c;e[p](b)},a=b[Da](/&nbsp;/g," ");Te(a,{sg:function(a,b){switch(a){case "p":g("p",a);d[F].margin=0;var e=b[Ha]("align");if(e)d[F].textAlign=e[Lb];if(!c)d[F].display="inline";break;case "b":case "i":case "u":g(a,a);break;case "a":g(a,a);(e=b[Ha]("href"))&&d[v]("href",e[Lb]);(e=b[Ha]("target"))&&d[v]("target",e[Lb]);d[F].Kg="all";d[F].color="inherit";break;case "br":e=m[Sa]("br");d[o](e);break;case "font":g("span",a);if(e=
b[Ha]("color"))d[F].color=e[Lb];if(e=b[Ha]("size"))d[F].fontSize=e[Lb]*20+"px";if(e=b[Ha]("face"))d[F].fontFamily=e[Lb]}},rg:function(a){e[e[A]-1]==a&&(e.pop(),d=d[Eb])},qg:function(a){d[o](m.createTextNode(a))}})},Se=function(a){switch(a){case 0:return"left";case 2:return"center";case 1:return"right";case 3:return"justify";default:return"left"}},Te=function(a,b){var c=m[Sa]("div");c.innerHTML=a;for(var d=0;d<c[Ya][A];d++)Ue(c[Ya][d],b)},Ue=function(a,b){switch(a.nodeType){case Node.ELEMENT_NODE:var c=
a.nodeName[Nb]();b.sg(c,a.attributes);for(var d=0;d<a[Ya][A];d++)Ue(a[Ya][d],b);b.rg(c);break;case Node.TEXT_NODE:b.qg(a.textContent)}};var We=function(a,b){pe[G](this,b.g);this.h=a;this.o=new Ve(this)};R(We,pe);var Ve=function(a){te[G](this,a);this.pb=[];this.tc=[]};R(Ve,te);L=Ve[C];L.$a=function(){var a=this.i,b=a.h,c=b.fillstyles;if(c)for(var d=0;d<c[A];d++)if(c[d]!=f){var e=de(c[d],b.bounds,this,a.g);e!=j&&(this.pb[d]=e,a.g.mb[o](e))}if(c=b.linestyles)for(d=0;d<c[A];d++)c[d]!=f&&c[d][bb]!=f&&(e=de(c[d][bb],b.bounds,this,a.g),e!=j&&(this.tc[d]=e,a.g.mb[o](e)));return this.tf()};
L.tf=function(){var a=this.i,b=a.h,c;c=a.pa==0?m[D]("http://www.w3.org/2000/svg","g"):m[D]("http://www.w3.org/2000/svg","clipPath");for(var d=0;d<b.paths[A];d++){var e=b.paths[d],g=m[D]("http://www.w3.org/2000/svg","path");this.la(g,"d",e[r],Xe);g.onclick=function(){};c[o](g);if(e.line!=j&&b.linestyles!=j){var i=b.linestyles[e.line];je(g,i,this,i[bb]?this.tc[e.line]:j)}if(e[bb]!=j)if(i=b.fillstyles[e[bb]],i[za]==j)he(g,i,this,this.pb[e[bb]]);else{var q=m[D]("http://www.w3.org/2000/svg","clipPath");
q.id=Id.xa().Fa();q[o](g);a.g.mb[o](q);g=m[D]("http://www.w3.org/2000/svg","g");g[v]("clip-path","url(#"+q.id+")");c[o](g);q=m[D]("http://www.w3.org/2000/svg","use");if(i[y]==5||i[y]==7)S(this.pb[e[bb]].id!=j),q[Ja]("http://www.w3.org/1999/xlink","href","#"+this.pb[e[bb]].id);else q[Ja]("http://www.w3.org/1999/xlink","href","#"+a.g.Da[i[za]].fa().id);i[Kb]&&q[v]("transform",be(i[Kb])[z]());g[o](q)}else g[v]("fill","none")}c[Ya][A]==1&&a.pa==0?(a=c[Ya][0],Sc(a)):a=c;return a};
L.q=function(){var a=this.i.P;Ve.p.q[G](this);if(a&2&&this.i.pa>0){var b=this.cd();ic(this.Xa[Ya],function(a){a[v]("transform",b)})}};L.la=function(a,b,c,d){S(c[A]==1);c=c[0];if(c instanceof Ye||c instanceof Nd)c=c[z]();a[v](b,d?d(c):c)};L.J=function(){Ve.p.J[G](this);for(var a=0;a<this.pb[A];a++)Sc(this.pb[a]);for(a=0;a<this.tc[A];a++)Sc(this.tc[a])};var Ze=function(a,b){this.Cf=a;this.Bf=b};Ze[C].wb=function(){return 0};var $e=function(a,b,c,d){Ze[G](this,a,b);this.z=c;this.ca=d};R($e,Ze);$e[C].wb=function(a){return this.z+(this.ca-this.z)*a};var af=function(a,b,c,d){Ze[G](this,a,b);this.z=c;this.ca=d};R(af,Ze);af[C].wb=function(a){return(new Nd(this.z.a+(this.ca.a-this.z.a)*a,this.z.b+(this.ca.b-this.z.b)*a,this.z.c+(this.ca.c-this.z.c)*a,this.z.d+(this.ca.d-this.z.d)*a,this.z.e+(this.ca.e-this.z.e)*a,this.z.f+(this.ca.f-this.z.f)*a))[z]()};
var bf=function(a,b,c,d){Ze[G](this,a,b);this.z=c;this.ca=d};R(bf,Ze);bf[C].wb=function(a){return(new Ye(n.round(this.z.ib+(this.ca.ib-this.z.ib)*a),n.round(this.z.hb+(this.ca.hb-this.z.hb)*a),n.round(this.z.b+(this.ca.b-this.z.b)*a),this.z.a+(this.ca.a-this.z.a)*a))[z]()};var cf=function(a,b,c,d){Ze[G](this,a,b);this.$e=c[E](" ");this.af=d[E](" ");S(this.$e[A]==this.af[A])};R(cf,Ze);
cf[C].wb=function(a){for(var b="",c=this.$e,d=this.af,e=0;e<c[A];e++){var g=ea(c[e],10);isNaN(g)?(S(c[e]==d[e]),b+=c[e]+" "):b+=g+(ea(d[e],10)-g)*a+" "}return b};var ef=function(a,b){We[G](this,a,b);this.o=new df(this)};R(ef,We);ef[C].wc=function(a){a!=this.ob&&this.W(256);ef.p.wc[G](this,a)};var df=function(a){Ve[G](this,a);this.$b=[]};R(df,Ve);df[C].$a=function(){return df.p.$a[G](this)};
df[C].la=function(a,b,c,d){if(c[A]==1)a[v](b,d?d(c[0]):c[0]);else S(c[A]==2),this.wg(a,b,d?d(c[0]):c[0],d?d(c[1]):c[1])};df[C].wg=function(a,b,c,d){var e;c instanceof Nd?e=af:typeof c=="number"?e=$e:c instanceof Ye?e=bf:(S(b=="d"),e=cf);c=new e(a,b,c,d);a[v](b,c.wb(this.i.ob/65535));this.$b[p](c)};df[C].q=function(){df.p.q[G](this);if(this.i.P&256){this.i.P^=256;for(var a=this.i.ob/65535,b=0;b<this.$b[A];b++){var c=this.$b[b].Cf,d=this.$b[b].Bf,e=this.$b[b].wb(a);c[v](d,e)}}};var gf=function(a,b){pe[G](this,b.g);this.h=a;this.o=new ff(this)};R(gf,pe);var ff=function(a){te[G](this,a)};R(ff,te);
ff[C].$a=function(){var a;a=this.i.pa==0?m[D]("http://www.w3.org/2000/svg","g"):m[D]("http://www.w3.org/2000/svg","clipPath");var b=this.i.h;this.qd=be(b[Ea])[z]();for(var c=0;c<b.records[A];c++){var d=b.records[c],e=m[D]("http://www.w3.org/2000/svg","text");e[o](m.createTextNode(d[Aa]));var g=this.i.g.Da[d.font];g&&e[v]("font-family","'"+g.rd+"'");e[v]("font-size",d[K]);d.bold&&e[v]("font-weight","bold");d.italic&&e[v]("font-style","italic");e[v]("x",hf(d.x));e[v]("y",d.y);e[v]("fill-rule","nonzero");
e[v]("style","white-space:pre");d[La]&&(d=fe(d[La]),e[v]("fill",d[z]()),e[v]("fill-opacity",d.a));a[o](e)}return a};var jf=function(){};jf[C].ig=function(a){this.ih=a};jf[C].eg=function(a){return this.Eb(a)};var kf=function(a){ve[G](this,a);this.t=new me(k)};R(kf,ve);L=kf[C];L.jd=function(a){kf.p.jd[G](this,a);this.t.Qf(h)};L.bd=function(a,b){this.W(32);a[ua]()!=j&&a[ua]()[pb](a);a.Gc(this);this.t.qb(a,b)};L.removeChild=function(a){this.W(32);this.t.Uf(a);a.Gc(j)};L.uc=function(a){this.W(32);(a=this.t.vc(a))&&a.Gc(j)};L.Ja=function(a){kf.p.Ja[G](this,a);this.t.te(a)};L.gc=function(a,b){this.t.gc(a,b)};L.D=function(){if(!this.r)this.r=new lf,this.Ja(this.r);return this.r};
L.Ld=function(a,b){this.W(32);this.t.Ld(a,b)};var mf=function(a){Je[G](this,a)};R(mf,Je);mf[C].q=function(){if((this.i.P&1||this.i.P&2)&&this.i.pa>0)for(var a=this.i.t.u,b=0;b<a[A];++b)a[b].W(2);mf.p.q[G](this);a=this.i;b=a.P;if(a.Va||b&32)b&=-33,a.Va=k,a.t.o.q();a.P=b};mf[C].J=function(){mf.p.J[G](this);this.i.t.o.de()};var of=function(a){var b=function(b){b instanceof re||(b=a.l().Nf(String(b)));this.r=b;this.ue=0};l[Ka](b[C],nf);return b},nf={getRGB:{value:function(){return this.ue}},setRGB:{value:function(a){if(this.r)this.ue=a,this.r.__swiffy_d.Ma(new Od(0,(a&16711680)>>16,0,(a&65280)>>8,0,a&255,256)),this.r.__swiffy_d.ka()}},setTransform:{value:function(a){if(this.r&&a){var b=this.r.__swiffy_d;this.r.__swiffy_d.Ma(new Od(a[b.g.l().j(a,"ra")]*256/100,a[b.g.l().j(a,"rb")],a[b.g.l().j(a,"ga")]*256/100,a[b.g.l().j(a,
"gb")],a[b.g.l().j(a,"ba")]*256/100,a[b.g.l().j(a,"bb")],a[b.g.l().j(a,"aa")]*256/100));this.r.__swiffy_d.ka()}}},getTransform:{value:function(){if(!this.r)return j;var a=this.r.__swiffy_d.ea;return{ra:a.Vb*100/256,rb:a.Ub,ga:a.Tb*100/256,gb:a.Sb,ba:a.Rb*100/256,bb:a.Qb,aa:a.dd*100/256,ab:0}}}};var qf=function(a,b,c){kf[G](this,b);this.h=a;this.Lb={};this.rc={};this.M=-1;this.tb=a.frameCount;this.xc=k;this.sa=0;this.K=c;this.ed={};this.Ta=b.Ta;this.Vd=this.ae=k;this.df=[];this.Ib={};this.Za={};this.o=new pf(this);this.g.pf(this)};R(qf,kf);L=qf[C];
L.gg=function(){if(!this.Vd){for(var a=0;a<this.h.tags[A];a++){var b=this.h.tags[a];switch(b[y]){case 10:var c=new rf(b);this.K.Ua(b.id,c);break;case 13:c=new sf(b);this.K.Ua(b.id,c);break;case 5:c=new tf(b);this.g.Da[b.id]=c;break;case 8:c=new uf(b);this.g.Da[b.id]=c;break;case 1:c=new vf(b);this.K.Ua(b.id,c);break;case 17:c=new wf(b);this.K.Ua(b.id,c);break;case 11:c=new xf(b);c.sd(this.sb());break;case 7:c=new yf(b,this.g,this.K);this.K.Ua(b.id,c);break;case 6:c=new zf(b);this.K.Ua(b.id,c);break;
case 9:c=new Af(b,this.l());this.Ob(this.sa,c);break;case 20:this.rc[this.sa]||(this.rc[this.sa]=[]);this.rc[this.sa][p](b);break;case 18:this.g.Dg.Eg(j);break;case 19:var b=b.references,d;for(d in b)c=Number(d),this.K.qf(c,b[c]);break;case 15:this.ed[b.label]=this.sa;break;case 3:c=new Bf(b);this.Ob(this.sa,c);break;case 4:c=new Cf(b);this.Ob(this.sa,c);break;case 2:this.sa++;break;case 12:c=new Df(b);this.Ob(this.sa,c);break;case 16:c=new Ef(b),this.Ob(this.sa,c)}}this.Vd=h}};
L.Ca=function(){this.gg();this.Fe();this.Yb(128);this.zc||this.Ne()};pa(L,function(){if(!this.ae)this.ae=h,this[Wa](),this.Ce(k),this.zc&&this.Ne()});L.Pb=function(a){if(a=this.Za[a])for(var b=0;b<a[A];++b)this.l().Qc(a[b])};L.Yb=function(a){if(a=this.Za[a])for(var b=0;b<a[A];++b)this.l().Hd(a[b])};L.qe=function(){return this.Za!=f&&this.Za[32]!=f};
L.of=function(a,b,c,d){for(var e in we){var g=we[e];if(a&g){this.Za[g]||(this.Za[g]=[]);this.Za[g][p](new Ne(d,this));if(g>=256&&g<=8192)this.Gg=h;g&131072&&(g=P(this.Yb,this,131072),this.o.re(b,c,g))}}};L.$c=function(a){return(a=this.K.fg(a))?a.eg(this):j};L.Ge=function(){return this};L.Ja=function(a){qf.p.Ja[G](this,a);l[Ka](a,Ff)};L.J=function(){this.g.Ef(this);this.t.J();qf.p.J[G](this)};L.Oa=function(){this.ee||(this.t.Oa(),this.Yb(32));qf.p.Oa[G](this)};
L.Ob=function(a,b){this.Lb[a]||(this.Lb[a]=[]);this.Lb[a][p](b)};L.play=function(){this.xc=h};L.If=function(){this.t.Vf();this.xc?this.Ce(h):this.Dd()};L.Ce=function(a){var b=this.M+1;b>=this.tb&&(b=0);(this.tb!=0||this.g.ha!=this)&&this.Mc(b,a)};L.Gd=function(a){this.Yb(a);qf.p.Gd[G](this,a)};L.Dd=function(){this.Yb(64);this.l().zd(P(function(){this.D().onEnterFrame()},this))};L.Ne=function(){this.l().zd(P(function(){this.D().onLoad()},this))};L.stop=function(){this.xc=k};
L.ic=function(a,b){a>=0&&a<this.tb?this.Mc(a):this.M=this.tb+1;this.xc=b};L.Wb=function(a){var b=f;typeof a=="string"&&this.ed[a]!=f?b=this.ed[a]:(a=Number(a)-1,a>=0&&a==n[Ga](a)&&(b=a));return b};L.xf=function(a){return this.Lb[a]};
L.Mc=function(a,b){var c=k,d=this.t;if(a<this.M)c=h,this.t=new me(h),this.M=-1;for(a==this.M&&b&&this.Dd();this.M<a;){this.M++;this.M==a&&b&&this.Dd();this.Lf(this.M);var e=this.Lb[this.M];if(e)for(var g=0;g<e[A];g++)e[g].ec(this),this.M==a&&e[g].dc(this)}e=this.df[this.M];O(e)&&e();if(c)d.Mf(this.t),this.t=d};L.Lf=function(a){for(a=this.rc[a];a&&a[A]>0;){var b=this.l(),c=a[va](),c=b.Ya(c[hb]);b.Qc(new Ne(c,this))}};L.Se=function(){this.M>0&&this.Mc(this.M-1);this[cb]()};
L.Re=function(){this.M+1<this.tb&&this.Mc(this.M+1);this[cb]()};L.l=function(){return this.g.l()};L.sb=function(){return this.g.sb()};L.Ga=function(){return this.g.Ga()};L.hg=function(a,b){this.D()[a]=b};L.setCapture=function(a,b,c){this.g[Fa](a,b,c)};L.releaseCapture=function(a){this.g[ab](a)};L.duplicate=function(a,b,c){var d=new qf(this.h,this.g,this.K);d.zc=h;d.nb(b);d[Oa](this.L());d.Ca();d[tb]();a.bd(d,c);d.Ma(this.ea);return d};L.D=function(){this.r||this.Fe();return this.r};
L.Fe=function(){var a=Y;if(this.h.id){var b=Rd[this.g.Sd[this.h.id]];b!=j&&(a=b)}this.r=l.create(a[C]);this.Ja(this.r);a[I](this.r)};L.Ea=function(){return h};var pf=function(a){Je[G](this,a)};R(pf,mf);
pf[C].$a=function(){var a=this.i,b=a.t.o;b.q();var b=b.fa(),c=Zb(a.Pb,1),c=V(m,"keyup",c,k,a);this.ja[p](c);c=Zb(a.Pb,2);c=V(m,"keydown",c,k,a);this.ja[p](c);c=Zb(a.Pb,4);c=V(a.g.Ga(),"createTouch"in m?"touchend":"mouseup",c,k,a);this.ja[p](c);c=Zb(a.Pb,8);c=V(a.g.Ga(),"createTouch"in m?"touchstart":"mousedown",c,k,a);this.ja[p](c);c=Zb(a.Pb,16);c=V(a.g.Ga(),"createTouch"in m?"touchmove":"mousemove",c,k,a);this.ja[p](c);return b};pf[C].Hc=function(){return this.fa()};var Gf=function(){this.Ye=[];this.Zc=[]};Gf[C].sd=function(a,b){this.Ye[a]=b};Gf[C].he=function(a){this.Zc[a]=new Audio(this.Ye[a]);this.Zc[a][Wa]()};Gf[C].dg=function(){for(var a in this.Zc)this.Zc[a].pause()};var Kf=function(a,b){this.pd=k;this.sc=new W(0,0);this.Da={};this.Cc=[];this.ta=m[D]("http://www.w3.org/1999/xhtml","div");this.ta[v]("style","position:relative;");a[o](this.ta);this.jf=new Gf;this.ub=m[D]("http://www.w3.org/2000/svg","svg");this.$d=b[sb][Cb];this.Zd=b[sb][wa];var c="fill-rule:evenodd;";c+="pointer-events:none;";c+="width:"+this.$d/20+"px;";c+="height:"+this.Zd/20+"px;";b.backgroundColor!=f&&(c+="background:"+fe(b.backgroundColor)[z]());this.ub[v]("style",c);this.ub[v]("viewBox",
b[sb][yb]+" "+b[sb][sa]+" "+b[sb][Cb]+" "+b[sb][wa]);this.ta[o](this.ub);this.Cg=b[sb][Cb]/b[sb][wa];c=new ke;this.Ac=new Hf(b.frameRate,this);c.Ua(0,new yf(b,this,c));this.Ta=b.version;this.ha=new qf(b,this,c);this.yc=new If(this.ha);this.Ha=j;this.nd=k;this.Bc=j;this.Td={};this.Sd={};this.Nb=new Zd(this);this.kf=new Jf(this);this.nf=1;this.Ia={};this.Ia.v=0;V(this.ta,"mousedown",this.Fb,k,this);V(this.ta,"mouseup",this.Gb,k,this);V(this.ta,"mouseout",this.ad,k,this);"createTouch"in m||V(this.ta,
"mousemove",this.hd,k,this);V(m,"mousedown",this.gf,k,this);V(m,"mouseup",this.hf,k,this);V(this.ta,"touchstart",this.mf,k,this);V(this.ta,"touchmove",this.lf,k,this);this.ha.Ca();this.mb=m[D]("http://www.w3.org/2000/svg","defs");for(var d in this.Da)this.mb[o](this.Da[d].Ca());this.ha.o.q();this.ub[o](this.mb);this.ub[o](this.ha.o.fa())},Lf="swiffy.Stage"[E]("."),Mf=M;!(Lf[0]in Mf)&&Mf.execScript&&Mf.execScript("var "+Lf[0]);
for(var Nf;Lf[A]&&(Nf=Lf[va]());)!Lf[A]&&N(Kf)?Mf[Nf]=Kf:Mf=Mf[Nf]?Mf[Nf]:Mf[Nf]={};L=Kf[C];L.Fb=function(a){a[lb]();this[Fa](this)};L.Gb=function(a){a[lb]();this[ab](this)};L.gf=function(){this[Fa](this,h)};L.hf=function(){this[ab](this)};L.ad=function(a){this[Jb]()&&a[qb]==this.ta&&this[Fa](this)};L.hd=function(a){this.Od(a)};L.mf=function(a){var b=a.ua.touches;b[A]==1&&(this.Od(b[0]),a[Ia]())};L.lf=function(a){var b=a.ua.touches;b[A]==1&&(this.Od(b[0]),a[Ia]())};
L.Od=function(a){var b;b=this.ub;var c=0,d=0;if(b.offsetParent){do c+=b.offsetLeft,d+=b.offsetTop;while(b=b.offsetParent)}b=[c,d];this.sc.x=a.clientX-b[0];this.sc.y=a.clientY-b[1]};L.Tf=function(){return this.Ia.v>0};L.Gf=function(a){a=Wb(a);a in this.Ia||(this.Ia[a]=h,this.Ia.v++);this.Nb[Fb]()};L.Hf=function(a){a=Wb(a);a in this.Ia&&(delete this.Ia[a],this.Ia.v--);this.Nb[Fb]()};L.isCaptured=function(){return this.Ha!=j};L.Jc=function(){return this.Ha!=j&&this.nd};
L.Ad=function(a){return this.Ha==a};L.Sf=function(){return this.Ha?Wb(this.Ha)in this.Ia:k};L.setCapture=function(a,b,c){this[ab](a);this.Ha=a;m.Xf=function(){return k};if(b)this.nd=h;if(c)this.Bc=c,this.Nb[Fb]()};L.releaseCapture=function(a){if(this.Ha)this.Nb[Fb](),m.Xf=j,this.Ha!=a&&this.Bc&&this.Bc(),this.Ha=this.Bc=j,this.nd=k};pa(L,function(){this.ha[Wa]();this.Ac[tb]()});pa(Kf[C],Kf[C][tb]);L=Kf[C];L.pf=function(a){this.Ac.Pd(a)};L.Ef=function(a){this.Ac.tg(a)};L.l=function(){return this.yc};
L.sb=function(){return this.jf};L.Pd=function(a){this.Ac.Pd(a)};L.Ga=function(){return this.ta};L.Bg=function(a){for(var a=new Md(a),b=a.jc(),c=0;c<b[A];c++){var d=b[c];this.ha.hg(d,a.get(d))}};Kf[C].setFlashVars=Kf[C].Bg;Kf[C].Ud=function(){return"instance"+this.nf++};Kf[C].Yd=function(a){this.Cc[p](a)};Kf[C].q=function(){if(!this.pd){this.pd=h;this.ha.o.q();for(var a=0;a<this.Cc[A];a++)this.Cc[a]();this.Cc=[];this.pd=k}};var Ye=function(a,b,c,d){this.ib=a;this.hb=b;this.b=c;this.a=d};la(Ye[C],function(){return"rgb("+this.ib+","+this.hb+","+this.b+")"});
var fe=function(a){var b=a&255;a>>=8;var c=a&255;a>>=8;var d=a&255;a>>=8;return new Ye(b,c,d,1-(a&255)/255)},ge=function(a){return fe(a).a},be=function(a){var b=0,c=Of(function(){return a[wb](b++)});return new Nd(c()/1E3+1,c()/1E3,c()/1E3,c()/1E3+1,c(),c())},hf=function(a){for(var b=0,c=Pf(function(){return a[wb](b++)}),d=[],e=0;b<a[A];)e+=ea(c(),10),d[p](e);return d[Hb](" ")},Pf=function(a){return function(){var b=a();if(b==58)return 0;for(var c="";b>=48&&b<=57;)c+=String.fromCharCode(b),b=a();return(b>=
97?b-96:-(b-64))+c}},Of=function(a){var b=Pf(a);return function(){return ea(b(),10)}},Xe=function(a){for(var b=0,c=a[s](":"),d=c+1,e=Pf(function(){return a[wb](d++)}),g="",i;b<c;)switch(i=a.charAt(b++),g[A]>0&&(g+=" "),g+=i+" ",i){case "q":g+=e()+" "+e()+" ";case "l":case "m":g+=e()+" ";case "h":case "v":g+=e();break;default:return""}return g},Oe=function(a){var b=0,c=Of(function(){return a[wb](b++)});return new Od(c()+256,c(),c()+256,c(),c()+256,c(),c()+256)},Qf=function(a){return a<=0.04045?a/12.92:
n.pow((a+0.055)/1.055,2.4)},Rf=function(a){return a<=0.0031308?a*12.92:n.pow(a,1/2.4)*1.055-0.055},Sf=function(a,b){var c=new W(b.x*20,b.y*20);c.Z(a.ud());c.x/=20;c.y/=20;return c},Tf=function(a,b){var c=a.g.l().Pa(b);if(!isNaN(c))return c};var Uf=function(a){this.o=a;this.Rf=Id.xa().Fa();this.region=new Pd(0,0,0,0)},ue=[];L=Uf[C];ra(L,function(){});L.result=function(){return this.Rf};L.Pe=function(a,b,c,d,e){var g=1;switch(a){case 1:g=5;break;case 2:g=3;break;case 3:g=2}a=b*20/g;c=c*20/g;g=m[D]("http://www.w3.org/2000/svg","feGaussianBlur");N(d)&&g[v]("in",d);N(e)&&g[v]("result",e);g[v]("stdDeviation",a+" "+c);this.$()[o](g);d=new Pd;d[Ba](new W(-a*3,-c*3));d[Ba](new W(+a*3,+c*3));return d};
L.La=function(a,b,c,d,e,g,i){var q=m[D]("http://www.w3.org/2000/svg","feComponentTransfer");N(g)&&q[v]("in",g);N(i)&&q[v]("result",i);N(e)||(e="linear");g=["feFuncR","feFuncG","feFuncB","feFuncA"];a=[a,b,c,d];for(b=0;b<4;++b){var c=j,u;for(u in a[b])c==j&&(c=m[D]("http://www.w3.org/2000/svg",g[b]),c[v]("type",e)),c[v](u,a[b][u]);c&&q[o](c)}this.$()[o](q)};
L.wa=function(a,b,c,d,e){var g=m[D]("http://www.w3.org/2000/svg","feComposite");N(e)&&g[v]("result",e);N(b)&&g[v]("in",b);N(c)&&g[v]("in2",c);g[v]("operator",a);if(N(d))for(var i in d)g[v](i,d[i]);this.$()[o](g)};L.Pf=function(a){var b=m[D]("http://www.w3.org/2000/svg","feFlood");N(a)&&b[v]("result",a);this.$()[o](b)};
L.jg=function(a,b,c,d){var e=n.cos(a)*b*20,a=n.sin(a)*b*20,b=m[D]("http://www.w3.org/2000/svg","feOffset");N(c)&&b[v]("in",c);N(d)&&b[v]("result",d);b[v]("dx",e);b[v]("dy",a);this.$()[o](b);return new Pd(e,a,e,a)};L.Ed=function(a,b,c,d,e,g){this.La({slope:0},{slope:0},{slope:0},{},"linear",a);a=this.Pe(b,c,d);g!=0&&this.region.kg(this.jg(e,g));this.region.add(a)};L.Rc=function(){return Id.xa().Fa()};L.$=function(){return this.o.$()};var Vf=function(a,b){Uf[G](this,a);this.oc=b[Ea];this.oc[4]/=255;this.oc[9]/=255;this.oc[14]/=255;this.oc[19]/=255};R(Vf,Uf);ue[3]=Vf;
ra(Vf[C],function(a){for(var b=[],c=[],d=0;d<256;d++)b[d]=Rf(d/255),c[d]=Qf(d/255);var e={tableValues:b[Hb](" ")},c={tableValues:c[Hb](" ")},b=this.Rc(),d=this.Rc();this.La(e,e,e,e,"discrete",a,b);a=this.$();e=m[D]("http://www.w3.org/2000/svg","feColorMatrix");e[v]("in",b);e[v]("result",d);e[v]("type","matrix");e[v]("values",this.oc[Hb](" "));a[o](e);this.La(c,c,c,c,"discrete",d,this[fb]())});var se=function(a){Uf[G](this,a);this.Kc="SourceGraphic";this.oe=a.i.ea};R(se,Uf);se[C].q=function(){var a=this.o.i.ea;!(this.o.i instanceof Qe)&&!a.Ff(this.oe)&&(this.oa==j&&this[I](this.Kc),this[Fb]());this.oe=a};se[C].update=function(){if(this.oa!=j){var a=this.o.i.ea;this.xd[v]("tableValues",Wf(a.Vb,a.Ub));this.wd[v]("tableValues",Wf(a.Tb,a.Sb));this.vd[v]("tableValues",Wf(a.Rb,a.Qb))}};se[C].ef=function(a){this.Kc=a;this.oa!=j&&(this.oa[v]("in",this.Kc),a=this.$(),a[pb](this.oa),a[o](this.oa))};
ra(se[C],function(a){this.Kc=a;var b=this.$();this.oa=m[D]("http://www.w3.org/2000/svg","feComponentTransfer");this.oa[v]("in",a);this.oa[v]("result",this[fb]());this.xd=m[D]("http://www.w3.org/2000/svg","feFuncR");this.xd[v]("type","discrete");this.oa[o](this.xd);this.wd=m[D]("http://www.w3.org/2000/svg","feFuncG");this.wd[v]("type","discrete");this.oa[o](this.wd);this.vd=m[D]("http://www.w3.org/2000/svg","feFuncB");this.vd[v]("type","discrete");this.oa[o](this.vd);b[o](this.oa);this[Fb]()});
var Wf=function(a,b){a/=256;b/=256;for(var c=[],d=0;d<256;d++)c[d]=Qf(Rf(d/255)*a+b);return c[Hb](" ")};var Xf=function(a,b){Uf[G](this,a);this.cc=b};R(Xf,Uf);ue[2]=Xf;ra(Xf[C],function(a){var b=this.cc;this.region=this.Pe(b[Mb],b.x,b.y,a,this[fb]())});var Yf=function(a,b){Uf[G](this,a);this.cc=b};R(Yf,Uf);ue[1]=Yf;
ra(Yf[C],function(a){var b=this.cc,c=this.$();b[gb]&&this.Pf("black");this.Ed(a,b[Mb],b.x,b.y,b.angle,b.distance);b[gb]&&this.wa("arithmetic",f,"black",{k2:-1,k3:1});var d=fe(b[La]);this.La({intercept:Qf(d.ib/255)},{intercept:Qf(d.hb/255)},{intercept:Qf(d.b/255)},{slope:b.strength});d.a<1&&this.La({},{},{},{slope:d.a});c[rb][v]("result","shadow");!b[gb]&&!b[Pa]&&!b.hideObject?this.wa("over",a,"shadow"):b[gb]&&!b[Pa]&&!b.hideObject?this.wa("atop","shadow",a):!b[gb]&&b[Pa]?this.wa("out","shadow",a):
b[gb]&&this.wa("in","shadow",a);c[rb][v]("result",this[fb]())});var Zf=function(a,b){Uf[G](this,a);this.cc=b};R(Zf,Uf);ue[4]=Zf;
ra(Zf[C],function(a){var b=this.cc,c=this.$(),d=this.Rc(),e=this.Rc();this.Ed(a,b[Mb],b.x,b.y,b.angle,-b.distance);var g=fe(b.highlight);this.La({intercept:Qf(g.ib/255)},{intercept:Qf(g.hb/255)},{intercept:Qf(g.b/255)},{slope:b.strength});g.a<1&&this.La({},{},{},{slope:g.a});c[rb][v]("result",e);this.Ed(a,b[Mb],b.x,b.y,b.angle,b.distance);g=fe(b.shadow);this.La({intercept:Qf(g.ib/255)},{intercept:Qf(g.hb/255)},{intercept:Qf(g.b/255)},{slope:b.strength});g.a<1&&this.La({},{},{},{slope:g.a});c[rb][v]("result",
d);this.wa("xor",d,e,{},"shadow");b[Pa]?b[gb]?this.wa("in","shadow",a):b.onTop||this.wa("out","shadow",a):b[gb]?this.wa("atop","shadow",a):b.onTop?this.wa("over","shadow",a):this.wa("over",a,"shadow");c[rb][v]("result",this[fb]())});var rf=function(a){this.h=a};R(rf,jf);rf[C].Eb=function(a){return new Me(this.h,a)};var sf=function(a){this.h=a};R(sf,jf);sf[C].Eb=function(a){return new Qe(this.h,a)};var tf=function(a){this.h=a;this.rd=Id.xa().Fa()};tf[C].fa=function(){return this.yb};
tf[C].Ca=function(){var a;a=this.h.emSquareSize?this.h.emSquareSize:1024;var b,c,d;this.h.ascent&&this.h.descent?(b=this.h.ascent,c=this.h.descent,d=(b+c)/a):(this.h[$a]&&!this.h[mb]?(b=m[D]("http://www.w3.org/1999/xhtml","div"),b[F].fontFamily=this.h[$a],b[F].fontSize="1024px",b.innerHTML="A",m[ob][o](b),d=b.clientHeight/1024,Sc(b)):d=1.15,b=a*0.9,c=a*(d-0.9));this.rf=d;d=m[D]("http://www.w3.org/2000/svg","font-face");d[v]("units-per-em",a);d[v]("ascent",b);d[v]("descent",c);b="'"+this.rd+"'";this.h[$a]&&
(b+=",'"+this.h[$a]+"'");d[v]("font-family",b);d[v]("font-weight",this.h.bold?"bold":"normal");d[v]("font-style",this.h.italic?"italic":"normal");if(this.h[$a]&&!this.h[mb])a=m[D]("http://www.w3.org/2000/svg","font-face-src"),b=m[D]("http://www.w3.org/2000/svg","font-face-name"),b[v]("name",this.h[$a]),a[o](b),d[o](a),this.yb=d;else{b=m[D]("http://www.w3.org/2000/svg","font");b[v]("horiz-adv-x",a);b[o](d);if(this.h[mb])for(a=0;a<this.h[mb][A];a++)d=this.h[mb][a],c=m[D]("http://www.w3.org/2000/svg",
"glyph"),c[v]("d",Xe(d[r])),c[v]("unicode",d.unicode),d.advance&&c[v]("horiz-adv-x",d.advance),b[o](c);this.yb=b}return this.yb};var uf=function(a){this.h=a};uf[C].fa=function(){return this.yb};
uf[C].Ca=function(){var a=m[D]("http://www.w3.org/2000/svg","image");a.id=Id.xa().Fa();a[v]("width",this.h[ya]);a[v]("height",this.h[K]);if(this.h.mask){var b=this.h[ya],c=this.h[K],d=m[Sa]("canvas");d.width=this.h[ya];d.height=this.h[K];var e=new Image,g=new Image,i=k,q=k,u=function(){if(i&&q){var u=d.getContext("2d");u.clearRect(0,0,b,c);u.drawImage(e,0,0,b,c);u.globalCompositeOperation="xor";u.drawImage(g,0,0,b,c);a[Ja]("http://www.w3.org/1999/xlink","href",d.toDataURL("image/png"))}};e.onload=
function(){i=h;u()};g.onload=function(){q=h;u()};e.src=this.h[r];g.src=this.h.mask}else a[Ja]("http://www.w3.org/1999/xlink","href",this.h[r]);return this.yb=a};var wf=function(a){this.h=a};R(wf,jf);wf[C].Eb=function(a){return new ef(this.h,a)};var vf=function(a){this.h=a};R(vf,jf);vf[C].Eb=function(a){return new We(this.h,a)};var xf=function(a){this.h=a};xf[C].sd=function(a){a.sd(this.h.id,this.h[r])};var yf=function(a,b,c){this.h=a;this.I=b;this.K=c};R(yf,jf);yf[C].Eb=function(){return new qf(this.h,this.I,this.K)};var zf=function(a){this.h=a};R(zf,jf);zf[C].Eb=function(a){return new gf(this.h,a)};var Af=function(a,b){this.Hg=a;this.Ke=b.Ya(a[hb]);this.yc=b};Af[C].ec=function(){};Af[C].dc=function(a){this.yc.Hd(new Ne(this.Ke,a))};Af[C].Zb=function(a){this.yc.Qc(new Ne(this.Ke,a))};var Df=function(a){this.pg=a};Df[C].ec=function(a){a.sb().he(this.pg.id)};Df[C].dc=function(){};Df[C].Zb=function(){};var Bf=function(a){this.m=a};
Bf[C].ec=function(a){var b=a.t.md(this.m[x]);if(!b||!b.Jb())if(b||!this.m[Da])if(!b||this.m[Da]||!this.m.id)if(b&&(b.Ea()||!this.m.id))this.ce(b);else{var c=b,b=a.$c(this.m.id);if(b!=j)if(b.Ea()&&c)this.ce(c);else{this.m[$a]?b.nb(this.m[$a]):b.Ea()&&b.nb(a.g.Ud());var d=j;this.m[Ea]&&(d=be(this.m[Ea]));var e=j;this.m[xb]&&(e=Oe(this.m[xb]));if(this.m[Da])d||(d=c.L()),e||(e=c.ea);this.m.clip&&b.jd(this.m.clip);if(this.m[hb])for(var g=0;g<this.m[hb][A];++g){var i=a.l().Ya(this.m[hb][g].action);b.of(this.m[hb][g].events,
this.m[hb][g][t],this.m[hb][g].keyAscii,i)}c&&a.uc(this.m[x]);b.Ca();a.bd(b,this.m[x]);this.m[Na]!=f&&b.wc(this.m[Na]);d&&b[Oa](d);this.m[Bb]&&b.be(this.m[Bb]);e&&b.Ma(e);!c&&!a.t.cf&&b[tb]()}}};Bf[C].ce=function(a){this.m[Ea]&&a[Oa](be(this.m[Ea]));this.m[xb]&&a.Ma(Oe(this.m[xb]));this.m[Na]!=f&&a.wc(this.m[Na]);var b=[];this.m[Bb]&&(b=this.m[Bb]);a.be(b)};Bf[C].dc=function(){};Bf[C].Zb=function(){};var Cf=function(a){this.Sc=a};
Cf[C].ec=function(a){var b=a.t.md(this.Sc[x]);if(!b||!b.Jb())b&&b.Oa(),a.uc(this.Sc[x])};Cf[C].dc=function(a){var b=a.t.md(this.Sc[x]);b&&b.Jb()&&(b.Oa(),a.uc(this.Sc[x]))};Cf[C].Zb=function(){};var Ef=function(a){this.Kf=a};Ef[C].ec=function(a){var b=this.Kf,c;for(c in b[r])a.g.Td[c]=b[r][c],a.g.Sd[b[r][c]]=c};Ef[C].dc=function(){};Ef[C].Zb=function(){};var Hf=function(a,b){this.Wf=a;this.I=b;this.Nc=[];this.Je=k};Hf[C].Pd=function(a){this.Nc[p](a)};Hf[C].tg=function(a){jc(this.Nc,a)};Hf[C].Ze=function(){for(var a=this.Nc[A]-1;a>=0;--a)this.Nc[a].If();this.I.l().td();this.I.q()};pa(Hf[C],function(){if(!this.Je)this.Je=h,this.Ze(),aa.setInterval(P(this.Ze,this),1E3/this.Wf)});var Ne=function(a,b){this.ye=a;this.i=b};var $f=function(a,b){this.object=a;this.method=b},ag=function(a,b){this.w=a;ga(this,{});this.N=b};L=ag[C];L.get=function(a){var b=this.w.j(this[r],a);return b in this[r]?this[r][b]:this.N.get(a)};oa(L,function(a,b){var c=this.w.j(this[r],a);if(c in this[r])if(c=this[r][c],c instanceof $f){var d=c.method.p[kb];if(O(d))return d[I](c.object,b)}else{if(O(c))return c[I](this.Y(),b)}else return this.N[G](a,b)});
L.set=function(a,b){var c=this.w.j(this[r],a);return c in this[r]?(this[r][c]=b,h):this.N.set(a,b)};L.Aa=function(a,b){this[r][this.w.j(this[r],a)]=b};L.bc=function(a){a=this.w.j(this[r],a);a in this[r]||(this[r][a]=f)};L.fb=function(a){this.w.j(this[r],a)in this[r]||this.N.fb(a)};la(L,function(){return"function->"+this.N[z]()});L.U=function(a){return this.N.U(a)};L.Y=function(){return this.N.Y()};var bg=function(a,b,c){this.w=a;ga(this,c);this.N=b};L=bg[C];
L.get=function(a){var b=this.w.j(this[r],a);return b in this[r]?this[r][b]:this.N.get(a)};oa(L,function(a,b){var c=this.w.j(this[r],a);if(c in this[r]){if(c=this[r][c],O(c))return c[I](this[r],b)}else return this.N[G](a,b)});L.set=function(a,b){var c=this.w.j(this[r],a);return c in this[r]?(this[r][c]=b,h):this.N.set(a,b)};L.Aa=function(a,b){var c=this.w.j(this[r],a);c in this[r]?this[r][c]=b:this.N.Aa(a,b)};L.bc=function(a){this.w.j(this[r],a)in this[r]||this.N.bc(a)};
L.fb=function(a){var b=this.w.j(this[r],a);b in this[r]?delete this[r][b]:this.N.fb(a)};la(L,function(){return this[r]+"->"+this.N[z]()});L.U=function(a){return this.N.U(a)};L.Y=function(){return this.N.Y()};var cg=function(a,b,c){this.w=a;ga(this,c);this.Cd=b;this.we=c};L=cg[C];L.get=function(a){var b=this.w.j(this[r],a);return b in this[r]?this[r][b]:a[Nb]()=="this"?this.we:this.Cd.get(a)};
oa(L,function(a,b){var c=this.w.j(this[r],a),d=this[r][c];if(c in this[r]){if(O(d))return d[I](this[r],b)}else return this.Cd[G](a,b)});L.set=function(a,b){this[r][this.w.j(this[r],a)]=b;return h};L.Aa=function(a,b){this[r][this.w.j(this[r],a)]=b};L.bc=function(a){a=this.w.j(this[r],a);a in this[r]||(this[r][a]=f)};L.fb=function(a){var b=this.w.j(this[r],a);b in this[r]?delete this[r][b]:this.Cd.fb(a)};la(L,function(){return this[r]+""});L.U=function(a){return ga(this,a?a:this.we)};L.Y=function(){return this[r]};
var dg=function(a,b){this.w=a;ga(this,new Z(b));this[r]._global=this[r]};L=dg[C];L.get=function(a){return this[r][this.w.j(this[r],a)]};oa(L,function(a,b){var c=this[r][this.w.j(this[r],a)];if(O(c))return c[I](this[r],b)});L.set=function(){return k};L.Aa=function(){};L.bc=function(){};L.fb=function(a){delete this[r][this.w.j(this[r],a)]};la(L,function(){return"_global"});L.U=function(){};L.Y=function(){return j};var re=function(){};R(re,Qd);re[C].valueOf=function(){for(var a="",b=this.__swiffy_d;b&&b[Qa]();)a="."+b[Qa]()+a,b=b[ua]();b&&b instanceof qf&&b.g.ha==b&&(a="_level0"+a);return a};
var qe={_x:{get:function(){return this.__swiffy_d.L().e/20},set:function(a){var b=this.__swiffy_d,a=Tf(b,a,"_x");if(N(a)){var c=b.L();b[Oa](c.translate(a*20-c.e,0));b.ka()}}},_y:{get:function(){return this.__swiffy_d.L().f/20},set:function(a){var b=this.__swiffy_d,a=Tf(b,a,"_y");if(N(a)){var c=b.L();b[Oa](c.translate(0,a*20-c.f));b.ka()}}},_xscale:{get:function(){var a=this.__swiffy_d.L();return 100*n[Ua](a.a*a.a+a.b*a.b)},set:function(a){var b=this.__swiffy_d,a=Tf(b,a,"_xscale");if(N(a)){var c=b.L();
b[Oa](c.ac(a/(100*n[Ua](c.a*c.a+c.b*c.b)),1));b.ka()}}},_yscale:{get:function(){var a=this.__swiffy_d.L();return 100*n[Ua](a.c*a.c+a.d*a.d)},set:function(a){var b=this.__swiffy_d,a=Tf(b,a,"_yscale");if(N(a)){var c=b.L();b[Oa](c.ac(1,a/(100*n[Ua](c.c*c.c+c.d*c.d))));b.ka()}}},_alpha:{get:function(){return this.__swiffy_d.ea.dd/2.56},set:function(a){var b=this.__swiffy_d,a=Tf(b,a,"_alpha");if(N(a)){var c=b.ea;b.Ma(new Od(c.Vb,c.Ub,c.Tb,c.Sb,c.Rb,c.Qb,a*2.56));b.ka()}}},_visible:{get:function(){return this.__swiffy_d.ya},
set:function(a){var b=this.__swiffy_d,a=Tf(b,a,"_visible");N(a)&&(b.lg(Boolean(a)),b.ka())}},_rotation:{get:function(){var a=this.__swiffy_d.L();return-180*n.atan2(a.c,a.a)/n.PI},set:function(a){var b=this.__swiffy_d,a=Tf(b,a,"_rotation");if(N(a)){var c=b.L();b[Oa](c.Yf(a*n.PI/-180-n.atan2(c.c,c.a)));b.ka()}}},_name:{get:function(){return this.__swiffy_d[Qa]()},set:function(a){this.__swiffy_d.nb(a);this.__swiffy_d.ka()}},_quality:{get:function(){return 0},set:function(){}},_highquality:{get:function(){return 0},
set:function(){}},_soundbuftime:{get:function(){return 0},set:function(){}},_parent:{get:function(){var a=this.__swiffy_d.eb;return a?a.D():a},set:function(){}},_xmouse:{get:function(){var a=this.__swiffy_d;return Sf(a.za(),a.g.sc).x},set:function(){}},_ymouse:{get:function(){var a=this.__swiffy_d;return Sf(a.za(),a.g.sc).y},set:function(){}},_url:{get:function(){return m.location.href},set:function(){}},_width:{get:function(){var a=this.__swiffy_d,b=a.cb();b.Z(a.L());return(b.G-b.A)/20},set:function(a){var b=
this.__swiffy_d,a=b.g.l().Pa(a);if(a>=0){a/=this._width;var c=b.L();b[Oa](c.ac(a,1));b.ka()}}},_height:{get:function(){var a=this.__swiffy_d,b=a.cb();b.Z(a.L());return(b.H-b.B)/20},set:function(a){var b=this.__swiffy_d,a=b.g.l().Pa(a);if(a>=0){a/=this._height;var c=b.L();b[Oa](c.ac(a,1));b[Oa](c.ac(1,a));b.ka()}}}};var lf=function(){};R(lf,re);var Y=function(){};R(Y,lf);Y[C].gotoAndStop=function(a){var b=this.__swiffy_d;b.ic(b.Wb(a),k)};Y[C].gotoAndPlay=function(a){var b=this.__swiffy_d;b.ic(b.Wb(a),h)};Y[C].play=function(){this.__swiffy_d[Wa]()};Y[C].stop=function(){this.__swiffy_d[cb]()};Y[C].nextFrame=function(){this.__swiffy_d.Re()};Y[C].prevFrame=function(){this.__swiffy_d.Se()};Y[C].onEnterFrame=function(){};Y[C].onLoad=function(){};
Y[C].globalToLocal=function(a){var b=this.__swiffy_d,c=b.g.l(),d=c.le(a);if(d!=j){var e=c.j(a,"x"),c=c.j(a,"y"),b=b.za(),d=Sf(b,d);a[e]=d.x;a[c]=d.y}};Y[C].localToGlobal=function(a){var b=this.__swiffy_d,c=b.g.l(),d=c.le(a);if(d!=j){var e=c.j(a,"x"),c=c.j(a,"y"),b=b.za(),d=new W(d.x*20,d.y*20);d.Z(b);d.x/=20;d.y/=20;a[e]=d.x;a[c]=d.y}};
Y[C].attachMovie=function(a,b,c,d){var e=this.__swiffy_d,a=e.g.Td[a];if(N(a)&&(a=e.$c(a),a.zc=h,a.nb(b),a.Ca(),a[tb](),e.uc(c),e.bd(a,c),N(d))){var b=a.D(),g;for(g in d)b[g]=d[g]}};Y[C].duplicateMovieClip=function(a,b,c){var d=this.__swiffy_d,e=d[ua]();if(e&&(a=d.duplicate(e,a,b),N(c))){var a=a.D(),g;for(g in c)a[g]=c[g]}};Y[C].removeMovieClip=function(){var a=this.__swiffy_d,b=a[ua]();a.zc&&b&&(a.J(),b[pb](a))};
Y[C].swapDepths=function(a){var b=this.__swiffy_d,c=b[ua]();if(c){if(a instanceof re){a=a.__swiffy_d;if(a[ua]()!=c)return;a=a[x]}else a=Number(a);c.Ld(b[x],a)}};l[Ka](Y[C],function(){var a={},b;for(b in xe){var c=xe[b];a[c]={get:ze,set:Zb(ye,c)}}return a}());Y[C].getBytesLoaded=function(){return this.getBytesTotal()};Y[C].getBytesTotal=function(){return 1E3};
Y[C].getBounds=function(a){var b=this.__swiffy_d,c=b.cb();if(N(a)){var d=j;a instanceof Y?d=a.__swiffy_d:Sb(a)&&(d=b.g.l().Kb(b,a));if(d!=j)a=d.za().ud(),c.Z(a.multiply(b.za()));else return}b={};b.A=c.A/20;b.G=c.G/20;b.B=c.B/20;b.H=c.H/20;return b};Y[C].hitTest=function(a,b,c){if(N(a)){var d=this.__swiffy_d,e=d.cb();e.Z(d.za());if(!N(b)&&!N(c)){if(b=j,a instanceof Y?b=a.__swiffy_d:Sb(a)&&(b=d.g.l().Kb(d,a)),b!=j)return a=b.cb(),a.Z(b.za()),e.Df(a)}else if(N(b))return e.contains(a*20,b*20)}return k};
var Ff={_currentframe:{get:function(){return n.max(1,this.__swiffy_d.M+1)},set:function(){}},_totalframes:{get:function(){return this.__swiffy_d.tb},set:function(){}},_framesloaded:{get:function(){return this.__swiffy_d.sa},set:function(){}},_root:{get:function(){return this.__swiffy_d.g.ha.D()},set:function(){}},_target:{get:function(){var a=this._root;if(this==a)return"/";else{for(var b="",c=this;c&&c!=a;)b="/"+c._name+b,c=c._parent;return b}},set:function(){}},_level0:{get:function(){return this.__swiffy_d.g.ha.D()},
set:function(){}}};var Jf=function(a){this.I=a};Jf[C].addListener=function(){};Jf[C].removeListener=function(){};l[Ta](Jf[C],"height",{get:function(){return this.I.Zd/20},set:function(){}});l[Ta](Jf[C],"width",{get:function(){return this.I.$d/20},set:function(){}});var Z=function(a){l[Ta](this,"__swiffy_s",{value:a});this.Color=of(a)};Z[C].clearInterval=function(a){aa.clearInterval(a)};Z[C].clearTimeout=function(a){aa.clearTimeout(a)};Z[C].escape=function(a){return escape(a)[Da](/[-@*+.\/_]/g,function(a){return"%"+a[wb](0)[z](16).toUpperCase()})};Z[C].parseFloat=function(a){return parseFloat(a)};Z[C].parseInt=function(a,b){return ea(a,b)};Z[C].isFinite=function(a){return isFinite(a)};Z[C].isNaN=function(a){return isNaN(a)};Z[C].unescape=function(a){return unescape(a)};
Z[C].setInterval=function(a){if(O(a)&&arguments[A]>=2)return aa.setInterval[I](j,arguments);else if(Tb(a)&&arguments[A]>=3&&O(a[arguments[1]])){var b=P(a[arguments[1]],a),c=arguments[2],d=ca[C][Ca][G](arguments,3);return aa.setInterval[I](j,[b,c].concat(d))}};Z[C].setTimeout=function(a,b){if(O(a)&&arguments[A]>=2)return aa.setTimeout[I](j,arguments)};Z[C].updateAfterEvent=function(){var a=this.__swiffy_s;setTimeout(function(){a.q()},0)};Z[C].Math=n;Z[C].MovieClip=Y;Z[C].String=String;
Z[C].Number=Number;Z[C].Date=Sd;Z[C].Array=Td;Z[C].Object=Qd;Z[C].Key=Ud;l[Ta](Z[C],"Mouse",{get:function(){return this.__swiffy_s.Nb},set:function(){}});l[Ta](Z[C],"Stage",{get:function(){return this.__swiffy_s.kf},set:function(){}});var If=function(a){this.F=[];this.X=this.S=j;this.je=[];this.ia=[];this.ha=a;this.vf=this.ie();this.Ic=[];this.Dc=k;this.Q=0;this.T=4;this.Xd=new dg(this,a.g)};L=If[C];L.Hd=function(a){this.Ic[p](P(function(){this.Qc(a)},this))};L.zd=function(a){this.Ic[p](a)};L.td=function(){if(!this.Dc){for(this.Dc=h;this.Ic[A]>0;)this.Ic[va]()();this.Dc=k}};L.ie=function(){return(new Date).getTime()};
L.reset=function(a){this.S=this.X=a;this.F=[];this.Q=0;this.T=4;this.F.length+=this.T;this.n=new cg(this,this.Xd,a.D())};L.Qc=function(a){if(!a.i.fe){this.reset(a.i);for(var b=0;b<a.ye[A];)b=a.ye[b][G](this,b+1)}};L.ve=function(a,b){return this.bf(a)[G](this,b)};var eg=function(a){a=a[Da](/\.\.|\/:?|:/g,function(a){return a==".."?"_parent":"."});a[0]=="."&&(a="_root"+a);a[a[A]-1]=="."&&(a=a.substring(0,a[A]-1));return a};
If[C].Fc=function(a,b){if(!N(b))b=this.S;var c=a[E](":");return c[A]>1?{path:this.Kb(b,c[0]),Mb:c[1]}:{path:b,Mb:a}};If[C].ug=function(a){for(var b=0;b<this.je[A];b++)this.je[b](a)};var fg=new Boolean(k),gg=new Number(0),hg=new String("");L=If[C];
L.j=function(a,b){if(this.X.Ta>=7){if(a instanceof re){if(b in a)return b;var c=b[Nb]();if(c in a&&ig[s](c)>-1)return c}}else{switch(typeof a){case "object":case "function":break;case "boolean":a=fg;break;case "number":a=gg;break;case "string":a=hg;break;default:return b}if(b in a)return b;c=b[Nb]();if(c in a)return c;do for(var d=l.getOwnPropertyNames(a),e=0;e<d[A];e++)if(d[e][Nb]()==c)return d[e];while(a=a[zb])}return b};
L.le=function(a){if(Tb(a)){var b=a[this.j(a,"x")],a=a[this.j(a,"y")];if(typeof b=="number"&&typeof a=="number")return new W(b,a)}return j};L.U=function(a){(this.S=a)?this.n.U(a.D()):this.n.U(j)};L.Y=function(){return this.S};L.push=function(a){this.F[p](a)};L.pop=function(){if(this.F[A]>this.Q+this.T)return this.F.pop()};L.Yc=function(a){var b=this.X.Ta;typeof a=="boolean"&&b<5&&(a=a?"1":"0");return!N(a)&&b<7?"":a+""};
L.Pa=function(a){var b=this.X.Ta;return!N(a)||a===j?b<7?0:Number.NaN:Sb(a)?(a=Number(a),b<5&&isNaN(a)?0:a):Number(a)};L.k=function(){return this.Pa(this.pop())};L.s=function(){return this.Yc(this.pop())};L.pc=function(){var a=this.pop();typeof a=="string"&&(a=Number(a));return Boolean(a)};L.Pc=function(){var a=this.pop();if(a instanceof re)return a;if(a=this.Kb(this.S,String(a)))return a.D()};
L.Kb=function(a,b){if(!a||!b)return a;for(var b=eg(b),c=a.D(),d=b[E]("."),e=0;e<d[A]&&c;e++)c=c[this.j(c,d[e])];return c?c.__swiffy_d:j};L.Nf=function(a){var b=this.n.Y();if(a)for(var a=eg(a),a=a[E]("."),c=0;c<a[A]&&b;c++)b=b[this.j(b,a[c])];return b};L.sf=function(a,b,c,d){this.Dc||this.reset(c);a=this.Fc(a,c);if(a[w]){var c=a[w].D(),e=this.j(c,a.Mb);N(a[w].Ib[e])||(a[w].Ib[e]=[]);a[w].Ib[e][p](b);if(e in c&&(b.kd(String(c[e])),d=c[e],l.getOwnPropertyDescriptor(c,e).get))return;l[Ta](c,e,jg(d,a[w].Ib[e]))}};
var jg=function(a,b){var c=a;return{get:function(){return c},set:function(a){c=a;for(var e=0;e<b[A];e++)b[e].kd(a)},configurable:h}};If[C].zf=function(a,b,c){a=this.Fc(a,c);a[w]&&(c=this.j(a[w].D(),a.Mb),jc(a[w].Ib[c],b))};If[C].$f=function(a,b){b[s]("_level")!=0&&a[Nb]()[s]("fscommand:")!=0&&a!="undefined"&&(b==""&&(b="_self"),aa.open(a,b))};If[C].Ya=function(a){for(var b=[],c=0;c<a[A];++c)b[c]=this.bf(a[c]);return b};If[C].bf=function(a){var b=$[a[y]];return!b?P(kg,this,a[y]):b.da?b(a,this):b};
var ig="_x,_y,_xscale,_yscale,_currentframe,_totalframes,_alpha,_visible,_width,_height,_rotation,_target,_framesloaded,_name,_droptarget,_url,_highquality,_focusrect,_soundbuftime,_quality,_xmouse,_ymouse".split(","),$={4:function(a){var b=this.S;b!=j&&b.Re();return a},5:function(a){var b=this.S;b!=j&&b.Se();return a},6:function(a){var b=this.S;b!=j&&b[Wa]();return a},7:function(a){var b=this.S;b!=j&&b[cb]();return a},9:function(a){var b=this.S;b!=j&&b.sb().dg();return a},10:function(a){var b=this.k();
this[p](this.k()+b);return a},11:function(a){var b=this.k();this[p](this.k()-b);return a},12:function(a){var b=this.k();this[p](this.k()*b);return a},13:function(a){var b=this.k();this[p](this.k()/b);return a},14:function(a){var b=this.k(),b=this.k()==b;this.X.Ta<5&&(b=b?1:0);this[p](b);return a},15:function(a){var b=this.k();this[p](this.k()<b);return a},16:function(a){var b=this.pc();this[p](this.pc()&&b);return a},17:function(a){var b=this.pc();this[p](this.pc()||b);return a},18:function(a){this[p](!this.pc());
return a},19:function(a){var b=this.s();this[p](this.s()==b);return a},20:function(a){this[p](this.s()[A]);return a},21:function(a){var b=Number(this.pop()),c=n.max(0,Number(this.pop())-1);this[p](this.s().substr(c,b));return a},23:function(a){this.pop();return a},24:function(a){var b=this.k(),b=b<0?n.ceil(b):n[Ga](b);this[p](b);return a},28:function(a){var b=this.s(),b=eg(b),b=b[E]("."),c=this.n.get(b[0]);if(b[A]>1){var d;for(d=1;N(c)&&d<b[A]-1;++d)c=c[this.j(c,b[d])];N(c)&&(c=c[this.j(c,b[d])])}this[p](c);
return a},29:function(a){var b=this.pop(),c=this.s(),c=eg(c),d=c[E](".");if(d[A]==1)this.n.set(c,b);else{var c=this.n.get(d[0]),e;for(e=1;N(c)&&e<d[A]-1;++e)c=c[this.j(c,d[e])];N(c)&&(c[this.j(c,d[e])]=b)}return a},33:function(a){var b=this.s();this[p](this.s()+b);return a},34:function(a){var b=ig[this.k()],c=this.Pc();c?this[p](c[b]):this[p](f);return a},35:function(a){var b=this.pop(),c=ig[this.k()],d=this.Pc();d&&c&&(d[c]=b);return a},36:function(a){var b=this.k(),c=this.s(),d=this.Pc();d&&d.__swiffy_d.duplicate(this.S,
c,b);return a},37:function(a){var b=this.Pc();b instanceof Y&&b.removeMovieClip();return a},38:function(a){var b=this.pop();this.ug(N(b)?this.Yc(b):"undefined");return a}},kg=function(a,b){return b};$[51]=function(a){var b=this.k();this[p](String.fromCharCode(b));return a};$[50]=function(a){this[p](this.s()[wb](0));return a};$[52]=function(a){this[p](this.ie()-this.vf);return a};$[48]=function(a){var b=this.k(),c;do c=n[Ga](n.random()*b);while(c==b&&b>0);this[p](c);return a};
$[60]=function(a){var b=this.pop();this.n.Aa(this.pop(),b);return a};$[65]=function(a){this.n.bc(this.pop());return a};$[59]=function(a){var b=this.s(),b=eg(b),c=b[E](".");if(c[A]==1)this.n.fb(b);else{var b=this.n.get(c[0]),d;for(d=1;N(b)&&d<c[A]-1;++d)b=b[this.j(b,c[d])];N(b)&&delete b[this.j(b,c[d])]}return a};$[62]=function(){qa(this,this.pop());return Number.MAX_VALUE};$[63]=function(a){var b=this.k();this[p](this.k()%b);return a};
$[71]=function(a){var b=this.pop(),c=this.pop();Sb(b)||Sb(c)?this[p](this.Yc(c)+this.Yc(b)):this[p](this.Pa(c)+this.Pa(b));return a};$[72]=function(a){var b=this.pop(),c=this.pop();if(!Sb(b)||!Sb(c))b=this.Pa(b),c=this.Pa(c);b!==b||c!==c?this[p](f):this[p](c<b);return a};$[103]=function(a){var b=this.pop();this[p](this.pop()>b);return a};$[73]=function(a){var b=this.pop();this[p](this.pop()==b);return a};$[102]=function(a){var b=this.pop();this[p](this.pop()===b);return a};
$[41]=function(a){var b=this.s();this[p](this.s()<b);return a};$[104]=function(a){var b=this.s();this[p](this.s()>b);return a};$[105]=function(a){var b=this.pop(),c=this.pop();R(c,b);return a};$[74]=function(a){this[p](this.k());return a};$[75]=function(a){this[p](this.s());return a};$[76]=function(a){var b=this.pop();this[p](b);this[p](b);return a};$[77]=function(a){var b=this.pop(),c=this.pop();this[p](b);this[p](c);return a};
$[78]=function(a){var b=this.s(),c=this.pop(),d=f;c&&(d=c[this.j(c,b)]);this[p](d);return a};$[79]=function(a){var b=this.pop(),c=this.s(),d=this.pop();d&&(d[this.j(d,c)]=b);return a};$[80]=function(a){var b=this.k();this[p](++b);return a};$[81]=function(a){var b=this.k();this[p](--b);return a};$[96]=function(a){var b=this.k(),c=this.k();this[p](b&c);return a};$[97]=function(a){var b=this.k(),c=this.k();this[p](b|c);return a};$[98]=function(a){var b=this.k();this[p](this.k()^b);return a};
$[99]=function(a){var b=this.k();this[p](this.k()<<b);return a};$[100]=function(a){var b=this.k();this[p](this.k()>>b);return a};$[101]=function(a){var b=this.k();this[p](this.k()>>>b);return a};$[58]=function(a){var b=this.s(),c=this.pop();c&&delete c[this.j(c,b)];return a};$[129]=function(a,b){return P(lg,b,a.frame)};$[129].da=h;var lg=function(a,b){var c=this.S;c!=j&&c.ic(a,k);return b};$[140]=function(a,b){return P(mg,b,a.label)};$[140].da=h;
var mg=function(a,b){var c=this.S;if(c!=j){var d=c.Wb(a);d!=f&&c.ic(d,k)}return b};$[136]=function(a,b){return P(ng,b,a.constants)};$[136].da=h;var ng=function(a,b){this.ia=a;return b};$[32]=function(a){var b=this.pop();b=b instanceof re?b.__swiffy_d:(b=String(b))?this.Kb(this.X,b):this.n.U(j).__swiffy_d;this.U(b);return a};$[69]=function(a){var b=this.pop(),c=f;b instanceof re&&(c=b.valueOf());this[p](c);return a};$[305]=function(a,b){return P(og,b,a.value)};$[305].da=h;
var og=function(a,b){this[p](a);return b};$[306]=function(a){this[p](f);return a};$[307]=function(a){this[p](Number[xa]);return a};$[308]=function(a){this[p](Number.NEGATIVE_INFINITY);return a};$[309]=function(a){this[p](Number.NaN);return a};$[304]=function(a,b){return P(pg,b,a.index)};$[304].da=h;var pg=function(a,b){this[p](this.ia[a]);return b};$[303]=function(a,b){return P(qg,b,a.index)};$[303].da=h;var qg=function(a,b){a>=0&&a<this.T?this[p](this.F[this.Q+a]):this[p](f);return b};
$[135]=function(a,b){return P(rg,b,a.index)};$[135].da=h;var rg=function(a,b){a>=0&&a<this.T&&(this.F[this.Q+a]=this.F[this.F[A]-1]);return b};$[154]=function(a){var b=this.s();this.$f(this.s(),b);return a};$[148]=function(a,b){return P(sg,b,b.Ya(a[ob]))};$[148].da=h;var sg=function(a,b){var c=this.pop();if(!(c instanceof Qd))return b;var d=this.n;this.n=new bg(this,d,c);for(c=0;c<a[A];)c=a[c][G](this,c+1);this.n=d;return b};$[155]=function(a,b){return P(tg,b,a.args,b.Ya(a[ob]))};$[155].da=h;
var tg=function(a,b,c){var d=this,e=this.ia,g=this.n,i=function(){var c=d.n,i=d.Q,B=d.T,ha=d.ia,J=d.S,X=d.X,H;d.X.Ta>5?(H=g,d.n=new ag(d,H),d.U(g.Y().__swiffy_d)):(H=new cg(d,d.Xd,this),d.n=new ag(d,H),this instanceof re&&d.U(this.__swiffy_d));d.ia=e;d.Q=d.F[A];d.T=4;d.F.length+=d.T;for(H=0;H<a[A];++H)d.n.Aa(a[H],arguments[H]);d.n.Aa("this",this);qa(d,f);for(H=0;H<b[A];)H=b[H][G](d,H+1);ma(d.F,d.Q);d.n=c;d.Q=i;d.T=B;d.ia=ha;d.X=X;d.S=J;return d[vb]};R(i,Qd);this[p](i);return c};
$[142]=function(a,b){return P(ug,b,a.args,b.Ya(a[ob]),a.preloads,a.suppress,a.registerCount)};$[142].da=h;
var ug=function(a,b,c,d,e,g){var i=this,q=this.ia,u=this.n,B=function(){var g=i.n,B=i.Q,X=i.T,H=i.ia,vg=i.Y(),wg=i.X;i.n=new ag(i,u);i.ia=q;i.U(u.Y().__swiffy_d);i.Q=i.F[A];i.T=e;i.F.length+=i.T;d&4||i.n.Aa("this",this);d&1||i.n.Aa("super",new $f(this,arguments.callee));for(var Q=0;Q<c[A];++Q)i.F[i.Q+Q+1]=i.n.get(c[Q]);for(Q=0;Q<a[A];++Q)Sb(a[Q])?i.n.Aa(a[Q],arguments[Q]):i.F[i.Q+a[Q]]=arguments[Q];qa(i,f);for(Q=0;Q<b[A];)Q=b[Q][G](i,Q+1);ma(i.F,i.Q);i.n=g;i.Q=B;i.T=X;i.ia=H;i.X=wg;i.U(vg);return i[vb]};
R(B,Qd);this[p](B);return g};$[61]=function(a){for(var b=this.s(),c=this.k(),d=[],e=0;e<c;++e)d[e]=this.pop();this[p](this.n[G](b,d));return a};
$[82]=function(a){for(var b=this.pop(),c=this.pop(),d=this.k(),e=[],g=0;g<d;g++)e[g]=this.pop();if(c!=j)if(b){var d=f,i;if(c instanceof $f){i=c.object;for(var q=k,u=i[kb];u;u=u.p&&u.p[kb]){if(q){d=u[C][String(b)];break}for(var B=l.getOwnPropertyNames(u[C]),g=0;g<B[A]&&!q;g++)u[C][B[g]]===c.method&&(q=h)}}else d=c[this.j(c,String(b))],i=c;d?this[p](d[I](i,e)):this[p](f)}else if(c instanceof $f)b=c.method.p[kb],O(b)?this[p](b[I](c.object,e)):this[p](f);else this[p](c[I](this.n.Y(),e));else this[p](f);
return a};$[64]=function(a){for(var b=this.n.get(this.s()),c=this.k(),d=[],e=0;e<c;++e)d[e]=this.pop();O(b)||(b=Qd);c=l.create(b[C]);b[I](c,d);this[p](c);return a};$[83]=function(a){for(var b=this.pop(),c=this.pop(),d=this.k(),e=[],g=0;g<d;g++)e[g]=this.pop();d=f;c!=j&&(d=b?c[this.j(c,String(b))]:c);O(d)||(d=Qd);b=l.create(d[C]);d[I](b,e);this[p](b);return a};$[84]=function(a){var b=this.pop(),c=this.pop(),d=k;O(b)&&(d=c instanceof b);this[p](d);return a};
$[67]=function(a){for(var b=new Qd,c=this.k(),d=0;d<c;d++){var e=this.pop(),g=this.s();b[g]=e}this[p](b);return a};$[66]=function(a){for(var b=[],c=this.k(),d=0;d<c;d++){var e=this.pop();b[d]=e}this[p](b);return a};$[68]=function(a){var b=this.pop();this[p](b instanceof Y?"movieclip":b==j||b==f?String(b):typeof b);return a};$[85]=function(a){var b=this.pop();this[p](j);for(var c in b)this[p](c);return a};$[153]=function(a,b){return P(xg,b,a[qb])};$[153].da=h;var xg=function(a){return a};
$[157]=function(a,b){return P(yg,b,a[qb])};$[157].da=h;var yg=function(a,b){return Boolean(this.pop())?a:b};$[158]=function(a){var b=this.Fc(this.s());if(b[w]){var c=b[w].Wb(b.Mb);if(c!=f&&(c=b[w].xf(c))){for(var d=this.n,e=this.Q,g=this.T,i=this.ia,q=this.Y(),u=this.X,B=this.F,ha=0;ha<c[A];ha++)c[ha].Zb(b[w]);this.F=B;this.n=d;this.Q=e;this.T=g;this.ia=i;this.X=u;this.U(q)}}return a};$[159]=function(a,b){return P(zg,b,a.frameBias,a[Wa])};$[159].da=h;
var zg=function(a,b,c){var d=this.Fc(this.s());if(d[w]){var e=d[w].Wb(d.Mb);e!=f&&d[w].ic(e+a,b)}return c};